{
  "hash": "7ad5abd016329200a9cbecb659199bea",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"2. The value premium in the data\"\naliases: [/financial-data.html]\n---\n\n[Chapter 1](01-two-free-numbers.qmd) argued that a DCF's two free numbers cannot price cash-flow risk. Before building the model that can, I need the facts the model must match. The chapter establishes them from the 1930 to 2003 sample my paper uses. Value stocks out-earned growth stocks by about six percentage points a year while trading at persistently lower valuations, so the higher return and the lower price go together. The obvious repair fails in the data as it failed in the model, because value's market beta is nowhere near large enough to explain six points.\n\nOne rule governs the construction. The series I construct (returns, dividends, price-dividend ratios, and consumption) are targets for the model rather than inputs to it. Average returns enter none of the model's inputs, and they appear only in the tables the model has to match. A model whose target facts leaked into its inputs would prove nothing.\n\nI sort stocks into portfolios by book-to-market equity, which is book value from the accounting statements divided by market value from prices, following Fama and French (1993). The sort forms June quintiles of ordinary shares with NYSE breakpoints. Growth is the bottom fifth, which is expensive relative to book value. Value is the top fifth, which is cheap relative to book value, and the market is the value-weighted whole. The sort hands the model two claims whose dividends behave differently, so any difference in prices and premia must come from cash-flow risk rather than from an assumption.\n\n## The economics: recovering cash flows from returns\n\nThe inconvenient fact of the construction is that CRSP, the standard file of U.S. stock returns, stores returns rather than dividends. It records two versions of each month's return: $r_t$, which includes the dividend, and $r_t^x$, the capital gain alone. Campbell and Shiller (1988) noticed that the gap between them is the dividend, and recovered it by scaling with a cumulated price index $V$:\n\n$$\nD_t = \\left(r_t - r_t^{x}\\right) V_{t-1},\n\\qquad\nV_t = V_{t-1}\\left(1 + r_t^{x}\\right).\n$$ {#eq-cs}\n\nIn words, whatever the with-dividend return earned beyond the price return was the dividend, and the dividend was paid on last month's value.\n\n::: {.callout-note collapse=\"true\" title=\"Derivation: why the identity recovers dividends\"}\nFor a portfolio worth $V_{t-1}$ at the end of last month, the two return definitions are\n\n$$\n1 + r_t = \\frac{V_t + D_t}{V_{t-1}}, \\qquad 1 + r_t^{x} = \\frac{V_t}{V_{t-1}},\n$$\n\nwhere $V_t$ is this month's ex-dividend value. Subtracting the second from the first gives $r_t - r_t^{x} = D_t / V_{t-1}$, which is @eq-cs. Cumulating $V$ with the capital-gain return alone keeps the index self-consistent, because dividends are paid out rather than reinvested into the price index. Summing the monthly $D_t$ within a calendar year gives the annual dividend; the year-end $V$ over that sum is the price-dividend ratio.\n:::\n\nDividends and prices from @eq-cs are nominal. I deflate them by the PCE price deflator, because the household in the model consumes real goods. Log differences of real annual dividends give dividend growth $\\Delta d$. Two more series complete the dataset. Consumption is real per-capita nondurables plus services from the national accounts, because durables behave like investment rather than consumption. The risk-free rate is the real return on the three-month Treasury bill, computed as the nominal bill return less a twelve-month moving average of inflation. One month of inflation is too noisy to be anyone's forecast.\n\nThe full pipeline, which pulls CRSP through WRDS, Compustat book equity, and the Davis-Fama-French book values for the years before 1960, is described in the appendix at the end of the chapter. The main argument does not need it. The repository ships the three files the pipeline writes, and every number below is computed live from them.\n\n## Hands-on: the facts, from the shipped files\n\n::: {#4ee7a458 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\n# Data bootstrap: use the repo's committed CSVs, or fetch them when this\n# notebook runs outside the repository.\nfrom pathlib import Path\nimport urllib.request\n\nDATA = Path(\"../../data\")\nif not DATA.exists():\n    DATA = Path(\"data\")\n    DATA.mkdir(exist_ok=True)\n    base = (\"https://raw.githubusercontent.com/tlorans/\"\n            \"kiku-value-premium-replication/main/data/\")\n    for f in (\"annual_panel.csv\", \"consumption_annual.csv\", \"rf_annual.csv\"):\n        if not (DATA / f).exists():\n            urllib.request.urlretrieve(base + f, DATA / f)\n```\n:::\n\n\n::: {#8c5f7d3d .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport lrrcs as lrr\n\npanel = pd.read_csv(DATA / \"annual_panel.csv\")\ndc = pd.read_csv(DATA / \"consumption_annual.csv\")\nrf = pd.read_csv(DATA / \"rf_annual.csv\")\npanel[\"year\"].min(), panel[\"year\"].max(), sorted(panel[\"claim\"].unique())\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\n(np.int64(1930), np.int64(2003), ['Growth', 'Market', 'Value'])\n```\n:::\n:::\n\n\nThe panel holds three claims with seventy-four years each. The next cell prints the summary table, with returns and dividend growth in percent per year and Newey-West standard errors:\n\n::: {#8249b7c9 .cell execution_count=3}\n``` {.python .cell-code}\nlrr.table_i(panel).round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>claim</th>\n      <th>ret_mean</th>\n      <th>ret_se</th>\n      <th>ret_sd</th>\n      <th>ret_sd_se</th>\n      <th>dg_mean</th>\n      <th>dg_se</th>\n      <th>dg_sd</th>\n      <th>dg_sd_se</th>\n      <th>log_pd</th>\n      <th>log_pd_se</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Growth</td>\n      <td>7.49</td>\n      <td>1.93</td>\n      <td>20.02</td>\n      <td>1.60</td>\n      <td>0.33</td>\n      <td>1.16</td>\n      <td>14.35</td>\n      <td>2.95</td>\n      <td>3.62</td>\n      <td>0.17</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Value</td>\n      <td>13.67</td>\n      <td>1.63</td>\n      <td>29.67</td>\n      <td>5.40</td>\n      <td>3.53</td>\n      <td>4.13</td>\n      <td>47.72</td>\n      <td>18.63</td>\n      <td>3.34</td>\n      <td>0.19</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Market</td>\n      <td>8.52</td>\n      <td>1.75</td>\n      <td>20.10</td>\n      <td>2.29</td>\n      <td>0.92</td>\n      <td>0.94</td>\n      <td>11.02</td>\n      <td>2.99</td>\n      <td>3.33</td>\n      <td>0.13</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nRead the middle columns before the first one. Value's dividend growth is more volatile, at 47.72 percent against growth's 14.35. The comparison is a statement about cash flows, because no average return entered its construction. The return columns then record the facts to explain. Value earned 13.67 percent a year against growth's 7.49, and its mean log price-dividend ratio is lower, 3.34 against 3.62. The higher premium and the lower valuation appear together. My paper's Table I, on its data vintage, prints the same pattern: 13.88 against 7.81 on returns, log P/D of 3.25 against 3.61, and volatilities of 29.9 and 20.2.\n\n### The spread and the Sharpe ratios\n\n::: {#d049a81b .cell execution_count=4}\n``` {.python .cell-code}\nwide_ret = panel.pivot(index=\"year\", columns=\"claim\", values=\"ret\")\nwide_dd = panel.pivot(index=\"year\", columns=\"claim\", values=\"dgrowth\")\nwide_pd = panel.pivot(index=\"year\", columns=\"claim\", values=\"pd\")\nrf_s = rf.set_index(\"year\")[\"rf\"]\n\nspread = wide_ret[\"Value\"].mean() - wide_ret[\"Growth\"].mean()\nprint(f\"value-growth return spread: {spread * 100:.2f} pp/yr\")\nfor c in (\"Growth\", \"Value\", \"Market\"):\n    sharpe = (wide_ret[c] - rf_s).mean() / wide_ret[c].std(ddof=1)\n    print(f\"{c:7s} Sharpe ratio: {sharpe:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nvalue-growth return spread: 6.18 pp/yr\nGrowth  Sharpe ratio: 0.37\nValue   Sharpe ratio: 0.46\nMarket  Sharpe ratio: 0.42\n```\n:::\n:::\n\n\nThe spread is 6.18 points a year over seventy-four years. Value is more volatile, so the first question is whether the premium only compensates for volatility. It does not, because value's Sharpe ratio of 0.46 is higher than growth's 0.37 and the market's 0.42. Per unit of return volatility, value still pays more. (The real bill rate on my reconstruction averages near zero, at 0.07 percent as printed below, so the Sharpe ratios barely depend on it. My paper's vintage prints a mean real rate of 0.91 percent.)\n\nCompounded over the sample, the spread is large:\n\n::: {#bb45e047 .cell execution_count=5}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\ncum = np.log((1.0 + wide_ret[[\"Value\", \"Growth\"]]).cumprod())\ngap = cum[\"Value\"] - cum[\"Growth\"]\nfig, ax = plt.subplots(figsize=(7, 3.8))\nax.plot(gap.index, gap.values)\nax.axhline(0.0, lw=0.8, color=\"gray\")\nax.set_xlabel(\"Year\")\nax.set_ylabel(\"Cumulative log return gap\")\nprint(f\"terminal log gap: {gap.iloc[-1]:.2f}  (x{np.exp(gap.iloc[-1]):.1f})\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nterminal log gap: 2.97  (x19.6)\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Cumulative log return of the value portfolio minus the growth portfolio, 1930 to 2003. The terminal gap of about 3 log points means a dollar compounding in value grew to roughly nineteen times a dollar compounding in growth.](02-value-premium-in-the-data_files/figure-html/cell-6-output-2.svg){}\n:::\n:::\n\n\nThe valuation half of the fact is also visible year by year:\n\n::: {#8c1571aa .cell execution_count=6}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(7, 3.8))\nax.plot(wide_pd.index, np.log(wide_pd[\"Growth\"]), label=\"Growth\")\nax.plot(wide_pd.index, np.log(wide_pd[\"Value\"]), label=\"Value\")\nax.set_xlabel(\"Year\")\nax.set_ylabel(\"log(P/D)\")\nax.legend(frameon=False)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Log price-dividend ratio of the growth and value portfolios, 1930 to 2003. Value trades at a lower multiple of its dividends in most years of the sample, so the market persistently prices its cash flows as riskier.](02-value-premium-in-the-data_files/figure-html/cell-7-output-1.svg){}\n:::\n:::\n\n\n### Returns comove more than cash flows\n\nThe rest of the course builds on the following clue. If value and growth returns moved independently, a six-point spread would be less surprising, because some difference in exposures would be doing visible work. Compare how the two portfolios comove in returns and in cash flows:\n\n::: {#60a9ed52 .cell execution_count=7}\n``` {.python .cell-code}\nprint(f\"return correlation, value & growth          : \"\n      f\"{wide_ret['Value'].corr(wide_ret['Growth']):.2f}\")\nprint(f\"dividend-growth correlation, value & growth : \"\n      f\"{wide_dd['Value'].corr(wide_dd['Growth']):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nreturn correlation, value & growth          : 0.72\ndividend-growth correlation, value & growth : 0.29\n```\n:::\n:::\n\n\nReturns correlate at 0.72, while dividend growth correlates at only 0.29 (my paper's vintage prints 0.75 and 0.32). The gap means the two portfolios' prices move together far more than their cash flows do. A common discount-rate component drives returns at high frequency, while the cash-flow risks that distinguish the claims operate at lower frequencies, where annual correlations barely register them. Any explanation that prices value from high-frequency return comovement therefore misses the relevant risk. The CAPM is the leading example.\n\n### The CAPM fails in the data too\n\n[Chapter 1](01-two-free-numbers.qmd) showed the CAPM misprices the model's claims. The next cell runs the same regression on the data, regressing each portfolio's annual return on the market's:\n\n::: {#1af0a370 .cell execution_count=8}\n``` {.python .cell-code}\nrm_d = wide_ret[\"Market\"] - wide_ret[\"Market\"].mean()\n\ndef capm_beta(claim):\n    ri_d = wide_ret[claim] - wide_ret[claim].mean()\n    return float((rm_d * ri_d).sum() / (rm_d * rm_d).sum())\n\nbetas = {c: round(capm_beta(c), 2) for c in (\"Growth\", \"Value\")}\nprint(f\"CAPM betas: {betas}\")\nimplied = (betas[\"Value\"] - betas[\"Growth\"]) * (wide_ret[\"Market\"] - rf_s).mean()\nprint(f\"CAPM-implied spread: {implied * 100:.2f} pp/yr   \"\n      f\"(actual: {spread * 100:.2f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCAPM betas: {'Growth': 0.95, 'Value': 1.28}\nCAPM-implied spread: 2.79 pp/yr   (actual: 6.18)\n```\n:::\n:::\n\n\nOn my reconstruction, value's beta is 1.28 against growth's 0.95. Value's beta is above one but not high enough, because the implied spread is 2.79 points against the 6.18 observed. The beta gap itself is also fragile. On my paper's data vintage both betas sit near 1.03, and the spread implied by the CAPM is close to zero. Either way the conclusion is the same, and market betas cannot explain the value premium.\n\n### The consumption series that must explain the premium\n\nIn the model, the consumption of the household that holds the claims is what prices them. So I record the last fact now, because it makes the premium a puzzle:\n\n::: {#c6756432 .cell execution_count=9}\n``` {.python .cell-code}\nprint(f\"{len(dc)} years of consumption growth: mean \"\n      f\"{dc['dc'].mean() * 100:.2f} %, volatility {dc['dc'].std(ddof=1) * 100:.2f} %\")\nprint(f\"mean real T-bill (this reconstruction): {rf_s.mean() * 100:.2f} %\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n74 years of consumption growth: mean 1.75 %, volatility 2.37 %\nmean real T-bill (this reconstruction): 0.07 %\n```\n:::\n:::\n\n\nConsumption growth has a volatility of 2.37 percent a year. The rest of the course must explain how a series with such low volatility leads the household to demand six extra points a year on value. The answer will be that the risk comes from a small, persistent component in consumption growth rather than from the year-to-year volatility.\n\n## Takeaways\n\n- Over 1930 to 2003, value out-earned growth by 6.18 points a year on my reconstruction (13.88 against 7.81 on my paper's vintage) while trading at a persistently lower price-dividend ratio. The higher premium and the lower valuation are one joint fact.\n- The premium survives risk adjustment by volatility, because value's Sharpe ratio (0.46) exceeds growth's (0.37).\n- Returns correlate across the two portfolios (0.72) far more than dividend growth does (0.29), so the risks that distinguish the claims appear in cash flows at low frequency rather than in return comovement.\n- The CAPM cannot explain the spread. Betas of 0.95 and 1.28 imply under half the observed premium here, and both betas are near 1.03 on the paper's vintage.\n- Every series is constructed without using average returns, and the tables above are the targets the equilibrium model must match.\n\n## Exercises\n\n1. Compute the value-growth spread decade by decade (group `wide_ret[\"Value\"] - wide_ret[\"Growth\"]` by `year // 10`). In how many decades is it negative? What does the answer say about how long an investor must wait to see the premium?\n2. Recompute the summary table on the post-war sample (1946 to 2003) with `lrr.table_i(panel[panel[\"year\"] >= 1946])`. Which facts survive: the return spread, the valuation ranking, and the gap in dividend volatility?\n3. The market's dividend growth volatility (11.02 percent in the table) is lower than either leg's. Using `wide_dd`, verify the claim and explain why a value-weighted combination can be less volatile than both components.\n\n## Appendix: rebuilding the panel from the raw sources\n\nThe argument above does not need the appendix. The full pipeline is in `lrrcs.empirical` and requires WRDS credentials for the CRSP and Compustat pulls. The code blocks below are shown for orientation and are not executed on this page.\n\nConsumption and the deflator come from FRED, which is public and needs no credentials:\n\n```python\nimport lrrcs as lrr\n\ndc = lrr.load_consumption()      # real per-capita ND+S growth, from NIPA\ndefl = lrr.load_deflator()       # PCE implicit price deflator\n```\n\nThe stock panel needs CRSP monthly returns with `retx`, Compustat book equity merged through the CCM links, and the Davis-Fama-French historical book-equity file for the years before Compustat's coverage begins. `lrr.build_annual_panel` runs the whole construction (the quintile sort, the value weighting, the Campbell-Shiller recovery of @eq-cs, deflation, and the real bill rate) and writes the three CSVs the chapter reads:\n\n```python\nimport tidyfinance as tf\n\ntf.set_wrds_credentials()                    # one-time WRDS setup\npanel = lrr.build_annual_panel(refresh=True) # writes data/annual_panel.csv,\n                                             # data/rf_annual.csv\n```\n\nThe Campbell-Shiller step and the real rate transformation are also exposed directly, so you can apply them to any return pair:\n\n```python\nannual = lrr.campbell_shiller_annual(ret, retx, defl)  # the identity, plus deflation\nrf = lrr.real_rf_from_monthly(t90ret, cpi)             # real 90-day bill\n```\n\n::: {.firewall}\n**Where each number comes from.** Every number above is computed by this page's cells from the repository's `data/annual_panel.csv`, `data/consumption_annual.csv`, and `data/rf_annual.csv` (via `lrr.table_i` and pandas arithmetic); the vintage figures quoted for comparison (13.88 vs 7.81, log P/D 3.25 vs 3.61, correlations 0.75 and 0.32, betas near 1.03, real rate 0.91) are from the paper's printed tables. The chapter can be downloaded as a notebook from the link at the top of the page.\n:::\n\n",
    "supporting": [
      "02-value-premium-in-the-data_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}