{
  "hash": "8d4148aa0f6cdf8696e2d8cd35cae010",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"7. The quadrature solution\"\n---\n\nThe log-linear solution of [Chapter 6](06-log-linear-solution.qmd) is\nan approximation. It assumes the valuation ratio is a linear function\nof the state variables and solves for the slopes. In this chapter we use\nthe second method, the one behind the paper's quantitative results.\nThe method makes no assumption about the shape of the solution. Instead\nit replaces the continuous state space with a finite Markov chain over\n$(x_t, \\sigma_t^2)$ and solves the Euler equation exactly on the\nchain, using the quadrature method of Tauchen and Hussey (1991).\n\nThe chapter first covers the mechanics, meaning how a continuous\neconomy becomes a chain and how a fixed-point iteration prices every\nclaim on it. It then covers a caution that most textbook treatments\nskip. The discretized economy is the economy you actually solve, so its\nartifacts end up in your risk premia unless you check for them. For\nexample, a grid can disperse the state more than the calibrated\nprocess does, and a fixed point iterated in an unstable form can\ndiverge. Both problems appeared in earlier versions of this\nreplication, and both are instructive.\n\n## From a process to a chain\n\nThe state dynamics of [Chapter 5](05-long-run-risks.qmd) give the\nconditional density $f(x_{t+1} \\mid x_t, \\sigma_t)$. Tauchen and Hussey\napproximate integrals against $f$ with a quadrature rule built for a\n*weighting density* $\\omega$:\n\n$$\n\\int p(x')\\, f(x' \\mid x_i)\\, dx'\n\\;\\approx\\; \\sum_{j=1}^{N} \\underbrace{w_j \\,\n\\frac{f(x_j \\mid x_i)}{\\omega(x_j)}}_{\\pi(x_j \\mid x_i)}\\; p(x_j),\n$$ {#eq-th}\n\nwhere the nodes $x_j$ and weights $w_j$ are the Gauss-Hermite rule for\n$\\omega$. Renormalizing each row so probabilities sum to one turns\n@eq-th into a transition matrix. The result is a Markov chain whose\nrows are the conditional distributions of the model, evaluated at the\nquadrature nodes.\n\nThe one free choice is $\\omega$. Tauchen and Hussey suggest the\none-step conditional density at the mean state. With persistence\n$\\rho = 0.98$, the suggested scaling puts all thirty nodes within two\nunconditional standard deviations of $x$. The narrow grid truncates\nthe range the process visits, and we show below that it also removes\nmost of the value premium. The package scales $\\omega$ to the\nunconditional distribution of $x$ instead, so the grid covers the\nstates the economy actually visits.\nThe volatility state $\\sigma_t^2$ gets a standard four-point Tauchen\nchain, as in the paper.\n\n## Pricing on the chain\n\nOn the chain, the Euler equation for the consumption claim is a\nfixed-point problem in the $N$-vector $z_c$ (log price-consumption\nratio, one entry per state). The stable form to iterate is\n\n$$\nz_{c,i} \\;=\\; \\frac{1}{\\theta} \\log\nE_i\\!\\Big[\\exp\\Big(\\theta \\log\\delta\n  + \\theta\\big(1 - \\tfrac{1}{\\psi}\\big)\\,\\Delta c_{t+1}\n  + \\theta \\log\\big(1 + e^{z_{c,j}}\\big)\\Big)\\Big],\n$$ {#eq-fixedpoint}\n\nwhere the expectation runs over the chain's transitions and the\nconsumption shock $\\eta$. Because $\\eta$ and the dividend residuals are\nGaussian and independent of the chain, their integrals have closed\nforms, and one iteration of @eq-fixedpoint is a single matrix-vector\nproduct. The map contracts at rate\n$\\kappa_1 = e^{\\bar z}/(1 + e^{\\bar z}) \\approx 0.999$, so convergence\ntakes thousands of iterations, and each iteration is cheap. Equity\nclaims are then solved the same way, with the converged $z_c$ inside\nthe pricing kernel.\n\n::: {.callout-warning title=\"Warning: iterate the contraction form\"}\nMultiply @eq-fixedpoint through by $\\theta$ and you get an equally\nvalid equation whose iteration map has local slope\n$1 - \\theta = 28$ for the Table II preferences ($\\theta = -27$). An\nearlier version of the package iterated the multiplied form. Every\nclaim's price diverged within a few steps and landed on a numerical\nfloor without any warning, because a clamp at `1e-12` hid the\ndivergence. The fix is one algebraic step, which is to divide by\n$\\theta$ before iterating. The episode also motivates a policy. A\nsolver should raise an error on divergence, and it should never clamp.\n:::\n\n## Hands-on: solve the paper grid\n\n`ModelSolver` builds the chain and runs the fixed points. The paper's\ngrid is 30 nodes for $x$ and 4 for $\\sigma^2$:\n\n::: {#4aec9ad1 .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport lrrcs as lrr\n\nparams = lrr.get_table_ii_params()\nsolver = lrr.ModelSolver(params, n_x=30, n_s=4).solve()\n\nzc = solver.z_c\nprint(f\"consumption claim: mean z_c = {zc.mean():.2f} \"\n      f\"(monthly W/C ratio about {np.exp(zc.mean()):.0f})\")\nfor name, z in solver.z.items():\n    zbar = float(np.dot(solver.stationary, z))\n    print(f\"{name:8s}: stationary mean log P/D (monthly) = {zbar:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nconsumption claim: mean z_c = 6.68 (monthly W/C ratio about 794)\ngrowth  : stationary mean log P/D (monthly) = 5.66\nvalue   : stationary mean log P/D (monthly) = 5.25\nmarket  : stationary mean log P/D (monthly) = 5.47\n```\n:::\n:::\n\n\nThe monthly ratios convert to annual magnitudes by\nsubtracting $\\log 12 \\approx 2.48$. For example, growth prices near\n$e^{5.7 - 2.48} \\approx 25$ times its annual dividend on the paper's\ngrid.\n\nThe exact solution should agree with the approximation of\n[Chapter 6](06-log-linear-solution.qmd) on a fine grid, because the\ntwo methods solve the same economy. We compare the\nnumerical slope $\\partial z/\\partial x$ at the center of the grid with\nthe log-linear $A_1$ evaluated at each claim's own valuation level:\n\n::: {#003db3e4 .cell execution_count=2}\n``` {.python .cell-code code-fold=\"true\"}\nimport pandas as pd\nfrom great_tables import GT\n\nKIKU_GT = dict(table_background_color=\"transparent\", table_font_size=\"0.92rem\",\n               heading_title_font_size=\"1.05rem\", heading_subtitle_font_size=\"0.85rem\",\n               source_notes_font_size=\"0.8rem\", column_labels_font_weight=\"bold\",\n               data_row_padding=\"4px\")\n\nsolver60 = lrr.ModelSolver(params, n_x=60, n_s=4).solve(tol=1e-8)\ng = solver60.grid\nc = params.cons\nis_mid = int(np.argmin(np.abs(g.s2_nodes - c.sigma**2)))\nmid = g.n_x // 2\nrows = []\nfor name, d in params.dividends.items():\n    z2d = solver60.z[name].reshape(g.n_x, g.n_s)\n    slope = ((z2d[mid + 1, is_mid] - z2d[mid - 1, is_mid])\n             / (g.x_nodes[mid + 1] - g.x_nodes[mid - 1]))\n    zbar = float(np.dot(solver60.stationary, solver60.z[name]))\n    kappa1 = np.exp(zbar) / (1 + np.exp(zbar))\n    a1 = (d.phi - 1 / params.prefs.psi) / (1 - kappa1 * c.rho)\n    rows.append({\"claim\": name, \"slope\": slope, \"a1\": a1})\n\n(\n    GT(pd.DataFrame(rows))\n    .tab_header(title=\"Numerical slope against the log-linear elasticity\")\n    .cols_label(claim=\"\", slope=\"dz/dx (numerical)\", a1=\"A1 (log-linear)\")\n    .fmt_number(columns=[\"slope\", \"a1\"], decimals=0)\n    .tab_source_note(\"Slopes from a 60-point grid solved to tolerance 1e-8.\")\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div id=\"hudryehigy\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#hudryehigy table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#hudryehigy thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#hudryehigy p { margin: 0; padding: 0; }\n #hudryehigy .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #hudryehigy .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #hudryehigy .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #hudryehigy .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #hudryehigy .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #hudryehigy .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #hudryehigy .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #hudryehigy .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #hudryehigy .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #hudryehigy .gt_column_spanner_outer:first-child { padding-left: 0; }\n #hudryehigy .gt_column_spanner_outer:last-child { padding-right: 0; }\n #hudryehigy .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #hudryehigy .gt_spanner_row { border-bottom-style: hidden; }\n #hudryehigy .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #hudryehigy .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #hudryehigy .gt_from_md> :first-child { margin-top: 0; }\n #hudryehigy .gt_from_md> :last-child { margin-bottom: 0; }\n #hudryehigy .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #hudryehigy .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #hudryehigy .gt_indent_1 { text-indent: 5px; }\n #hudryehigy .gt_indent_2 { text-indent: calc(5px * 2); }\n #hudryehigy .gt_indent_3 { text-indent: calc(5px * 3); }\n #hudryehigy .gt_indent_4 { text-indent: calc(5px * 4); }\n #hudryehigy .gt_indent_5 { text-indent: calc(5px * 5); }\n #hudryehigy .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #hudryehigy .gt_row_group_first td { border-top-width: 2px; }\n #hudryehigy .gt_row_group_first th { border-top-width: 2px; }\n #hudryehigy .gt_striped { color: #333333; background-color: #F4F4F4; }\n #hudryehigy .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #hudryehigy .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #hudryehigy .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #hudryehigy .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #hudryehigy .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #hudryehigy .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #hudryehigy .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #hudryehigy .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #hudryehigy .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #hudryehigy .gt_left { text-align: left; }\n #hudryehigy .gt_center { text-align: center; }\n #hudryehigy .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #hudryehigy .gt_font_normal { font-weight: normal; }\n #hudryehigy .gt_font_bold { font-weight: bold; }\n #hudryehigy .gt_font_italic { font-style: italic; }\n #hudryehigy .gt_super { font-size: 65%; }\n #hudryehigy .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #hudryehigy .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #hudryehigy .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #hudryehigy .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #hudryehigy .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #hudryehigy .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\">Numerical slope against the log-linear elasticity</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"claim\"></th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"slope\">dz/dx (numerical)</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a1\">A1 (log-linear)</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">growth</td>\n    <td class=\"gt_row gt_right\">96</td>\n    <td class=\"gt_row gt_right\">88</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">value</td>\n    <td class=\"gt_row gt_right\">261</td>\n    <td class=\"gt_row gt_right\">243</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">market</td>\n    <td class=\"gt_row gt_right\">101</td>\n    <td class=\"gt_row gt_right\">94</td>\n  </tr>\n</tbody>\n<tfoot><tr class=\"gt_sourcenotes\"><td class=\"gt_sourcenote\" colspan=\"3\"><span class=\"gt_from_md\">Slopes from a 60-point grid solved to tolerance 1e-8.</span></td></tr></tfoot>\n</table>\n\n</div>\n```\n:::\n:::\n\n\nThe two methods agree within ten percent, claim by claim.\n\n## The grid changes the quantity of risk\n\nThe chain's stationary distribution should reproduce the unconditional\ndispersion of $x$. If it does not, the discretized economy carries a\ndifferent quantity of long-run risk than the one you calibrated. Few\nreplications print the check below:\n\n::: {#a2e015c2 .cell execution_count=3}\n``` {.python .cell-code}\nsd_true = c.phi_x * c.sigma / np.sqrt(1 - c.rho**2)\nfor n_x in (30, 60):\n    s = lrr.ModelSolver(params, n_x=n_x, n_s=4).solve(tol=1e-8)\n    var_x = float(np.dot(s.stationary, s.grid.x_grid**2)\n                  - np.dot(s.stationary, s.grid.x_grid)**2)\n    print(f\"n_x = {n_x}: chain sd(x) = {np.sqrt(var_x):.3e}   \"\n          f\"(true {sd_true:.3e})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nn_x = 30: chain sd(x) = 1.246e-03   (true 1.029e-03)\nn_x = 60: chain sd(x) = 1.029e-03   (true 1.029e-03)\n```\n:::\n:::\n\n\nThe paper's 30-point grid over-disperses expected growth by about a\nfifth. More dispersion in $x$ means more long-run risk, so premia\ncomputed on the 30-point grid run high and prices run low relative to\nthe continuous model. Refining the grid shows the size of the effect:\n\n::: {#73c64a3c .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\nsizes = (20, 30, 40, 60, 100)\nvps, rfs = [], []\nfor n_x in sizes:\n    s = lrr.ModelSolver(params, n_x=n_x, n_s=4).solve(tol=1e-8)\n    m = lrr.compute_asset_pricing_moments(s)\n    vps.append(m[\"value_premium\"])\n    rfs.append(m[\"mean_rf\"])\n\nconv = pd.DataFrame({\"n_x\": sizes, \"vp\": vps, \"rf\": rfs})\n(\n    GT(conv)\n    .tab_header(title=\"Grid convergence of the population moments\")\n    .cols_label(n_x=\"x-grid size\",\n                vp=\"value premium (% per year)\",\n                rf=\"risk-free rate (% per year)\")\n    .fmt_number(columns=[\"vp\", \"rf\"], decimals=2)\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div id=\"sbwkdghhjd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#sbwkdghhjd table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#sbwkdghhjd thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#sbwkdghhjd p { margin: 0; padding: 0; }\n #sbwkdghhjd .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #sbwkdghhjd .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #sbwkdghhjd .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #sbwkdghhjd .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #sbwkdghhjd .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #sbwkdghhjd .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #sbwkdghhjd .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #sbwkdghhjd .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #sbwkdghhjd .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #sbwkdghhjd .gt_column_spanner_outer:first-child { padding-left: 0; }\n #sbwkdghhjd .gt_column_spanner_outer:last-child { padding-right: 0; }\n #sbwkdghhjd .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #sbwkdghhjd .gt_spanner_row { border-bottom-style: hidden; }\n #sbwkdghhjd .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #sbwkdghhjd .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #sbwkdghhjd .gt_from_md> :first-child { margin-top: 0; }\n #sbwkdghhjd .gt_from_md> :last-child { margin-bottom: 0; }\n #sbwkdghhjd .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #sbwkdghhjd .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #sbwkdghhjd .gt_indent_1 { text-indent: 5px; }\n #sbwkdghhjd .gt_indent_2 { text-indent: calc(5px * 2); }\n #sbwkdghhjd .gt_indent_3 { text-indent: calc(5px * 3); }\n #sbwkdghhjd .gt_indent_4 { text-indent: calc(5px * 4); }\n #sbwkdghhjd .gt_indent_5 { text-indent: calc(5px * 5); }\n #sbwkdghhjd .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #sbwkdghhjd .gt_row_group_first td { border-top-width: 2px; }\n #sbwkdghhjd .gt_row_group_first th { border-top-width: 2px; }\n #sbwkdghhjd .gt_striped { color: #333333; background-color: #F4F4F4; }\n #sbwkdghhjd .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #sbwkdghhjd .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #sbwkdghhjd .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #sbwkdghhjd .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #sbwkdghhjd .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #sbwkdghhjd .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #sbwkdghhjd .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #sbwkdghhjd .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #sbwkdghhjd .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #sbwkdghhjd .gt_left { text-align: left; }\n #sbwkdghhjd .gt_center { text-align: center; }\n #sbwkdghhjd .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #sbwkdghhjd .gt_font_normal { font-weight: normal; }\n #sbwkdghhjd .gt_font_bold { font-weight: bold; }\n #sbwkdghhjd .gt_font_italic { font-style: italic; }\n #sbwkdghhjd .gt_super { font-size: 65%; }\n #sbwkdghhjd .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #sbwkdghhjd .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #sbwkdghhjd .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #sbwkdghhjd .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #sbwkdghhjd .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #sbwkdghhjd .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\">Grid convergence of the population moments</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_x\">x-grid size</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"vp\">value premium (% per year)</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rf\">risk-free rate (% per year)</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_right\">20</td>\n    <td class=\"gt_row gt_right\">4.76</td>\n    <td class=\"gt_row gt_right\">0.10</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">30</td>\n    <td class=\"gt_row gt_right\">5.18</td>\n    <td class=\"gt_row gt_right\">0.98</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">40</td>\n    <td class=\"gt_row gt_right\">4.97</td>\n    <td class=\"gt_row gt_right\">1.48</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">60</td>\n    <td class=\"gt_row gt_right\">3.81</td>\n    <td class=\"gt_row gt_right\">1.78</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">100</td>\n    <td class=\"gt_row gt_right\">3.33</td>\n    <td class=\"gt_row gt_right\">1.81</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\n::: {#a1cdda20 .cell execution_count=5}\n``` {.python .cell-code code-fold=\"true\"}\nfrom plotnine import (ggplot, aes, geom_line, geom_point, labs,\n                      scale_color_manual, scale_linetype_manual,\n                      scale_shape_manual, theme_minimal, theme,\n                      element_blank, element_line, element_text)\n\nconv_long = conv.melt(id_vars=\"n_x\", var_name=\"series\", value_name=\"value\")\nconv_long[\"series\"] = conv_long[\"series\"].map(\n    {\"vp\": \"value premium\", \"rf\": \"risk-free rate\"})\n\np = (\n    ggplot(conv_long, aes(\"n_x\", \"value\", color=\"series\",\n                          linetype=\"series\", shape=\"series\"))\n    + geom_line(size=0.9)\n    + geom_point(size=2)\n    + scale_color_manual(values={\"value premium\": \"#7a1f1f\",\n                                 \"risk-free rate\": \"#1f4e79\"})\n    + scale_linetype_manual(values={\"value premium\": \"solid\",\n                                    \"risk-free rate\": \"dashed\"})\n    + scale_shape_manual(values={\"value premium\": \"o\",\n                                 \"risk-free rate\": \"s\"})\n    + labs(x=\"x-grid size n_x\", y=\"percent per year\")\n    + theme_minimal(base_size=11)\n    + theme(figure_size=(6.5, 3.2), text=element_text(color=\"#2d2926\"),\n            panel_grid_minor=element_blank(),\n            panel_grid_major=element_line(color=\"#e2d6c4\", size=0.4),\n            axis_line=element_line(color=\"#1b1714\", size=0.5),\n            legend_title=element_blank(), legend_position=\"top\")\n)\np.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Grid convergence. The population value premium and risk-free rate as the x-grid refines: the premium computed on the paper's 30-point grid carries the grid's extra x-dispersion; the converged model settles near 3.4% with a higher risk-free rate.](07-quadrature-solution_files/figure-ipynb/cell-6-output-1.png){width=312 height=153}\n:::\n:::\n\n\nThe mechanism survives at every grid size. Dispersion in long-run\ncash-flow risk produces a large positive value premium on every grid\nin the figure. The level the paper prints, a 5.3 percent premium,\nreflects the 30-point discretization it was computed on. The converged\nchain gives about 3.4 percent, with a risk-free rate near 1.8 rather\nthan 1.0. When you replicate a quadrature-solved model, the grid\nspecification is as much a part of the result as the preference\nparameters. [Chapter 10](10-value-premium-resolved.qmd) runs the full\ncomparison with Table VII, including simulated samples, standard\nerrors, and CAPM betas, using `simulate_table_vii`.\n\nOne more behavior is useful to know. On a very coarse grid the\nover-dispersion is so large that the value claim's dividend growth\nexceeds its discount rate. The price is then infinite, and the\nsolver raises an error rather than returning a made-up number:\n\n::: {#1fc832a4 .cell execution_count=6}\n``` {.python .cell-code}\nfrom lrrcs.model.solver import SolverDivergenceError\n\ntry:\n    lrr.ModelSolver(params, n_x=5, n_s=2).solve()\nexcept SolverDivergenceError as err:\n    print(f\"SolverDivergenceError: {err}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSolverDivergenceError: equity claim 'value' z left the plausible range (max |z| = 50.00); the Euler iteration is diverging.\n```\n:::\n:::\n\n\n::: {.firewall}\n**Where each number comes from.** Every figure in this chapter is\nprinted by the cells above at build time: `ModelSolver` (the\nTauchen-Hussey chain and Euler fixed points),\n`compute_asset_pricing_moments` (population moments under the\nstationary distribution), all on `get_table_ii_params()`. Download the\nchapter as a notebook (top of the page) to rerun everything.\n:::\n\n## Takeaways\n\n- Tauchen-Hussey quadrature replaces the continuous state with a\n  Markov chain whose rows are quadrature approximations of the true\n  conditional densities. Pricing then reduces to a contraction, with\n  one matrix-vector product per iteration.\n- Iterate the Euler equation in its contraction form, because the\n  algebraically equivalent undivided form diverges at rate\n  $1 - \\theta$. A solver should raise an error on divergence instead\n  of clamping.\n- The exact solution confirms the log-linear elasticities on a fine\n  grid. It also shows that the grid itself changes the quantity of\n  long-run risk, so check the chain's stationary dispersion against\n  the process you calibrated.\n\n## Exercises\n\n1. Rebuild the chain with `n_s = 8` volatility states (keep\n   `n_x = 30`) and recompute the population value premium. Adding\n   volatility states changes the answer much less than adding $x$\n   states. Explain why, given the prices of risk in\n   [Chapter 6](06-log-linear-solution.qmd).\n2. Compute the chain's implied one-month persistence\n   $E[x_{t+1} \\mid x_t]/x_t$ at a node one standard deviation out, for\n   `n_x = 30` and `n_x = 60`. How does the deviation from\n   $\\rho = 0.98$ line up with the over-dispersion you measured?\n3. The consumption claim converges in thousands of iterations because\n   $\\kappa_1 \\approx 0.999$. Estimate the iteration count needed for a\n   sup-norm tolerance of $10^{-10}$ from the contraction modulus, and\n   check it against a timed run.\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n::: {#4ff0a828 .cell execution_count=7}\n``` {.python .cell-code code-fold=\"true\"}\n# Exercise 1: more volatility states\ns8 = lrr.ModelSolver(params, n_x=30, n_s=8).solve()\nm4 = lrr.compute_asset_pricing_moments(solver)\nm8 = lrr.compute_asset_pricing_moments(s8)\nprint(f\"value premium, n_s = 4: {m4['value_premium']:.2f}\")\nprint(f\"value premium, n_s = 8: {m8['value_premium']:.2f}\")\n\n# Exercise 2: implied one-month persistence one sd out\nfor label, s in ((\"n_x = 30\", solver), (\"n_x = 60\", solver60)):\n    g = s.grid\n    ix = int(np.argmin(np.abs(g.x_nodes - sd_true)))\n    i = ix * g.n_s + is_mid\n    pers = float(g.Pi[i] @ g.x_grid) / g.x_nodes[ix]\n    print(f\"{label}:  E[x'|x]/x one sd out = {pers:.4f}  (rho = {c.rho})\")\n\n# Exercise 3: iterations implied by the contraction modulus\nzb = float(np.dot(solver60.stationary, solver60.z[\"market\"]))\nk1 = np.exp(zb) / (1 + np.exp(zb))\nprint(f\"kappa1 = {k1:.6f}  =>  iterations for 1e-10: \"\n      f\"{np.log(1e-10) / np.log(k1):,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nvalue premium, n_s = 4: 5.18\nvalue premium, n_s = 8: 5.75\nn_x = 30:  E[x'|x]/x one sd out = 0.9921  (rho = 0.98)\nn_x = 60:  E[x'|x]/x one sd out = 0.9817  (rho = 0.98)\nkappa1 = 0.997252  =>  iterations for 1e-10: 8,367\n```\n:::\n:::\n\n\nRefining the volatility dimension moves the premium far less than refining\nx did, because the price of volatility risk is small next to the price of\npersistence risk. The chain's implied persistence at one standard deviation\nsits above rho on the coarse grid (0.992) and close to rho on the fine\ngrid (0.982), the same coarse-grid distortion direction as the\nover-dispersion check. The\niteration estimate from the modulus is the right order of magnitude for a\ntimed run: thousands of cheap iterations.\n\n:::\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: C:\\DBD\\kiku-value-premium-replication\\.venv\\share\\jupyter\\kernels\\python3\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.12.12\n---\n",
    "supporting": [
      "07-quadrature-solution_files\\figure-ipynb"
    ],
    "filters": [],
    "includes": {}
  }
}