project:
  type: website
  output-dir: _site

website:
  title: "geap"
  description: >
    General-equilibrium asset pricing models in Python.
  site-url: https://tlorans.github.io/kiku-value-premium-replication
  repo-url: https://github.com/tlorans/kiku-value-premium-replication
  search: true
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - installation.qmd
      - section: "Long-run risks"
        contents:
          - lrr/index.qmd
          - lrr/user-guide.qmd
          - lrr/examples.qmd
          - lrr/estimation.qmd
          - lrr/math.qmd
          - lrr/api.qmd
      - section: "Power utility"
        contents:
          - ccapm/index.qmd
          - ccapm/user-guide.qmd
          - ccapm/examples.qmd
          - ccapm/math.qmd
          - ccapm/api.qmd
      - section: "Habit"
        contents:
          - habit/index.qmd
          - habit/user-guide.qmd
          - habit/examples.qmd
          - habit/math.qmd
          - habit/api.qmd
      - section: "GMM"
        contents:
          - gmm/index.qmd
          - gmm/user-guide.qmd
          - gmm/examples.qmd
          - gmm/math.qmd
          - gmm/api.qmd
      - section: "Reference"
        contents:
          - reference/glossary.qmd
          - reference/references.qmd

format:
  html:
    theme: [cosmo, theme/kiku.scss]
    grid:
      body-width: 768px
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: false
    html-math-method: mathjax
    fig-format: svg
    fig-dpi: 150
    link-external-newwindow: true

execute:
  freeze: auto
  warning: false

jupyter: python3
