{
  "hash": "f2612b4b00ce6eeae3b791326d0ea227",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"9. The market test\"\naliases: [/time-series.html]\n---\n\nThe model is now fully assembled, and every parameter has already been\nused. The household's preferences were pinned down by consumption\nmoments in [Chapter 5](05-long-run-risks.qmd), and the cash-flow\nloadings were measured from dividends and consumption in\n[Chapter 8](08-calibrating-cash-flows.qmd). No parameter is left that\ncould be adjusted to match a return. The first comparison with\nasset-price data is therefore an out-of-sample test. Hand the\ncalibrated household the calibrated aggregate dividend claim, and ask\nwhat it pays for the claim and what it earns on the claim.\n\nThe aggregate market is where the long-run risks model family was\nbuilt to be tested (Bansal and Yaron 2004), and the test has two\ntargets at once. The market out-earns a Treasury bill by seven to\neight percentage points a year over 1930 to 2003, and it trades at a\nmean price-dividend ratio near thirty, a valuation that swings from 10\nto 88 across the sample. A DCF can hit either target alone, because it\nhas a free number to spend on it. The model here has no free number\nleft, so it is graded on both targets together. A match on the equity\npremium at the wrong valuation is a fail, and so is the reverse.\n\nOne more check comes before prices. The calibrated cash-flow processes\nmust themselves look like the data when simulated. If simulated\nconsumption and dividends do not resemble the sample, a later match on\nreturns could come from wrong cash flows rather than from correct\npricing, and the test ends there.\n\n## The economics of the test\n\nNothing new is derived here. The Euler equation\n$E_t[M_{t+1} R_{i,t+1}] = 1$ with the Epstein-Zin kernel\n([Chapter 4](04-epstein-zin-preferences.qmd)) prices the market claim,\nand the Tauchen-Hussey solver of [Chapter 7](07-quadrature-solution.qmd)\ncomputes the valuation function $z(x_t, \\sigma_t^2)$ on a grid without\nlog-linear approximation. The new part is the object being compared to\nthe data.\n\nThe paper's Table VII reports sample statistics, not population\nmoments. Each entry is the average, across 1,000 artificial samples,\nof a statistic estimated on 74 years of annual data. Each artificial\nsample is simulated at the monthly frequency and aggregated to years,\nso it has exactly the length of the 1930 to 2003 sample. The\nconstruction matters for grading, because a 74-year sample average is\na noisy draw. The model is asked whether the data look like a typical\nsample from it, and the cross-sample standard deviation says how far a\ntypical sample strays. `lrr.simulate_table_vii` reproduces the same\nobject. The page runs 300 samples rather than 1,000 to keep the build\nfast, and the printed means barely move.\n\n## Hands-on: the data targets\n\n::: {#5aae8a05 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\n# Data bootstrap: use the repo's committed CSVs, or fetch them when this\n# notebook runs outside the repository.\nfrom pathlib import Path\nimport urllib.request\n\nDATA = Path(\"../../data\")\nif not DATA.exists():\n    DATA = Path(\"data\")\n    DATA.mkdir(exist_ok=True)\n    base = (\"https://raw.githubusercontent.com/tlorans/\"\n            \"kiku-value-premium-replication/main/data/\")\n    for f in (\"annual_panel.csv\", \"consumption_annual.csv\", \"rf_annual.csv\"):\n        if not (DATA / f).exists():\n            urllib.request.urlretrieve(base + f, DATA / f)\n```\n:::\n\n\n::: {#a612a2f5 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport lrrcs as lrr\n\ndc = pd.read_csv(DATA / \"consumption_annual.csv\").sort_values(\"year\")\npanel = pd.read_csv(DATA / \"annual_panel.csv\")\nrf = pd.read_csv(DATA / \"rf_annual.csv\")\ny = dc[\"dc\"].to_numpy()\nmkt = panel[panel[\"claim\"] == \"Market\"].merge(dc, on=\"year\").sort_values(\"year\")\n```\n:::\n\n\n::: {#0d483ef5 .cell execution_count=3}\n``` {.python .cell-code}\nprint(f\"{len(mkt)} years, 1930-2003\")\nprint(f\"consumption growth : mean {y.mean()*100:.2f}%, \"\n      f\"sd {y.std(ddof=1)*100:.2f}%, AC1 {np.corrcoef(y[:-1], y[1:])[0, 1]:.2f}\")\nprint(f\"market return      : mean {mkt['ret'].mean()*100:.2f}%, \"\n      f\"sd {mkt['ret'].std(ddof=1)*100:.1f}%\")\nprint(f\"market dividends   : mean {mkt['dgrowth'].mean()*100:.1f}%, \"\n      f\"sd {mkt['dgrowth'].std(ddof=1)*100:.1f}%, \"\n      f\"corr(dc, dd) {np.corrcoef(mkt['dc'], mkt['dgrowth'])[0, 1]:.2f}\")\nprint(f\"real T-bill        : mean {rf['rf'].mean()*100:.2f}%\")\nprint(f\"market valuation   : mean P/D {mkt['pd'].mean():.1f}, \"\n      f\"mean log P/D {np.log(mkt['pd']).mean():.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n74 years, 1930-2003\nconsumption growth : mean 1.75%, sd 2.37%, AC1 0.41\nmarket return      : mean 8.52%, sd 20.1%\nmarket dividends   : mean 0.9%, sd 11.0%, corr(dc, dd) 0.60\nreal T-bill        : mean 0.07%\nmarket valuation   : mean P/D 30.9, mean log P/D 3.33\n```\n:::\n:::\n\n\nRead the targets off the print. Consumption growth averages 1.75\npercent with a 2.37 percent standard deviation, so the endowment is\nsmooth. The smoothness is why a market return of 8.5 percent is a\npuzzle. The first autocorrelation of 0.41 says expected growth is not\na constant. The reconstruction's real T-bill averages 0.07 percent,\nwhile the paper's sample, on a slightly different vintage, prints 0.91\npercent. The safe rate is the one series where the reconstruction and\nthe paper's data differ visibly, and I quote both below. The valuation\nalso moves a lot across the sample, as the figure below shows.\n\n::: {#6e266f9c .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\nimport matplotlib\nmatplotlib.use(\"Agg\")\nimport matplotlib.pyplot as plt\n\nlog_pd = np.log(mkt[\"pd\"].to_numpy())\nfig, ax = plt.subplots(figsize=(6.5, 3.2))\nax.plot(mkt[\"year\"], log_pd, color=\"#1b1714\", lw=1.3)\nax.axhline(log_pd.mean(), color=\"#7a1f1f\", lw=1.0, ls=\"--\")\nax.set_xlabel(\"year\")\nax.set_ylabel(\"log(P/D)\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nfig.tight_layout()\nplt.show()\n```\n:::\n\n\n## First check: do the simulated cash flows look like the sample?\n\n`lrr.simulate_cashflow_moments` runs the calibrated endowment forward,\nusing twenty artificial 74-year samples here, and reports average\nannual moments:\n\n::: {#ba853815 .cell execution_count=5}\n``` {.python .cell-code}\nmom = lrr.simulate_cashflow_moments(n_sims=20, years=74, seed=1)\ncons = mom[\"consumption\"]\nmdiv = mom[\"dividends\"][\"market\"]\nprint(f\"consumption      : mean {cons['E[dc]']:.2f}%, \"\n      f\"sd {cons['sigma(dc)']:.2f}%, AC1 {cons['AC1']:.2f}\")\nprint(f\"market dividends : mean {mdiv['E[dd]']:.2f}%, \"\n      f\"sd {mdiv['sigma(dd)']:.1f}%, corr(dc, dd) {mdiv['corr(dc,dd)']:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nconsumption      : mean 1.82%, sd 2.44%, AC1 0.16\nmarket dividends : mean 0.68%, sd 16.4%, corr(dc, dd) 0.57\n```\n:::\n:::\n\n\nSimulated consumption growth averages 1.82 percent with a 2.44 percent\nstandard deviation, against 1.75 and 2.37 in the data, so the endowment\nside passes. Market dividend growth is an order of magnitude more\nvolatile than consumption, in the model as in the data (16.4 percent\nsimulated against the 11.0 percent the data cell printed; the note\nbelow explains the gap). Its correlation with consumption growth is\n0.57 simulated against 0.60 in the data. The autocorrelation print and\nthe dividend volatility print need a comment before anyone reads them\nas failures.\n\n::: {.callout-warning title=\"Two annualization conventions affect this print\"}\nThe cell prints a first autocorrelation of simulated annual consumption\ngrowth of 0.16, while the data show 0.41 and my Table III reports 0.43\nfor the model. The gap comes from the measurement convention, not from\nthe economics. The paper aggregates simulated monthly data the way\nNIPA, the national income and product accounts, builds annual\nconsumption. It sums the twelve monthly levels within the year, then\ntakes log growth of the annual sums. Aggregating levels in that way\nsmooths the annual series, so it raises the autocorrelation and damps\nthe year-over-year volatility (Working 1960). The helper here sums the\ntwelve monthly log growth rates instead, which does neither. The same\nconvention gap accounts for a good part of the dividend volatility\nprint of 16.4 against the data's 11.0. The economy is the same, and\nthe two annualization conventions produce different annual prints. The\npersistence the pricing relies on sits in the monthly state $x_t$\nunder either convention.\n:::\n\nThe check passes. The endowment's mean and volatility and the\ncorrelation between consumption and dividend growth land near the\nsample, and the two visible gaps come from the annualization\nconvention rather than from the calibration. Prices come next.\n\n## Second check: solve, simulate, and grade both targets\n\nSolve the model on the paper's grid of 30 points for $x$ and 4 for\n$\\sigma^2$, which [Chapter 7](07-quadrature-solution.qmd) built. Then\ngenerate 300 samples of 74 years and average the sample statistics,\nexactly as the data column was constructed:\n\n::: {#5c1f6d7f .cell execution_count=6}\n``` {.python .cell-code}\nparams = lrr.get_table_ii_params()\nsolver = lrr.ModelSolver(params, n_x=30, n_s=4).solve()\ntab = lrr.simulate_table_vii(solver, n_samples=300, years=74, seed=0)\n```\n:::\n\n\n::: {#b75c8e61 .cell execution_count=7}\n``` {.python .cell-code}\nprint(f\"risk-free rate    : {tab['mean_rf']:5.2f}%  (SE {tab['mean_rf_se']:.2f})\")\nprint(f\"market return     : {tab['mean_return']['market']:5.2f}%  \"\n      f\"(SE {tab['mean_return_se']['market']:.2f})\")\nprint(f\"equity premium    : {tab['mean_return']['market'] - tab['mean_rf']:5.2f}%\")\nprint(f\"return volatility : {tab['volatility']['market']:5.2f}%\")\nprint(f\"mean log P/D      : {tab['mean_log_pd']['market']:5.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrisk-free rate    :  1.04%  (SE 0.62)\nmarket return     :  8.93%  (SE 3.25)\nequity premium    :  7.89%\nreturn volatility : 19.68%\nmean log P/D      :  3.01\n```\n:::\n:::\n\n\nThe table below places the page's model prints next to the paper's\nown prints. The paper's Table VII uses 1,000 samples and a slightly\ndifferent data vintage, and the SE columns are cross-sample standard\ndeviations.\n\n|  | Model (this page) | Model (paper prints) | Data (reconstruction) | Data (paper prints) |\n|:---|---:|---:|---:|---:|\n| Market return, % | 8.93 (3.25) | 7.53 (2.69) | 8.52 | 8.56 (1.79) |\n| Return volatility, % | 19.68 | not reported | 20.1 | 20.1 |\n| Risk-free rate, % | 1.04 (0.62) | 1.58 | 0.07 | 0.91 (0.39) |\n| Mean log P/D | 3.01 | 3.24 | 3.33 | 3.34 (0.13) |\n\nGrade both targets. The model earns 8.93 percent on the market claim\nagainst 8.52 in the data, which is an equity premium of 7.89 percent\nover its own safe rate, against 7.65 on the paper's data prints (8.56\nminus 0.91). Return volatility is 19.68 percent against 20.1. The\nvaluation comes out at a mean log price-dividend ratio of 3.01 against\n3.33, so the model matches the premium at close to the data's\nvaluation level. The safe rate lands at 1.04 percent, between the\nreconstruction's 0.07 and the paper's model print of 1.58. My own\nprints differ from the cells on the page by less than one cross-sample\nstandard deviation. The run here uses 300 samples, a 30-point grid,\nand one seed, and [Chapter 10](10-value-premium-resolved.qmd)\nquantifies how the grid moves the numbers. The verdict does not move.\nBoth targets land, and no return entered the calibration.\n\nThe contrast with a DCF is the point of the test. A DCF matching the\n8.5 percent return would have assumed a discount rate near 8.5, and a\nDCF matching the valuation would have assumed the growth number. Here,\nconsumption moments fixed the household, and dividends fixed the\nclaim. The Euler equation then produced the premium, the volatility,\nand the valuation together. The market test is passed, but matching\nthe market does not rank firms. The cross-section is the next chapter.\n\n## Takeaways\n\n- Nothing was left to tune. Preferences came from consumption, and\n  cash flows came from dividends, so the market row is out of sample\n  and the model is graded on the premium and the valuation together.\n- Simulated cash flows pass their own check first (consumption mean\n  1.82 vs 1.75, sd 2.44 vs 2.37). The printed AC1 of 0.16 comes from\n  the annualization convention, not from a persistence failure.\n- The solved model prints a market return of 8.93 percent (data: 8.52),\n  volatility of 19.68 (data: 20.1), a safe rate of 1.04, and a mean log\n  P/D of 3.01 (data: 3.33). Both targets land, and the safe rate and\n  the exact valuation are sensitive to the grid.\n- Table VII is a sampling object. It reports means over hundreds of\n  74-year samples, with cross-sample dispersion, which is the right way\n  to compare a model to one 74-year history.\n\n## Exercises\n\n1. Rerun `simulate_table_vii` with `seed=1` and `seed=2`. How much do\n   the market return and the safe rate move? Compare the movement to\n   the printed SE columns.\n2. Set `n_samples=1000` (a few seconds more) and check how the printed\n   means change relative to the 300-sample run.\n3. Call `lrr.simulate_cashflow_moments(n_sims=20, years=74, seed=1)`\n   and read off the value and growth dividend moments it also returns.\n   Which claim's dividends are more volatile, and does volatility alone\n   rank the premia? (Keep your answer; Chapter 10 tests it.)\n\n::: {.firewall}\n**Where each number comes from.** Data numbers are printed by the cells\nabove from `data/consumption_annual.csv`, `data/annual_panel.csv`, and\n`data/rf_annual.csv`. Model numbers are printed by\n`simulate_cashflow_moments` and by `ModelSolver(params, n_x=30, n_s=4)`\nplus `simulate_table_vii(..., n_samples=300, seed=0)` on the Table II\ncalibration. The remaining columns are the paper's Table VII prints.\nDownload the chapter as a notebook (top of the page) to rerun\neverything.\n:::\n\n",
    "supporting": [
      "09-the-market-test_files\\figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}