{
  "hash": "0e62a8a0d3be7272c2be9ca5cb26339c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"9. The market test\"\naliases: [/time-series.html]\n---\n\nThe model is now fully assembled, and — this is the point of everything\nthat came before — fully *spent*. The household's preferences were\npinned down by consumption moments in\n[Chapter 5](05-long-run-risks.qmd). The cash-flow loadings were\nmeasured from dividends and consumption in\n[Chapter 8](08-calibrating-cash-flows.qmd). There is no parameter left\nthat could be bent toward a return. So the first confrontation with\nasset-price data is a genuine out-of-sample test: hand the calibrated\nhousehold the calibrated aggregate dividend claim and ask what it pays\nfor it, and what it earns on it.\n\nThe aggregate market is where this model family was built to be tested\n(Bansal and Yaron 2004), and the bar is set by two facts at once. The\nmarket out-earns a Treasury bill by seven to eight percentage points a\nyear over 1930–2003, and it trades at a mean price–dividend ratio near\nthirty — a valuation that swings from 10 to 88 across the sample. A DCF\ncan hit either fact alone, because it has a free number to spend on it.\nThis model has none left, so it is graded on the pair: *a match on the\nequity premium at the wrong valuation is a fail, and so is the\nreverse.*\n\nOne more gate before prices: the calibrated cash-flow processes must\nthemselves look like the data when simulated. If simulated consumption\nand dividends do not resemble the sample, a later match on returns\nwould be a free parameter in disguise, and the test ends there.\n\n## The economics: what is being graded, and how\n\nNothing new is derived here. The Euler equation\n$E_t[M_{t+1} R_{i,t+1}] = 1$ with the Epstein–Zin kernel\n([Chapter 4](04-epstein-zin-preferences.qmd)) prices the market claim;\nthe Tauchen–Hussey solver of [Chapter 7](07-quadrature-solution.qmd)\ncomputes the valuation function $z(x_t, \\sigma_t^2)$ on a grid without\nlog-linear shortcuts. What is new is the *object* being compared to the\ndata.\n\nThe paper's Table VII is not a population moment. It is the average,\nacross 1,000 artificial samples, of statistics estimated on 74 years of\nannual data — each artificial sample simulated at the monthly frequency\nand aggregated to years, exactly the length of the 1930–2003 sample.\nThis matters for honest grading: a 74-year sample average is a noisy\ndraw, so the model is asked whether the data look like a *typical\nsample* from it, and the cross-sample standard deviation says how far a\ntypical sample strays. `lrr.simulate_table_vii` reproduces that object;\nthis page runs 300 samples rather than 1,000 to keep the build fast\n(the printed means barely move).\n\n## Hands-on: the data targets\n\n::: {#9c105337 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\n# Data bootstrap: use the repo's committed CSVs, or fetch them when this\n# notebook runs outside the repository.\nfrom pathlib import Path\nimport urllib.request\n\nDATA = Path(\"../../data\")\nif not DATA.exists():\n    DATA = Path(\"data\")\n    DATA.mkdir(exist_ok=True)\n    base = (\"https://raw.githubusercontent.com/tlorans/\"\n            \"kiku-value-premium-replication/main/data/\")\n    for f in (\"annual_panel.csv\", \"consumption_annual.csv\", \"rf_annual.csv\"):\n        if not (DATA / f).exists():\n            urllib.request.urlretrieve(base + f, DATA / f)\n```\n:::\n\n\n::: {#c2bf7e2b .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport lrrcs as lrr\n\ndc = pd.read_csv(DATA / \"consumption_annual.csv\").sort_values(\"year\")\npanel = pd.read_csv(DATA / \"annual_panel.csv\")\nrf = pd.read_csv(DATA / \"rf_annual.csv\")\ny = dc[\"dc\"].to_numpy()\nmkt = panel[panel[\"claim\"] == \"Market\"].merge(dc, on=\"year\").sort_values(\"year\")\n```\n:::\n\n\n::: {#f4ad35a9 .cell execution_count=3}\n``` {.python .cell-code}\nprint(f\"{len(mkt)} years, 1930-2003\")\nprint(f\"consumption growth : mean {y.mean()*100:.2f}%, \"\n      f\"sd {y.std(ddof=1)*100:.2f}%, AC1 {np.corrcoef(y[:-1], y[1:])[0, 1]:.2f}\")\nprint(f\"market return      : mean {mkt['ret'].mean()*100:.2f}%, \"\n      f\"sd {mkt['ret'].std(ddof=1)*100:.1f}%\")\nprint(f\"market dividends   : mean {mkt['dgrowth'].mean()*100:.1f}%, \"\n      f\"sd {mkt['dgrowth'].std(ddof=1)*100:.1f}%, \"\n      f\"corr(dc, dd) {np.corrcoef(mkt['dc'], mkt['dgrowth'])[0, 1]:.2f}\")\nprint(f\"real T-bill        : mean {rf['rf'].mean()*100:.2f}%\")\nprint(f\"market valuation   : mean P/D {mkt['pd'].mean():.1f}, \"\n      f\"mean log P/D {np.log(mkt['pd']).mean():.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n74 years, 1930-2003\nconsumption growth : mean 1.75%, sd 2.37%, AC1 0.41\nmarket return      : mean 8.52%, sd 20.1%\nmarket dividends   : mean 0.9%, sd 11.0%, corr(dc, dd) 0.60\nreal T-bill        : mean 0.07%\nmarket valuation   : mean P/D 30.9, mean log P/D 3.33\n```\n:::\n:::\n\n\nRead the targets off the print. The endowment is smooth — consumption\ngrowth averages 1.75 percent with a 2.37 percent standard deviation —\nwhich is exactly why an eight-and-a-half percent market return is a\npuzzle. Its first autocorrelation of 0.41 says expected growth is not a\nconstant. The reconstruction's real T-bill averages 0.07 percent; the\npaper's sample, on a slightly different vintage, prints 0.91 percent —\nthe safe rate is the one series where the reconstruction and the\npaper's data differ visibly, and I quote both below. And the valuation\nis a moving target, not a Gordon constant:\n\n::: {#ed6005b6 .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\nimport matplotlib\nmatplotlib.use(\"Agg\")\nimport matplotlib.pyplot as plt\n\nlog_pd = np.log(mkt[\"pd\"].to_numpy())\nfig, ax = plt.subplots(figsize=(6.5, 3.2))\nax.plot(mkt[\"year\"], log_pd, color=\"#1b1714\", lw=1.3)\nax.axhline(log_pd.mean(), color=\"#7a1f1f\", lw=1.0, ls=\"--\")\nax.set_xlabel(\"year\")\nax.set_ylabel(\"log(P/D)\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nfig.tight_layout()\nplt.show()\n```\n:::\n\n\n## Gate one: do the simulated cash flows look like the sample?\n\n`lrr.simulate_cashflow_moments` runs the calibrated endowment forward —\ntwenty artificial 74-year samples here — and reports average annual\nmoments:\n\n::: {#79549e67 .cell execution_count=5}\n``` {.python .cell-code}\nmom = lrr.simulate_cashflow_moments(n_sims=20, years=74, seed=1)\ncons = mom[\"consumption\"]\nmdiv = mom[\"dividends\"][\"market\"]\nprint(f\"consumption      : mean {cons['E[dc]']:.2f}%, \"\n      f\"sd {cons['sigma(dc)']:.2f}%, AC1 {cons['AC1']:.2f}\")\nprint(f\"market dividends : mean {mdiv['E[dd]']:.2f}%, \"\n      f\"sd {mdiv['sigma(dd)']:.1f}%, corr(dc, dd) {mdiv['corr(dc,dd)']:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nconsumption      : mean 1.82%, sd 2.44%, AC1 0.16\nmarket dividends : mean 0.68%, sd 16.4%, corr(dc, dd) 0.57\n```\n:::\n:::\n\n\nSimulated consumption growth averages 1.82 percent with a 2.44 percent\nstandard deviation, against 1.75 and 2.37 in the data — the endowment\nside passes. Market dividend growth is an order of magnitude more\nvolatile than consumption, in the model as in the data (16.4 percent\nsimulated against the 11.0 percent the data cell printed; the note\nbelow explains the gap), and its\ncorrelation with consumption growth, 0.57 simulated, sits next to the\ndata's 0.60. Two printed numbers need a flag before anyone reads them\nas failures:\n\n::: {.callout-warning title=\"Honesty note: two annualization artifacts in this print\"}\nThe cell prints a first autocorrelation of simulated annual consumption\ngrowth of 0.16, while the data show 0.41 and my Table III reports 0.43\nfor the model. The gap is measurement convention, not economics. The\npaper aggregates simulated monthly data the way NIPA builds annual\nconsumption — sum the twelve monthly *levels* within the year, then\ntake log growth of the annual sums — and that overlapping-levels\naggregation smooths the annual series: it raises its autocorrelation\nand damps its year-over-year volatility (Working 1960). This helper\nsums the twelve monthly *log growth rates*, which does neither; the\nsame convention gap accounts for a good part of the\ndividend-volatility print of 16.4 against the data's 11.0. Same\neconomy, two annualization conventions, different annual prints. The\npersistence the pricing relies on lives in the monthly state $x_t$\neither way.\n:::\n\nThe gate is passed: the endowment's mean and volatility and the\nconsumption–dividend correlation land near the sample, and the two\nvisible gaps are convention, not calibration. Now, and only now,\nprices.\n\n## Gate two: solve, simulate, and grade the pair\n\nSolve the model on the paper's grid (30 points for $x$, 4 for\n$\\sigma^2$ — [Chapter 7](07-quadrature-solution.qmd) built this), then\ngenerate 300 samples of 74 years and average the sample statistics,\nexactly as the data column was constructed:\n\n::: {#1dfc50a1 .cell execution_count=6}\n``` {.python .cell-code}\nparams = lrr.get_table_ii_params()\nsolver = lrr.ModelSolver(params, n_x=30, n_s=4).solve()\ntab = lrr.simulate_table_vii(solver, n_samples=300, years=74, seed=0)\n```\n:::\n\n\n::: {#450745a0 .cell execution_count=7}\n``` {.python .cell-code}\nprint(f\"risk-free rate    : {tab['mean_rf']:5.2f}%  (SE {tab['mean_rf_se']:.2f})\")\nprint(f\"market return     : {tab['mean_return']['market']:5.2f}%  \"\n      f\"(SE {tab['mean_return_se']['market']:.2f})\")\nprint(f\"equity premium    : {tab['mean_return']['market'] - tab['mean_rf']:5.2f}%\")\nprint(f\"return volatility : {tab['volatility']['market']:5.2f}%\")\nprint(f\"mean log P/D      : {tab['mean_log_pd']['market']:5.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrisk-free rate    :  1.04%  (SE 0.62)\nmarket return     :  8.93%  (SE 3.25)\nequity premium    :  7.89%\nreturn volatility : 19.68%\nmean log P/D      :  3.01\n```\n:::\n:::\n\n\nThe scoreboard, with the paper's own prints alongside (its Table VII\nuses 1,000 samples and a slightly different data vintage; the SE\ncolumns are cross-sample standard deviations):\n\n|  | Model (this page) | Model (paper prints) | Data (reconstruction) | Data (paper prints) |\n|:---|---:|---:|---:|---:|\n| Market return, % | 8.93 (3.25) | 7.53 (2.69) | 8.52 | 8.56 (1.79) |\n| Return volatility, % | 19.68 | — | 20.1 | 20.1 |\n| Risk-free rate, % | 1.04 (0.62) | 1.58 | 0.07 | 0.91 (0.39) |\n| Mean log P/D | 3.01 | 3.24 | 3.33 | 3.34 (0.13) |\n\nGrade the pair. The model earns 8.93 percent on the market claim\nagainst 8.52 in the data — an equity premium of 7.89 percent over its\nown safe rate, against 7.65 on the paper's data prints (8.56 minus\n0.91). Return volatility is 19.68 percent against 20.1. And the\nvaluation comes out at a mean log price–dividend ratio of 3.01 against\n3.33 — a claim priced near the data's level, not a premium bought with\nan absurd price. The safe rate lands at 1.04 percent, between the\nreconstruction's 0.07 and the paper's model print of 1.58. My own\nprints differ from this page's cells within one cross-sample standard\ndeviation — the run here uses 300 samples, a 30-point grid, and this\nseed, and [Chapter 10](10-value-premium-resolved.qmd) quantifies how\nthe grid moves these numbers — but the verdict does not move: both\nmembers of the pair land, from cash flows that never saw a return.\n\nThat sentence deserves its weight. A DCF matching the 8.5 percent\nreturn would have *assumed* a discount rate near 8.5; matching the\nvaluation would have assumed the growth number. Here consumption\nmoments fixed the household, dividends fixed the claim, and the Euler\nequation produced the premium, the volatility, and the valuation\ntogether. The market test is passed — but matching the market does not\nrank firms. The cross-section is the next chapter.\n\n## Takeaways\n\n- Nothing was left to tune: preferences came from consumption, cash\n  flows from dividends. The market row is therefore out of sample, and\n  the model is graded on the premium and the valuation *as a pair*.\n- Simulated cash flows pass their own exam first (consumption mean 1.82\n  vs 1.75, sd 2.44 vs 2.37); the printed AC1 of 0.16 is an annualization\n  convention, not a persistence failure.\n- The solved model prints a market return of 8.93 percent (data: 8.52),\n  volatility of 19.68 (data: 20.1), a safe rate of 1.04, and mean log\n  P/D of 3.01 (data: 3.33) — the pair lands, with the safe-rate level\n  and the exact valuation sensitive to the grid.\n- Table VII is a *sampling* object: means over hundreds of 74-year\n  samples, with cross-sample dispersion — the honest way to compare a\n  model to one 74-year history.\n\n## Exercises\n\n1. Rerun `simulate_table_vii` with `seed=1` and `seed=2`. How much do\n   the market return and the safe rate move? Compare the movement to\n   the printed SE columns.\n2. Set `n_samples=1000` (a few seconds more) and check how the printed\n   means change relative to the 300-sample run.\n3. Call `lrr.simulate_cashflow_moments(n_sims=20, years=74, seed=1)`\n   and read off the value and growth dividend moments it also returns.\n   Which claim's dividends are more volatile, and does that alone rank\n   the premia? (Keep your answer; Chapter 10 tests it.)\n\n::: {.firewall}\n**Where each number comes from.** Data numbers are printed by the cells\nabove from `data/consumption_annual.csv`, `data/annual_panel.csv`, and\n`data/rf_annual.csv`; model numbers by `simulate_cashflow_moments` and\nby `ModelSolver(params, n_x=30, n_s=4)` plus\n`simulate_table_vii(..., n_samples=300, seed=0)` on the Table II\ncalibration; the remaining columns are the paper's Table VII prints.\nDownload the chapter as a notebook (top of the page) to rerun\neverything.\n:::\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: C:\\DBD\\kiku-value-premium-replication\\.venv\\share\\jupyter\\kernels\\python3\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.12.12\n---\n",
    "supporting": [
      "09-the-market-test_files\\figure-ipynb"
    ],
    "filters": [],
    "includes": {}
  }
}