{
  "hash": "ff4046c211b6426ce2219be3c7491170",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"1. Two free numbers\"\naliases: [/two-free-numbers.html]\n---\n\nYou already know how to price a stock. You forecast the cash flows and discount them at a rate you choose. Every valuation built this way runs on those two numbers, and the discounted cash flow framework never asks where either one came from. The forecast comes from one source, e.g., analyst estimates, a historical average, or a terminal value convention. The rate comes from another source, e.g., a CAPM regression, a corporate hurdle rate, or a round number that seems reasonable. The two numbers are free, and they come from two unrelated models.\n\nChoosing the two numbers separately is the problem. A firm whose cash flows collapse in bad times should carry a high discount rate, because the rate is compensation for the risk in the cash flows. If you choose the numerator and the denominator separately, you assume away the question the course answers, which is why risky cash flows earn high expected returns, and how high.\n\nThe rest of this chapter makes that cost visible on a napkin, with two plants, one common rate, and Gordon's formula. The names already tell you which plant should grow faster. The arithmetic can follow the names and still produce no value premium. Chapter 2 records the two facts the napkin misses. Chapters 3 to 10 build the model that produces the forecast and the rate from one consumption process.\n\n## Two plants\n\nEach plant pays a dividend of $1 this year. The names are the usual ones.\n\n- Growth is the expensive plant. Analysts write a growth rate of 6 percent.\n- Value is the cheap plant. Analysts write a growth rate of 3 percent.\n- The committee uses one cost of capital, 8 percent, for both.\n\nThe names already contain a growth ranking. Using them as the forecast is how a DCF is usually filled in. Write down which plant is worth more, and what expected return each offers. The attractive answer is that Growth is richer and that both expected returns equal 8 percent. That answer matches the names. It is also what every textbook DCF does.\n\n## The economics\n\nIf dividends grow at a constant rate $g$ and you discount at a constant rate $r$, the price-dividend ratio is\n\n$$\n\\frac{P}{D} = \\frac{1}{r - g}.\n$$ {#eq-gordon}\n\n@eq-gordon says nothing about where either half came from. The implied expected return of the claim equals the $r$ you put in, by construction. The rate contains no term for the risk in the cash flows, so a premium cannot come out of a common rate.\n\nThe choice still moves the price. At $r - g = 4\\%$ the ratio is 25. Cut the discount rate by one percentage point and the ratio rises to 33, so a third of the firm's value depends on a number you made up.\n\n## Hands-on: the napkin DCF\n\nName the two inputs and apply @eq-gordon. The cell prints the table the rest of the chapter uses.\n\n::: {#4a63f81b .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nfrom great_tables import GT\n\nKIKU_GT = dict(table_background_color=\"transparent\", table_font_size=\"0.92rem\",\n               heading_title_font_size=\"1.05rem\", heading_subtitle_font_size=\"0.85rem\",\n               source_notes_font_size=\"0.8rem\", column_labels_font_weight=\"bold\",\n               data_row_padding=\"4px\")\n\n# 1. name the inputs (decimals, not percents)\n#    the names already say who gets the high g\ndividend = 1.0\ng = {\"growth\": 0.06, \"value\": 0.03}\nr = 0.08\n\n# 2. Gordon price-dividend ratio\npd_ratio = {k: 1.0 / (r - gk) for k, gk in g.items()}\n\n# 3. implied expected return equals the rate you put in\nimplied_er = {k: r for k in g}\n\ntable = pd.DataFrame({\n    \"claim\": list(g),\n    \"g\": [100 * g[k] for k in g],\n    \"r\": [100 * r for k in g],\n    \"pd\": [pd_ratio[k] for k in g],\n    \"er\": [100 * implied_er[k] for k in g],\n})\nprint(f\"implied value-growth premium: \"\n      f\"{implied_er['value'] - implied_er['growth']:+.2f}\")\n(\n    GT(table)\n    .tab_header(title=\"Gordon DCF at a common 8 percent rate\")\n    .cols_label(claim=\"\", g=\"g (%)\", r=\"r (%)\", pd=\"P/D\", er=\"implied E[R] (%)\")\n    .fmt_number(columns=[\"g\", \"r\", \"er\"], decimals=1)\n    .fmt_number(columns=\"pd\", decimals=1)\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nimplied value-growth premium: +0.00\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div id=\"rojconismk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#rojconismk table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#rojconismk thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#rojconismk p { margin: 0; padding: 0; }\n #rojconismk .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #rojconismk .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #rojconismk .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #rojconismk .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #rojconismk .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #rojconismk .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #rojconismk .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #rojconismk .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #rojconismk .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #rojconismk .gt_column_spanner_outer:first-child { padding-left: 0; }\n #rojconismk .gt_column_spanner_outer:last-child { padding-right: 0; }\n #rojconismk .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #rojconismk .gt_spanner_row { border-bottom-style: hidden; }\n #rojconismk .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #rojconismk .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #rojconismk .gt_from_md> :first-child { margin-top: 0; }\n #rojconismk .gt_from_md> :last-child { margin-bottom: 0; }\n #rojconismk .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #rojconismk .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #rojconismk .gt_indent_1 { text-indent: 5px; }\n #rojconismk .gt_indent_2 { text-indent: calc(5px * 2); }\n #rojconismk .gt_indent_3 { text-indent: calc(5px * 3); }\n #rojconismk .gt_indent_4 { text-indent: calc(5px * 4); }\n #rojconismk .gt_indent_5 { text-indent: calc(5px * 5); }\n #rojconismk .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #rojconismk .gt_row_group_first td { border-top-width: 2px; }\n #rojconismk .gt_row_group_first th { border-top-width: 2px; }\n #rojconismk .gt_striped { color: #333333; background-color: #F4F4F4; }\n #rojconismk .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #rojconismk .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #rojconismk .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #rojconismk .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #rojconismk .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #rojconismk .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #rojconismk .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #rojconismk .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #rojconismk .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #rojconismk .gt_left { text-align: left; }\n #rojconismk .gt_center { text-align: center; }\n #rojconismk .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #rojconismk .gt_font_normal { font-weight: normal; }\n #rojconismk .gt_font_bold { font-weight: bold; }\n #rojconismk .gt_font_italic { font-style: italic; }\n #rojconismk .gt_super { font-size: 65%; }\n #rojconismk .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #rojconismk .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #rojconismk .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #rojconismk .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #rojconismk .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #rojconismk .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal\">Gordon DCF at a common 8 percent rate</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"claim\"></th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"g\">g (%)</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"r\">r (%)</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pd\">P/D</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"er\">implied E[R] (%)</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">growth</td>\n    <td class=\"gt_row gt_right\">6.0</td>\n    <td class=\"gt_row gt_right\">8.0</td>\n    <td class=\"gt_row gt_right\">50.0</td>\n    <td class=\"gt_row gt_right\">8.0</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">value</td>\n    <td class=\"gt_row gt_right\">3.0</td>\n    <td class=\"gt_row gt_right\">8.0</td>\n    <td class=\"gt_row gt_right\">20.0</td>\n    <td class=\"gt_row gt_right\">8.0</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\nTwo facts fall out of the arithmetic.\n\n1. The implied value-minus-growth premium is exactly zero. Both claims were discounted at the same rate, so both implied expected returns equal that rate.\n2. Growth is richer than value. The high-$g$ claim gets the high price-dividend ratio, 50 against 20. That ranking follows the names we started with.\n\nThe data agree on the ranking and disagree on the premium. In the paper's Table I vintage, value is the cheap portfolio, and it out-earns growth by about six points:\n\n::: {#77a11387 .cell execution_count=2}\n``` {.python .cell-code}\n# Kiku (2006), Table I printed vintage (1930 to 2003)\ntable_i = pd.DataFrame({\n    \"claim\": [\"growth\", \"value\"],\n    \"ret\": [7.81, 13.88],\n    \"log_pd\": [3.61, 3.25],\n})\nprint(f\"data premium: {table_i.loc[1, 'ret'] - table_i.loc[0, 'ret']:.2f} pp/yr\")\n(\n    GT(table_i)\n    .tab_header(title=\"Table I vintage: returns and valuations\")\n    .cols_label(claim=\"\", ret=\"mean return (%)\", log_pd=\"mean log P/D\")\n    .fmt_number(columns=[\"ret\", \"log_pd\"], decimals=2)\n    .tab_source_note(\"Kiku (2006), Table I. Chapter 2 rebuilds the series.\")\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndata premium: 6.07 pp/yr\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div id=\"eynirlwwan\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#eynirlwwan table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#eynirlwwan thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#eynirlwwan p { margin: 0; padding: 0; }\n #eynirlwwan .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #eynirlwwan .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #eynirlwwan .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #eynirlwwan .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #eynirlwwan .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #eynirlwwan .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #eynirlwwan .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #eynirlwwan .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #eynirlwwan .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #eynirlwwan .gt_column_spanner_outer:first-child { padding-left: 0; }\n #eynirlwwan .gt_column_spanner_outer:last-child { padding-right: 0; }\n #eynirlwwan .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #eynirlwwan .gt_spanner_row { border-bottom-style: hidden; }\n #eynirlwwan .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #eynirlwwan .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #eynirlwwan .gt_from_md> :first-child { margin-top: 0; }\n #eynirlwwan .gt_from_md> :last-child { margin-bottom: 0; }\n #eynirlwwan .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #eynirlwwan .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #eynirlwwan .gt_indent_1 { text-indent: 5px; }\n #eynirlwwan .gt_indent_2 { text-indent: calc(5px * 2); }\n #eynirlwwan .gt_indent_3 { text-indent: calc(5px * 3); }\n #eynirlwwan .gt_indent_4 { text-indent: calc(5px * 4); }\n #eynirlwwan .gt_indent_5 { text-indent: calc(5px * 5); }\n #eynirlwwan .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #eynirlwwan .gt_row_group_first td { border-top-width: 2px; }\n #eynirlwwan .gt_row_group_first th { border-top-width: 2px; }\n #eynirlwwan .gt_striped { color: #333333; background-color: #F4F4F4; }\n #eynirlwwan .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #eynirlwwan .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #eynirlwwan .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #eynirlwwan .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #eynirlwwan .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #eynirlwwan .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #eynirlwwan .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #eynirlwwan .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #eynirlwwan .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #eynirlwwan .gt_left { text-align: left; }\n #eynirlwwan .gt_center { text-align: center; }\n #eynirlwwan .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #eynirlwwan .gt_font_normal { font-weight: normal; }\n #eynirlwwan .gt_font_bold { font-weight: bold; }\n #eynirlwwan .gt_font_italic { font-style: italic; }\n #eynirlwwan .gt_super { font-size: 65%; }\n #eynirlwwan .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #eynirlwwan .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #eynirlwwan .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #eynirlwwan .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #eynirlwwan .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #eynirlwwan .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\">Table I vintage: returns and valuations</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"claim\"></th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ret\">mean return (%)</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"log_pd\">mean log P/D</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">growth</td>\n    <td class=\"gt_row gt_right\">7.81</td>\n    <td class=\"gt_row gt_right\">3.61</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">value</td>\n    <td class=\"gt_row gt_right\">13.88</td>\n    <td class=\"gt_row gt_right\">3.25</td>\n  </tr>\n</tbody>\n<tfoot><tr class=\"gt_sourcenotes\"><td class=\"gt_sourcenote\" colspan=\"3\"><span class=\"gt_from_md\">Kiku (2006), Table I. Chapter 2 rebuilds the series.</span></td></tr></tfoot>\n</table>\n\n</div>\n```\n:::\n:::\n\n\nA DCF that copies the names can match the cheap-versus-expensive ranking. It cannot match both facts at once, because the cheap claim also has to earn more, and a common rate has no term for cash-flow risk.\n\n::: {#60c508ae .cell execution_count=3}\n``` {.python .cell-code}\nfrom plotnine import (ggplot, aes, geom_col, geom_text, labs,\n                      scale_fill_manual, ylim, theme_minimal, theme,\n                      element_blank, element_line, element_text)\n\nbars = pd.DataFrame({\n    \"claim\": [\"growth\", \"value\"],\n    \"pd\": [pd_ratio[\"growth\"], pd_ratio[\"value\"]],\n})\np = (\n    ggplot(bars, aes(\"claim\", \"pd\", fill=\"claim\"))\n    + geom_col(width=0.55, show_legend=False)\n    + geom_text(aes(label=\"pd\"), nudge_y=2.5, size=10)\n    + scale_fill_manual(values={\"growth\": \"#1b1714\", \"value\": \"#7a1f1f\"})\n    + ylim(0, 60)\n    + labs(x=\"\", y=\"price-dividend ratio\")\n    + theme_minimal(base_size=11)\n    + theme(figure_size=(5.2, 3.2), text=element_text(color=\"#2d2926\"),\n            panel_grid_minor=element_blank(),\n            panel_grid_major_x=element_blank(),\n            panel_grid_major=element_line(color=\"#e2d6c4\", size=0.4),\n            axis_line=element_line(color=\"#1b1714\", size=0.5),\n            legend_position=\"none\")\n)\np.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The names put the high g on growth, so Gordon prices growth at 50 and value at 20. The ranking matches the labels. Both implied expected returns still equal 8 percent.](01-two-free-numbers_files/figure-html/cell-4-output-1.svg){}\n:::\n:::\n\n\nThe 6 percent on growth is a naming convention, not a measurement. Later chapters measure long-run growth from the cash-flow process instead of from the label. Value's measured growth is then the higher number, because its dividends load more on the persistent piece of consumption. A DCF that uses those measured rates and one common $r$ ranks value expensive, which is the opposite of the data. That calculation is [Chapter 10](10-value-premium-resolved.qmd). Today the names are enough.\n\n### A. Change only the rate\n\nThe common rate was 8 percent. Raise it to 10 percent and recompute. The premium is still zero. Growth is still richer. A common rate cannot manufacture a premium, whatever number you pick.\n\n::: {#a104c196 .cell execution_count=4}\n``` {.python .cell-code}\ndef gordon_table(rate):\n    ratios = {k: 1.0 / (rate - gk) for k, gk in g.items()}\n    premium = rate - rate\n    return ratios, premium\n\nfor rate in (0.08, 0.10):\n    ratios, premium = gordon_table(rate)\n    print(f\"r = {rate:.0%}:  P/D value = {ratios['value']:.1f}   \"\n          f\"P/D growth = {ratios['growth']:.1f}   \"\n          f\"premium = {premium:+.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nr = 8%:  P/D value = 20.0   P/D growth = 50.0   premium = +0.00\nr = 10%:  P/D value = 14.3   P/D growth = 25.0   premium = +0.00\n```\n:::\n:::\n\n\n### B. A rate fitted to the CAPM\n\nThe usual repair gives each claim its own rate from a market-beta regression,\n\n$$\nr_i = r_f + \\beta_i\\,(\\mathbb{E}[R_m] - r_f).\n$$\n\nThe repair works only if the beta that shows up in monthly returns is the cash-flow risk that needs to be priced. It is not. High-frequency returns are dominated by transitory price moves. The extra risk in value is in the low-frequency behavior of its cash flows. Chapter 2 measures the data version of this failure: value's market beta is not large enough to explain six points, and on the paper's vintage the two betas sit near one. Chapter 10 shows the same wrong sign inside the model, once the cash flows exist.\n\nA discount rate built from market betas therefore need not reflect the risk the premium pays for. The failure is structural. Nothing in the DCF lets the riskiness of the cash flows enter the rate.\n\n### C. Shock the forecast, hold the rate\n\nNews arrives that value's cash flows are more tied to bad times than the committee thought. A DCF and a consistent valuation react to the news differently.\n\nIn a DCF the rate is an input, so it does not move. If the committee treats the news as a growth revision, $g$ changes, the Gordon price changes, and the implied expected return is unchanged. The committee has only updated a forecast.\n\nIn a consistent valuation the same news is risk. The required return has to move with the forecast, so the price response includes a new rate as well as a new numerator. The gap between those two answers is the premium.\n\nThe course will derive both numbers from one consumption process. Value and growth will differ by one loading on the persistent part of consumption. That single difference will move the forecast and the rate together. That calculation is in [Chapter 10](10-value-premium-resolved.qmd), after the process and the preference exist. The script that prints it on the Table II economy is `examples/dcf_counterfactual.py`.\n\n::: {.callout-note collapse=\"true\" title=\"Later in the course\"}\nChapter 5 writes the dividend process. Chapter 6 solves for the valuation elasticities. Chapter 8 measures the loadings from cash flows alone. Chapter 10 then hands those cash flows back to a DCF and to the equilibrium solver, and compares the two answers. Nothing in that machinery is required to follow the napkin arithmetic on this page.\n:::\n\n## Where the course goes\n\nThe diagnosis is already in view. The DCF's two numbers are free because they come from two unrelated models, so nothing forces the discount rate to account for the risk in the cash flows. The repair is a single model in which both numbers are outputs of the same measurable process, which is aggregate consumption.\n\nBefore building the model, we establish what it has to explain. [Chapter 2](02-value-premium-in-the-data.qmd) constructs the facts for 1930 to 2003: the six-point value premium, the valuation ranking, and the CAPM's failure in the data.\n\n## Takeaways\n\n- A DCF prices with two free numbers: a forecast $g$ from one model and a rate $r$ from another. Nothing connects the rate to the risk in the cash flows.\n- The names already say who should have the high $g$. Copying that ranking into Gordon makes growth expensive and value cheap, which matches the labels. Both implied expected returns still equal the common $r$, so the premium is exactly zero.\n- Picking the second number from a market-beta regression can get the sign wrong, because the beta in monthly returns is not the cash-flow risk that needs to be priced.\n- If you change the cash-flow story and leave the rate alone, you have updated a forecast. In a consistent valuation the required return moves with the forecast. The gap is the premium.\n\n::: {.callout-note collapse=\"true\" title=\"Recall\"}\n\nAnswer from memory before opening.\n\n1. A DCF gets its growth forecast and its discount rate from two\n   unrelated models. What question does that arrangement assume away?\n2. Give growth the high $g$ and discount both claims at one common rate.\n   What does that force the value premium to be, and what does it do to\n   the valuation ranking?\n3. News arrives that value's cash flows are riskier than we thought.\n   Name what moves in a DCF and what additionally moves in a consistent\n   valuation.\n\n**Answers.**\n\n1. Why risky cash flows earn high expected returns, and how high.\n   Nothing connects the rate to the risk in the cash flows.\n2. Exactly zero, whatever rate you pick. Growth is richer than value,\n   because the names put the high $g$ on growth.\n3. In a DCF only the forecast moves; the price changes and the implied\n   expected return is unchanged. In a consistent valuation the required\n   return moves with the forecast.\n\n:::\n\n## Exercises\n\n1. The common-rate table used $r = 8\\%$. Recompute $P/D$ for both claims\n   at $r = 9\\%$, with growth at 6 percent and value at 3 percent.\n   Confirm that the premium is still zero and that growth is still richer.\n2. Pick any common rate above 6 percent. Show that the implied premium\n   is still zero and that growth is still the expensive claim. The claim\n   is about the common rate, not about 8 percent.\n3. Give value a CAPM beta of 1.4 and growth a beta of 0.9. Take a market\n   premium of 6 percent. Compute the CAPM-implied value-growth spread.\n   State whether that repair used cash-flow risk or return comovement.\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\nRun each check against your own output; the cells use the objects defined\non this page.\n\n::: {#ac3894b2 .cell execution_count=5}\n``` {.python .cell-code code-fold=\"true\"}\n# Exercise 1: Gordon at 9 percent\nr9 = 0.09\npd9 = {k: 1.0 / (r9 - gk) for k, gk in g.items()}\nprint(f\"r = 9%:  P/D value = {pd9['value']:.1f}   \"\n      f\"P/D growth = {pd9['growth']:.1f}   \"\n      f\"premium = {r9 - r9:+.2f}\")\n\n# Exercise 2: any common rate above 6 percent\nfor rate in (0.07, 0.12):\n    ratios = {k: 1.0 / (rate - gk) for k, gk in g.items()}\n    print(f\"r = {rate:.0%}:  P/D value = {ratios['value']:.1f}   \"\n          f\"P/D growth = {ratios['growth']:.1f}\")\n\n# Exercise 3: CAPM napkin\nbeta_g, beta_v, mkt_prem = 0.9, 1.4, 0.06\ncapm_spread = (beta_v - beta_g) * mkt_prem\nprint(f\"CAPM-implied spread: {100 * capm_spread:.1f} pp/yr  \"\n      \"(return comovement, not cash-flow risk)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nr = 9%:  P/D value = 16.7   P/D growth = 33.3   premium = +0.00\nr = 7%:  P/D value = 25.0   P/D growth = 100.0\nr = 12%:  P/D value = 11.1   P/D growth = 16.7\nCAPM-implied spread: 3.0 pp/yr  (return comovement, not cash-flow risk)\n```\n:::\n:::\n\n\nExercise 1 prints 16.7 against 33.3 at a 9 percent rate, with a zero\npremium. Exercise 2 repeats the same ranking at 7 percent and at 12\npercent. Exercise 3 prints a 3-point CAPM spread from the beta gap, which\nis return comovement rather than a reading of the cash-flow process.\n\n:::\n\n::: {.firewall}\n**Where each number comes from.** The Gordon table, the 50-against-20\nranking, the zero premium, and the 8-versus-10 percent check are printed\nby this page's cells from $g_{\\text{growth}} = 0.06$, $g_{\\text{value}} = 0.03$,\nand the stated $r$. The Table I vintage figures (13.88 against 7.81,\nlog P/D 3.25 against 3.61) are the paper's printed numbers;\n[Chapter 2](02-value-premium-in-the-data.qmd) rebuilds the underlying\nseries. The model-side DCF, once the cash flows exist, is\n`examples/dcf_counterfactual.py`. The chapter can be downloaded as a\nnotebook from the link at the top of the page.\n:::\n\n::: {.callout-note title=\"Where to go next\"}\nThe canonical treatment of this chapter's topic is Kiku (2006), the\nmotivation and the CAPM discussion\n([references](../reference/references.qmd)). Stuck, or spot an\nerror? Open an issue at the\n[repository](https://github.com/tlorans/kiku-value-premium-replication/issues), or ask your agent to walk through it with\nyou.\n:::\n\n",
    "supporting": [
      "01-two-free-numbers_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}