{
  "hash": "32e2bab621e9044e6749f681cd22d00e",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"1. Two free numbers\"\naliases: [/two-free-numbers.html]\n---\n\nYou already know how to price a stock. You forecast the cash flows and discount them at a rate you choose. Every valuation built this way runs on those two numbers, and the discounted cash flow framework never asks where either one came from. The forecast comes from one source, e.g., analyst estimates, a historical average, or a terminal value convention. The rate comes from another source, e.g., a CAPM regression, a corporate hurdle rate, or a round number that seems reasonable. The two numbers are free, and they come from two unrelated models.\n\nChoosing the two numbers separately is the problem. A firm whose cash flows collapse in bad times should carry a high discount rate, because the rate is compensation for the risk in the cash flows. If you choose the numerator and the denominator separately, you assume away the question the course answers, which is why risky cash flows earn high expected returns, and how high. The rest of this chapter measures what that costs, on one claim and Gordon's formula. Chapter 2 records the facts the arithmetic misses. Chapters 3 to 10 build the model that produces the forecast and the rate from one consumption process.\n\n## The economics\n\nIf dividends grow at a constant rate $g$ and you discount at a constant rate $r$, the price-dividend ratio is\n\n$$\n\\frac{P}{D} = \\frac{1}{r - g}.\n$$ {#eq-gordon}\n\nNow ask the valuation what the claim is expected to earn. Under @eq-gordon the expected return is the dividend yield plus the growth rate, so\n\n$$\n\\mathbb{E}[R] = \\frac{D}{P} + g = (r - g) + g = r.\n$$ {#eq-identity}\n\n@eq-identity is an identity, not a result. The expected return the valuation reports is the rate you put in, exactly, and the rate contains no term for the risk in the cash flows. The next section runs both formulas and reads the two columns.\n\n## Hands-on: how much the two numbers do\n\nFix the forecast at 3 percent, vary the rate, and compute the price and the implied expected return from the two formulas above.\n\n::: {#567dd900 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nfrom great_tables import GT\n\nKIKU_GT = dict(table_background_color=\"transparent\", table_font_size=\"0.92rem\",\n               heading_title_font_size=\"1.05rem\", heading_subtitle_font_size=\"0.85rem\",\n               source_notes_font_size=\"0.8rem\", column_labels_font_weight=\"bold\",\n               data_row_padding=\"4px\")\n\ng = 0.03            # the forecast, from one model\nRATES = (0.07, 0.08, 0.09, 0.10)\n\n\ndef implied_er(r, g):\n    \"\"\"What the claim is expected to earn: dividend yield plus growth.\"\"\"\n    pd_ratio = 1.0 / (r - g)\n    return 1.0 / pd_ratio + g\n\n\ntable = pd.DataFrame({\n    \"r\": [100 * r for r in RATES],\n    \"pd\": [1.0 / (r - g) for r in RATES],\n    \"er\": [100 * implied_er(r, g) for r in RATES],\n})\n(\n    GT(table)\n    .tab_header(title=\"One claim growing at 3 percent, four discount rates\")\n    .cols_label(r=\"r (%)\", pd=\"P/D\", er=\"implied E[R] (%)\")\n    .fmt_number(columns=[\"r\", \"er\"], decimals=1)\n    .fmt_number(columns=\"pd\", decimals=1)\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div id=\"ovnqvvvjkz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#ovnqvvvjkz table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#ovnqvvvjkz thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#ovnqvvvjkz p { margin: 0; padding: 0; }\n #ovnqvvvjkz .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #ovnqvvvjkz .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #ovnqvvvjkz .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #ovnqvvvjkz .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #ovnqvvvjkz .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #ovnqvvvjkz .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #ovnqvvvjkz .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #ovnqvvvjkz .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #ovnqvvvjkz .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #ovnqvvvjkz .gt_column_spanner_outer:first-child { padding-left: 0; }\n #ovnqvvvjkz .gt_column_spanner_outer:last-child { padding-right: 0; }\n #ovnqvvvjkz .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #ovnqvvvjkz .gt_spanner_row { border-bottom-style: hidden; }\n #ovnqvvvjkz .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #ovnqvvvjkz .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #ovnqvvvjkz .gt_from_md> :first-child { margin-top: 0; }\n #ovnqvvvjkz .gt_from_md> :last-child { margin-bottom: 0; }\n #ovnqvvvjkz .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #ovnqvvvjkz .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #ovnqvvvjkz .gt_indent_1 { text-indent: 5px; }\n #ovnqvvvjkz .gt_indent_2 { text-indent: calc(5px * 2); }\n #ovnqvvvjkz .gt_indent_3 { text-indent: calc(5px * 3); }\n #ovnqvvvjkz .gt_indent_4 { text-indent: calc(5px * 4); }\n #ovnqvvvjkz .gt_indent_5 { text-indent: calc(5px * 5); }\n #ovnqvvvjkz .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #ovnqvvvjkz .gt_row_group_first td { border-top-width: 2px; }\n #ovnqvvvjkz .gt_row_group_first th { border-top-width: 2px; }\n #ovnqvvvjkz .gt_striped { color: #333333; background-color: #F4F4F4; }\n #ovnqvvvjkz .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #ovnqvvvjkz .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #ovnqvvvjkz .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #ovnqvvvjkz .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #ovnqvvvjkz .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #ovnqvvvjkz .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #ovnqvvvjkz .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #ovnqvvvjkz .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #ovnqvvvjkz .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #ovnqvvvjkz .gt_left { text-align: left; }\n #ovnqvvvjkz .gt_center { text-align: center; }\n #ovnqvvvjkz .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #ovnqvvvjkz .gt_font_normal { font-weight: normal; }\n #ovnqvvvjkz .gt_font_bold { font-weight: bold; }\n #ovnqvvvjkz .gt_font_italic { font-style: italic; }\n #ovnqvvvjkz .gt_super { font-size: 65%; }\n #ovnqvvvjkz .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #ovnqvvvjkz .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #ovnqvvvjkz .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #ovnqvvvjkz .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #ovnqvvvjkz .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #ovnqvvvjkz .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\">One claim growing at 3 percent, four discount rates</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"r\">r (%)</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pd\">P/D</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"er\">implied E[R] (%)</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_right\">7.0</td>\n    <td class=\"gt_row gt_right\">25.0</td>\n    <td class=\"gt_row gt_right\">7.0</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">8.0</td>\n    <td class=\"gt_row gt_right\">20.0</td>\n    <td class=\"gt_row gt_right\">8.0</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">9.0</td>\n    <td class=\"gt_row gt_right\">16.7</td>\n    <td class=\"gt_row gt_right\">9.0</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">10.0</td>\n    <td class=\"gt_row gt_right\">14.3</td>\n    <td class=\"gt_row gt_right\">10.0</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\nTwo things fall out of the table.\n\n1. The price is mostly the rate. Moving from 8 percent to 7 percent raises the ratio from 20 to 25, so one percentage point on a number nobody measured is worth a fifth of the firm. Across the four rows the price rises by three quarters.\n2. The last column is a copy of the first. The dividend yield in `implied_er` is $r - g$ by construction, so adding $g$ back returns $r$ on every row. Nothing was computed. The number was retyped.\n\nThe second point is the one to keep. A valuation built this way cannot tell you what a claim should earn, because you told it.\n\n::: {#209429d1 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nfrom plotnine import (ggplot, aes, geom_line, geom_point, labs,\n                      theme_minimal, theme, element_blank, element_line,\n                      element_text)\n\ncurve = pd.DataFrame({\"r\": np.linspace(0.045, 0.12, 200)})\ncurve[\"pd\"] = 1.0 / (curve[\"r\"] - g)\np = (\n    ggplot(curve, aes(\"r\", \"pd\"))\n    + geom_line(color=\"#7a1f1f\", size=0.9)\n    + geom_point(pd.DataFrame({\"r\": [0.08], \"pd\": [1.0 / (0.08 - g)]}),\n                 aes(\"r\", \"pd\"), color=\"#1b1714\", size=2.5)\n    + labs(x=\"discount rate r\", y=\"price-dividend ratio\")\n    + theme_minimal(base_size=11)\n    + theme(figure_size=(5.2, 3.2), text=element_text(color=\"#2d2926\"),\n            panel_grid_minor=element_blank(),\n            panel_grid_major=element_line(color=\"#e2d6c4\", size=0.4),\n            axis_line=element_line(color=\"#1b1714\", size=0.5))\n)\np.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Price-dividend ratio of a claim growing at 3 percent, as a function of the discount rate. The point marks the 8 percent row of the table. The curve is steep across the whole range of plausible rates, so most of what the valuation reports is the rate the committee chose rather than anything measured about the firm.](01-two-free-numbers_files/figure-ipynb/cell-3-output-1.png){width=249 height=153}\n:::\n:::\n\n\n### Any number of claims, one rate\n\nA committee pricing a cross-section writes one forecast per claim and applies its cost of capital to all of them. Put three claims through the same two formulas, at one rate of 8 percent.\n\n::: {#d510ed81 .cell execution_count=3}\n``` {.python .cell-code}\nr = 0.08\nfor g_i, label in ((0.06, \"grows at 6 percent\"),\n                   (0.03, \"grows at 3 percent\"),\n                   (0.00, \"never grows at all\")):\n    print(f\"a claim that {label:20s}  P/D {1.0 / (r - g_i):5.1f}   \"\n          f\"implied E[R] {100 * implied_er(r, g_i):.2f} %\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\na claim that grows at 6 percent    P/D  50.0   implied E[R] 8.00 %\na claim that grows at 3 percent    P/D  20.0   implied E[R] 8.00 %\na claim that never grows at all    P/D  12.5   implied E[R] 8.00 %\n```\n:::\n:::\n\n\nThe prices differ by a factor of four, and every implied expected return is 8.00 percent. A claim that never grows is expected to earn what a claim growing at 6 percent earns. The valuation ranking is whatever the forecasts said, and the implied premium between any two of these claims is exactly zero.\n\nThat is the shape of the problem. The data hold two facts at once: value trades at a lower multiple than growth, and value out-earns it. In the paper's Table I vintage the mean log price-dividend ratios are 3.25 against 3.61 and the mean returns are 13.88 against 7.81 percent, which is a spread of about six points a year. A common rate can match the first fact, because the forecasts set the ranking. It cannot produce the second, because the premium is zero by @eq-identity whatever forecasts you write. Getting a premium requires giving the claims different rates, and a DCF has no rule that produces one.\n\nNor is the ranking safe. Later chapters measure long-run growth from the cash-flow process instead of assuming it, and value's measured growth turns out to be the higher number, because its dividends load more on the persistent piece of consumption. A DCF fed those measured rates at one common $r$ prices value richer than growth, which is the opposite of the data. That calculation is [Chapter 10](10-value-premium-resolved.qmd).\n\n### Where a different rate would come from\n\nThe usual repair gives each claim its own rate from a market-beta regression,\n\n$$\nr_i = r_f + \\beta_i\\,(\\mathbb{E}[R_m] - r_f).\n$$\n\nThe repair works only if the beta that shows up in monthly returns is the cash-flow risk that needs to be priced. It is not. High-frequency returns are dominated by transitory price moves. The extra risk in value is in the low-frequency behavior of its cash flows. Chapter 2 measures the data version of this failure: value's market beta is not large enough to explain six points, and on the paper's vintage the two betas sit near one. Chapter 10 shows the same wrong sign inside the model, once the cash flows exist.\n\nA discount rate built from market betas therefore need not reflect the risk the premium pays for. The failure is structural. Nothing in the DCF lets the riskiness of the cash flows enter the rate.\n\n### A forecast is not a valuation\n\nNews arrives that value's cash flows are more tied to bad times than the committee thought. A DCF and a consistent valuation react to the news differently.\n\nIn a DCF the rate is an input, so it does not move. If the committee treats the news as a growth revision, $g$ changes, the Gordon price changes, and the implied expected return is unchanged at $r$. The committee has only updated a forecast.\n\nIn a consistent valuation the same news is risk. The required return has to move with the forecast, so the price response includes a new rate as well as a new numerator. The gap between those two answers is the premium.\n\nThe course will derive both numbers from one consumption process. Value and growth will differ by one loading on the persistent part of consumption. That single difference will move the forecast and the rate together. That calculation is in [Chapter 10](10-value-premium-resolved.qmd), after the process and the preference exist. The script that prints it on the Table II economy is `examples/dcf_counterfactual.py`.\n\n::: {.callout-note collapse=\"true\" title=\"Later in the course\"}\nChapter 5 writes the dividend process. Chapter 6 solves for the valuation elasticities. Chapter 8 measures the loadings from cash flows alone. Chapter 10 then hands those cash flows back to a DCF and to the equilibrium solver, and compares the two answers. Nothing in that machinery is required to follow the arithmetic on this page.\n:::\n\nThe diagnosis is now in view, and the repair is a single model in which both numbers are outputs of the same measurable process, which is aggregate consumption. Before building it, we establish what it has to explain. [Chapter 2](02-value-premium-in-the-data.qmd) constructs the facts for 1930 to 2003: the six-point value premium, the valuation ranking, and the CAPM's failure in the data.\n\n## Takeaways\n\n- A DCF prices with two free numbers: a forecast $g$ from one model and a rate $r$ from another. Nothing connects the rate to the risk in the cash flows.\n- Under Gordon the implied expected return is the dividend yield plus growth, which returns the $r$ you typed. A valuation built this way cannot tell you what a claim should earn, because you told it.\n- The price is mostly the rate. One percentage point on $r$ moves the price-dividend ratio by about a fifth.\n- At one common rate the implied premium is exactly zero across any cross-section, whatever forecasts you write. A claim that never grows is expected to earn what a claim growing at 6 percent earns.\n- Picking the second number from a market-beta regression can get the sign wrong, because the beta in monthly returns is return comovement rather than the cash-flow risk that needs to be priced.\n- If you change the cash-flow story and leave the rate alone, you have updated a forecast. In a consistent valuation the required return moves with the forecast. The gap is the premium.\n\n::: {.callout-note collapse=\"true\" title=\"Recall\"}\n\nAnswer from memory before opening.\n\n1. Under Gordon, what does the implied expected return of a claim work\n   out to, and why does that make the calculation uninformative?\n2. Price several claims with different growth forecasts at one common\n   rate. What does that force the implied premium between any two of\n   them to be, and what sets the valuation ranking?\n3. News arrives that value's cash flows are riskier than we thought.\n   Name what moves in a DCF and what additionally moves in a consistent\n   valuation.\n\n**Answers.**\n\n1. The dividend yield is $r - g$, so adding $g$ back returns $r$ exactly.\n   The valuation reports the rate you chose, so it cannot tell you what\n   the claim should earn.\n2. Exactly zero, whatever rate and whatever forecasts you pick. The\n   ranking is set by the forecasts alone, because the high-$g$ claim gets\n   the high price-dividend ratio.\n3. In a DCF only the forecast moves; the price changes and the implied\n   expected return is unchanged. In a consistent valuation the required\n   return moves with the forecast.\n\n:::\n\n## Exercises\n\n1. The table prints $P/D = 20$ at $r = 8\\%$ with $g = 3\\%$. Find the rate\n   that would have given $P/D = 33$ instead. Report how far that rate sits\n   from 8 percent and what fraction of the price the gap moved.\n2. Invent a fourth claim with any growth rate below $r$ and check its\n   implied expected return against $r$. Explain in one sentence why the\n   algebra forces the answer you get.\n3. Give value a CAPM beta of 1.4 and growth a beta of 0.9. Take a market\n   premium of 6 percent. Compute the CAPM-implied value-growth spread.\n   State whether that repair used cash-flow risk or return comovement.\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\nRun each check against your own output; the cells use the objects defined\non this page.\n\n::: {#ec2979fb .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\n# Exercise 1: the rate that prices the claim at 33\nr33 = g + 1.0 / 33.0\nprint(f\"P/D = 33 needs r = {100 * r33:.2f}%, \"\n      f\"{100 * (0.08 - r33):.2f} pp below 8%\")\nprint(f\"price change from that gap: {33.0 / 20.0 - 1.0:+.0%}\")\n\n# Exercise 2: a fourth claim, any growth rate below r\ng4 = 0.045\nprint(f\"claim growing at {100 * g4:.1f}%:  P/D {1.0 / (0.08 - g4):.1f}   \"\n      f\"implied E[R] {100 * implied_er(0.08, g4):.2f} %\")\n\n# Exercise 3: CAPM napkin\nbeta_g, beta_v, mkt_prem = 0.9, 1.4, 0.06\ncapm_spread = (beta_v - beta_g) * mkt_prem\nprint(f\"CAPM-implied spread: {100 * capm_spread:.1f} pp/yr  \"\n      \"(return comovement, not cash-flow risk)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nP/D = 33 needs r = 6.03%, 1.97 pp below 8%\nprice change from that gap: +65%\nclaim growing at 4.5%:  P/D 28.6   implied E[R] 8.00 %\nCAPM-implied spread: 3.0 pp/yr  (return comovement, not cash-flow risk)\n```\n:::\n:::\n\n\nExercise 1 needs a rate of 6.03 percent, just under two points below the\none the committee wrote, and that gap raises the price by 65 percent.\nExercise 2 returns 8.00 percent again, because the dividend yield the\nformula computes is $r - g$ and adding $g$ back cancels it. Exercise 3\nprints a 3-point CAPM spread from the beta gap, which is return\ncomovement rather than a reading of the cash-flow process.\n\n:::\n\n::: {.firewall}\n**Where each number comes from.** The four-rate table, the implied expected\nreturn column, the three-claim check, the curve, and the exercise answers\nare printed by this page's cells from $g = 0.03$, the four rates, and\n@eq-gordon with @eq-identity. The Table I vintage figures quoted in the\ntext (13.88 against 7.81, log P/D 3.25 against 3.61) are the paper's\nprinted numbers; [Chapter 2](02-value-premium-in-the-data.qmd) rebuilds\nthe underlying series from the shipped data. The model-side DCF, once the\ncash flows exist, is `examples/dcf_counterfactual.py`. The chapter can be\ndownloaded as a notebook from the link at the top of the page.\n:::\n\n::: {.callout-note title=\"Where to go next\"}\nThe canonical treatment of this chapter's topic is Kiku (2006), the\nmotivation and the CAPM discussion\n([references](../reference/references.qmd)). Stuck, or spot an\nerror? Open an issue at the\n[repository](https://github.com/tlorans/kiku-value-premium-replication/issues), or ask your agent to walk through it with\nyou.\n:::\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: C:\\DBD\\kiku-value-premium-replication\\.venv\\share\\jupyter\\kernels\\python3\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.12.12\n---\n",
    "supporting": [
      "01-two-free-numbers_files\\figure-ipynb"
    ],
    "filters": [],
    "includes": {}
  }
}