{
  "hash": "c98f81389e56b3d41685476381f77f1a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"11. Price your own claim\"\naliases:\n  - /price-your-own-claim.html\n---\n\nEverything in this course so far priced my three claims: the market and\nthe two legs of the book-to-market sort. This chapter shows you how to\nprice a claim of your own. Bring a dividend process, e.g., a portfolio's\ndividends, a firm's distributable earnings, or any cash-flow stream you\ncan put a growth series to. The model then reports how the claim's\nvaluation responds to long-run growth news and what that exposure costs.\n\nThe contrast to remember is [Chapter 1](01-two-free-numbers.qmd). A DCF\nprices a claim from two free numbers, a growth rate and a discount rate,\nand nothing inside the method disciplines either one. Here the claim\nbrings exactly one number of its own, the loading of its cash flows on\nthe persistent component of consumption growth, and you measure that\nnumber from cash flows alone. Nobody chooses the discount rate. The\nhousehold of [Chapter 4](04-epstein-zin-preferences.qmd) sets it, and\nthe same household prices every claim. Returns never enter the\nestimation, so the premium that comes out is a prediction, not a fit.\n\nThe point of building a general equilibrium model instead of a\nspreadsheet is exactly the arrangement above. One economy, with one set\nof preferences, prices every claim in the cross-section by where its\ncash flows fall when news arrives about the next decade of growth.\n\n## The steps\n\nPricing a claim takes four steps, and none of them uses a return.\n\n1. **Obtain your claim's cash-flow growth series.** Use annual log\n   dividend growth for a portfolio, or growth in distributable earnings\n   for a firm. The growth series is the only input the claim\n   contributes.\n2. **Measure its long-run leverage.** Project the growth series on the\n   two-year moving average of lagged consumption growth, as in equation\n   (19) of the paper and\n   [Chapter 8](08-calibrating-cash-flows.qmd). The slope is the loading\n   $\\tilde\\phi$.\n3. **Hand the loading to `price_from_loadings`.** The function embeds\n   the claim in the Table II economy and solves the log-linear model of\n   [Chapter 6](06-log-linear-solution.qmd) for that one claim.\n4. **Read off the outputs.** `A1` is the elasticity of the\n   price-dividend ratio to $x_t$, so it measures how the claim's\n   valuation responds to growth news. `premium_lr` is the annualized\n   compensation for bearing that news. `gordon_return` is what a Gordon\n   growth formula would report at the same anchor, using the growth\n   channel alone with no adjustment for risk.\n\n## Two synthetic firms\n\nBefore using real data, run the cleanest possible experiment. Price two\nfirms that are identical in every respect except the loading. Nothing is\nestimated and nothing is re-tuned between the rows, so the loading is\nthe only difference.\n\n::: {#ed9c866e .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\n# Data bootstrap: use the repo's committed CSVs, or fetch them when this\n# notebook runs outside the repository.\nfrom pathlib import Path\nimport urllib.request\n\nDATA = Path(\"../../data\")\nif not DATA.exists():\n    DATA = Path(\"data\")\n    DATA.mkdir(exist_ok=True)\n    base = (\"https://raw.githubusercontent.com/tlorans/\"\n            \"kiku-value-premium-replication/main/data/\")\n    for f in (\"annual_panel.csv\", \"consumption_annual.csv\", \"rf_annual.csv\"):\n        if not (DATA / f).exists():\n            urllib.request.urlretrieve(base + f, DATA / f)\n```\n:::\n\n\n::: {#6f61486d .cell execution_count=2}\n``` {.python .cell-code}\nimport lrrcs as lrr\n\nprint(f\"{'firm':6s} {'phi':>5s} {'A1':>7s} {'premium_lr %':>13s} \"\n      f\"{'g_eff %':>9s} {'gordon %':>9s}\")\nfor name, phi in ((\"A\", 0.5), (\"B\", 1.5)):\n    out = lrr.price_from_loadings(phi)\n    print(f\"{name:6s} {out['loading']:5.1f} {out['A1']:7.1f} \"\n          f\"{out['premium_lr'] * 100:13.2f} {out['g_eff'] * 100:9.2f} \"\n          f\"{out['gordon_return'] * 100:9.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfirm     phi      A1  premium_lr %   g_eff %  gordon %\nA        0.5    -3.0         -0.03      3.20      6.89\nB        1.5    15.2          0.14      3.32      7.01\n```\n:::\n:::\n\n\nFirm B's dividends track the persistent component of consumption, so\nits price-dividend ratio moves with long-run news ($A_1 = 15.2$) and its\ncompensation for that news is positive, 0.14 percent a year. Firm A\nbehaves in the opposite way. Its loading of 0.5 sits below the\nhousehold's $1/\\psi = 0.67$ threshold from\n[Chapter 6](06-log-linear-solution.qmd), so its valuation moves against\nthe news ($A_1 = -3.0$) and its compensation for $x_t$ news is slightly\nnegative, $-0.03$ percent. A hedge pays less, because the household\nwill accept a lower return on a claim that does well precisely when\nlong-run news is bad.\n\nNow look at the Gordon column. The Gordon formula uses only expected\ngrowth, so it puts the two firms 0.12 points apart (7.01 versus 6.89\npercent), which is almost entirely the mechanical difference in\neffective growth. The economics of the two rows is in the risk the\nGordon formula omits. `premium_lr` is the part of that risk that comes\nfrom $x_t$ news, and short-run and volatility news add more.\n\n## Pricing the value and growth legs\n\nNow run the same steps on the 1930 to 2003 data that\n[Chapter 8](08-calibrating-cash-flows.qmd) built. Step 1 uses the\npanel's dividend growth series, and step 2 runs the equation (19)\nregression. The value leg is missing dividend growth in two depression\nyears, so the regression masks non-finite pairs, which is the same\narithmetic Chapter 8 ran:\n\n::: {#5aee1cba .cell execution_count=3}\n``` {.python .cell-code}\nimport numpy as np\nimport polars as pl\n\ndc = pl.read_csv(DATA / \"consumption_annual.csv\").sort(\"year\")[\"dc\"].to_numpy()\npanel = pl.read_csv(DATA / \"annual_panel.csv\")\n\ndef dividend_growth(claim):\n    return (\n        panel.filter(pl.col(\"claim\") == claim)\n        .sort(\"year\")[\"dgrowth\"]\n        .to_numpy()\n    )\n\nma = lrr.expected_growth_proxy(dc, window=2)\n\ndef leverage(dd):\n    mask = np.isfinite(ma) & np.isfinite(dd)\n    x = ma[mask] - ma[mask].mean()\n    e = dd[mask] - dd[mask].mean()\n    return float(np.dot(x, e) / np.dot(x, x))\n\nphi = {c: leverage(dividend_growth(c)) for c in (\"Value\", \"Growth\", \"Market\")}\nfor claim, slope in phi.items():\n    print(f\"{claim:8s} phi_tilde = {slope:6.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nValue    phi_tilde =  12.13\nGrowth   phi_tilde =  -0.27\nMarket   phi_tilde =   0.72\n```\n:::\n:::\n\n\nValue's dividends load heavily on the slow component of consumption,\nand growth's barely respond. On the reconstruction here, growth's slope\nis even slightly negative, and the market sits in between. For complete\nseries, `calibrate_from_data` wraps the same regression in one call and\nalso estimates the short-run parameters ($\\mu$, $\\phi_\\sigma$,\n$\\alpha$):\n\n::: {#d0489475 .cell execution_count=4}\n``` {.python .cell-code}\ndiv = lrr.calibrate_from_data(\n    dc,\n    frequency=\"annual\",\n    window=2,\n    short=dividend_growth(\"Growth\"),\n    market=dividend_growth(\"Market\"),\n)\nlrr.print_calibration_summary(div)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPortfolio          μ (m)     φ (long-run)   φ_σ      α\n-------------------------------------------------------\nshort               0.00027    -0.267       7.05    0.33\nmarket              0.00076     0.722       5.33    0.57\n```\n:::\n:::\n\n\nThe slopes match the regression run by hand above. The signature has no\nargument for returns, by design, so the Euler equation stays a test\nrather than becoming a target.\n\nFor steps 3 and 4, hand each measured loading to the pricer and compare\nthe rows. Everything except the loading is held at the package defaults,\nso the only difference between the rows is the measured cash-flow\nexposure:\n\n::: {#7d39312a .cell execution_count=5}\n``` {.python .cell-code}\nprint(f\"{'leg':8s} {'phi':>6s} {'A1':>7s} {'premium_lr %':>13s}\")\nfor leg, claim in ((\"value\", \"Value\"), (\"growth\", \"Growth\")):\n    out = lrr.price_from_loadings(phi[claim])\n    print(f\"{leg:8s} {out['loading']:6.2f} {out['A1']:7.1f} \"\n          f\"{out['premium_lr'] * 100:13.2f}\")\n\nspread = (lrr.price_from_loadings(phi[\"Value\"])[\"premium_lr\"]\n          - lrr.price_from_loadings(phi[\"Growth\"])[\"premium_lr\"])\nprint(f\"\\nValue-growth spread from long-run risks: {spread * 100:.2f} points\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nleg         phi      A1  premium_lr %\nvalue     12.13   208.9          1.89\ngrowth    -0.27   -17.0         -0.15\n\nValue-growth spread from long-run risks: 2.04 points\n```\n:::\n:::\n\n\nThe premium ordering follows the measured leverage. The leg whose\ndividends load on long-run news earns compensation for that risk, and\nthe leg whose dividends do not earns a small hedge discount. The spread\nis positive even though no return ever entered the calculation.\n\nDo not read the level literally. About seventy annual observations are\nenough to establish a ranking but not a third decimal. Table VI of the\npaper reports annual slopes of $-0.38$ for growth and $2.16$ for value,\nwhere the reconstruction here prints $-0.27$ and $12.13$, so the ranking\nsurvives and the point estimates do not. Moreover, an annual slope is\nnot the monthly loading the full solution uses (Table II sets\n$\\phi_V = 6.2$, $\\phi_G = 2.6$), and at $\\tilde\\phi = 12.13$ the\nlog-linear elasticity of 208.9 comes from applying the formula well\npast the region it was linearized for. The demonstration establishes\nthe ordering and the mechanism, not the decimals.\n\n## When your claim is not a traded portfolio\n\nThe steps do not require a traded portfolio, because any cash-flow\ngrowth series can be projected on the consumption moving average.\nOutside traded portfolios, though, measurement error and the\nlinearization anchor deserve extra caution.\n\nFirst, the loading is measured with error. The regression above had\nseven decades of exchange-listed dividends, and the point estimate\nstill moved from 2.16 to 12.13 across reconstructions. A firm's\ndistributable earnings over 15 or 20 years measure $\\tilde\\phi$ with\neven more error, so the honest output is a range. Price the claim at\nthe low and high ends of a confidence band for the loading rather than\nat the point estimate.\n\nSecond, the anchor is an assumption. `price_from_loadings` linearizes\naround a mean log price-dividend ratio of 3.30. The function does not\nknow your claim's actual valuation, and the `mean_log_pd` field in its\noutput repeats the assumption rather than predicting anything. If your\nclaim's valuation ratio sits far from $e^{3.30} \\approx 27$, the\nelasticities and the Gordon comparison drift with it. The sign and\nordering logic survives. A loading above $1/\\psi$ means the valuation\nrises on good long-run news and the claim owes a premium for it, and a\nloading below $1/\\psi$ means the opposite.\n\n## Takeaways\n\n- Any claim is priced from one measured number, the loading of its\n  cash-flow growth on the two-year moving average of lagged consumption\n  growth. Returns never enter, so the premium is a prediction.\n- `price_from_loadings` returns the valuation response to growth news\n  ($A_1$), the compensation that response commands (`premium_lr`), and\n  the Gordon return, which is the number a DCF would report from growth\n  alone, with no adjustment for the risk that separates the claims.\n- On the 1930 to 2003 data the measured leverages are 12.13 (value),\n  $-0.27$ (growth) and 0.72 (market), and the implied premium ordering\n  follows the leverage ordering.\n- Short samples measure the loading with substantial error, and the\n  anchor P/D of 3.30 is a linearization point, not a fitted level.\n  Trust the ordering and the sign, and do not trust the third decimal.\n\n## Exercises\n\n1. Price a claim with $\\phi = 0.67$ (the household's $1/\\psi$). Confirm\n   `A1` and `premium_lr` are approximately zero, and explain why the\n   threshold is $1/\\psi$ rather than 0.\n2. Re-run the equation (19) regression with `window=3` in\n   `expected_growth_proxy`. Does the value-growth leverage ranking\n   survive? Compare with exercise 1 of\n   [Chapter 8](08-calibrating-cash-flows.qmd).\n3. Drop 1930 to 1945 from the sample and re-estimate $\\tilde\\phi$ for\n   both legs, then re-price them. How much does the spread move, and\n   what does the answer tell you about which years supply the\n   identifying variation?\n4. Take any dividend-paying portfolio you can build a yearly\n   dividend-growth series for, run the four steps, and write down the\n   loading, the premium, and the Gordon return. Which of the three\n   numbers would a DCF valuation of the same portfolio have shown you?\n\n::: {.firewall}\n**Where each number comes from.** The two-firm table and the leg\npricing are `lrr.price_from_loadings` on the Table II economy; the\nmeasured leverages are the equation (19) regression on\n`data/consumption_annual.csv` and `data/annual_panel.csv` via\n`lrr.expected_growth_proxy`, with `lrr.calibrate_from_data` wrapping\nthe same arithmetic. Every cell runs when the site is built. Download\nthe chapter as a notebook (Other Formats, top of the page) to rerun it\non your own series.\n:::\n\n",
    "supporting": [
      "11-price-your-own-claim_files\\figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}