{
  "hash": "8d200f1b3d7698343fcb6cb7e8a6f6f6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"11. Price your own claim\"\naliases:\n  - /price-your-own-claim.html\n---\n\nEverything in this course so far priced my three claims: the market and\nthe two legs of the book-to-market sort. This chapter hands you the\nmachinery. Bring a dividend process — a portfolio's dividends, a firm's\ndistributable earnings, any cash-flow stream you can put a growth series\nto — and the model returns how its valuation responds to long-run growth\nnews and what that exposure costs.\n\nThe contrast to remember is [Chapter 1](01-two-free-numbers.qmd). A DCF\nprices a claim from two free numbers, a growth rate and a discount rate,\nand nothing inside the method disciplines either one. Here the claim\nbrings exactly one number of its own — the loading of its cash flows on\nthe persistent component of consumption growth — and that number is\n*measured*, from cash flows alone. The discount rate is not chosen at\nall: the household of [Chapter 4](04-epstein-zin-preferences.qmd) sets\nit, the same household for every claim. Returns never enter the\nestimation, so the premium that comes out is a prediction, not a fit.\n\nThat is the whole point of building a general equilibrium model instead\nof a spreadsheet. One economy, one set of preferences, and the entire\ncross-section of claims priced by where their cash flows fall when news\narrives about the next decade of growth.\n\n## The recipe\n\nFour steps, none of which involves a return:\n\n1. **Obtain your claim's cash-flow growth series.** Annual log dividend\n   growth for a portfolio, or growth in distributable earnings for a\n   firm. This is the only input the claim contributes.\n2. **Measure its long-run leverage.** Project the growth series on the\n   two-year moving average of lagged consumption growth — equation (19)\n   of the paper, exactly as in\n   [Chapter 8](08-calibrating-cash-flows.qmd). The slope is the loading\n   $\\tilde\\phi$.\n3. **Hand the loading to `price_from_loadings`.** The function embeds\n   the claim in the Table II economy and solves the log-linear model of\n   [Chapter 6](06-log-linear-solution.qmd) for that one claim.\n4. **Read off the outputs.** `A1` is the price–dividend elasticity to\n   $x_t$ — how the claim's valuation responds to growth news.\n   `premium_lr` is the annualized compensation for bearing that news.\n   `gordon_return` is what a Gordon growth formula would report at the\n   same anchor: the growth channel alone, blind to risk.\n\n## Two synthetic firms\n\nBefore real data, the cleanest possible experiment: two firms identical\nin every respect except the loading. Nothing is estimated and nothing is\nre-tuned between the rows — the loading is the only difference.\n\n::: {#f0cf4e8f .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\n# Data bootstrap: use the repo's committed CSVs, or fetch them when this\n# notebook runs outside the repository.\nfrom pathlib import Path\nimport urllib.request\n\nDATA = Path(\"../../data\")\nif not DATA.exists():\n    DATA = Path(\"data\")\n    DATA.mkdir(exist_ok=True)\n    base = (\"https://raw.githubusercontent.com/tlorans/\"\n            \"kiku-value-premium-replication/main/data/\")\n    for f in (\"annual_panel.csv\", \"consumption_annual.csv\", \"rf_annual.csv\"):\n        if not (DATA / f).exists():\n            urllib.request.urlretrieve(base + f, DATA / f)\n```\n:::\n\n\n::: {#ac39f4d8 .cell execution_count=2}\n``` {.python .cell-code}\nimport lrrcs as lrr\n\nprint(f\"{'firm':6s} {'phi':>5s} {'A1':>7s} {'premium_lr %':>13s} \"\n      f\"{'g_eff %':>9s} {'gordon %':>9s}\")\nfor name, phi in ((\"A\", 0.5), (\"B\", 1.5)):\n    out = lrr.price_from_loadings(phi)\n    print(f\"{name:6s} {out['loading']:5.1f} {out['A1']:7.1f} \"\n          f\"{out['premium_lr'] * 100:13.2f} {out['g_eff'] * 100:9.2f} \"\n          f\"{out['gordon_return'] * 100:9.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfirm     phi      A1  premium_lr %   g_eff %  gordon %\nA        0.5    -3.0         -0.03      3.20      6.89\nB        1.5    15.2          0.14      3.32      7.01\n```\n:::\n:::\n\n\nFirm B's dividends track the persistent component of consumption: its\nprice–dividend ratio moves with long-run news ($A_1 = 15.2$) and its\ncompensation for that news is positive, 0.14 percent a year. Firm A\nleans the other way. Its loading of 0.5 sits below the household's\n$1/\\psi = 0.67$ threshold from [Chapter 6](06-log-linear-solution.qmd),\nso its valuation moves *against* the news ($A_1 = -3.0$) and its\n$x_t$-news compensation is slightly negative, $-0.03$ percent. A hedge\npays less — the household will accept a lower return on a claim that\ndoes well precisely when long-run news is bad.\n\nNow look at the Gordon column. It sees only expected growth, so it puts\nthe two firms 0.12 points apart (7.01 versus 6.89 percent) — almost\nentirely the mechanical difference in effective growth. The economics\nof the two rows is in the risk the Gordon formula cannot see, and\n`premium_lr` is the $x_t$-news piece of it; short-run and volatility\nnews add more.\n\n## A real claim: the value and growth legs\n\nThe same recipe on the 1930–2003 data that\n[Chapter 8](08-calibrating-cash-flows.qmd) built. Step 1 is the panel's\ndividend growth series; step 2 is the equation (19) regression. The\nvalue leg is missing dividend growth in two depression years, so the\nregression masks non-finite pairs — the same arithmetic Chapter 8 ran:\n\n::: {#db3204ff .cell execution_count=3}\n``` {.python .cell-code}\nimport numpy as np\nimport polars as pl\n\ndc = pl.read_csv(DATA / \"consumption_annual.csv\").sort(\"year\")[\"dc\"].to_numpy()\npanel = pl.read_csv(DATA / \"annual_panel.csv\")\n\ndef dividend_growth(claim):\n    return (\n        panel.filter(pl.col(\"claim\") == claim)\n        .sort(\"year\")[\"dgrowth\"]\n        .to_numpy()\n    )\n\nma = lrr.expected_growth_proxy(dc, window=2)\n\ndef leverage(dd):\n    mask = np.isfinite(ma) & np.isfinite(dd)\n    x = ma[mask] - ma[mask].mean()\n    e = dd[mask] - dd[mask].mean()\n    return float(np.dot(x, e) / np.dot(x, x))\n\nphi = {c: leverage(dividend_growth(c)) for c in (\"Value\", \"Growth\", \"Market\")}\nfor claim, slope in phi.items():\n    print(f\"{claim:8s} phi_tilde = {slope:6.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nValue    phi_tilde =  12.13\nGrowth   phi_tilde =  -0.27\nMarket   phi_tilde =   0.72\n```\n:::\n:::\n\n\nValue's dividends load hard on the slow component of consumption;\ngrowth's barely respond — on this reconstruction the slope even leans\nnegative — and the market sits in between. For complete series,\n`calibrate_from_data` wraps the same regression in one call and also\nestimates the short-run parameters ($\\mu$, $\\phi_\\sigma$, $\\alpha$):\n\n::: {#c2204dc4 .cell execution_count=4}\n``` {.python .cell-code}\ndiv = lrr.calibrate_from_data(\n    dc,\n    frequency=\"annual\",\n    window=2,\n    short=dividend_growth(\"Growth\"),\n    market=dividend_growth(\"Market\"),\n)\nlrr.print_calibration_summary(div)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPortfolio          μ (m)     φ (long-run)   φ_σ      α\n-------------------------------------------------------\nshort               0.00027    -0.267       7.05    0.33\nmarket              0.00076     0.722       5.33    0.57\n```\n:::\n:::\n\n\nThe slopes match the hand-run regression. Note what the signature does\n*not* contain: there is no argument for returns, by design, so the Euler\nequation stays a test rather than becoming a target.\n\nSteps 3 and 4 — hand each measured loading to the pricer and compare.\nEverything except the loading is held at the package defaults, so the\nonly difference between the rows is the measured cash-flow exposure:\n\n::: {#9c044b79 .cell execution_count=5}\n``` {.python .cell-code}\nprint(f\"{'leg':8s} {'phi':>6s} {'A1':>7s} {'premium_lr %':>13s}\")\nfor leg, claim in ((\"value\", \"Value\"), (\"growth\", \"Growth\")):\n    out = lrr.price_from_loadings(phi[claim])\n    print(f\"{leg:8s} {out['loading']:6.2f} {out['A1']:7.1f} \"\n          f\"{out['premium_lr'] * 100:13.2f}\")\n\nspread = (lrr.price_from_loadings(phi[\"Value\"])[\"premium_lr\"]\n          - lrr.price_from_loadings(phi[\"Growth\"])[\"premium_lr\"])\nprint(f\"\\nValue-growth spread from long-run risks: {spread * 100:.2f} points\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nleg         phi      A1  premium_lr %\nvalue     12.13   208.9          1.89\ngrowth    -0.27   -17.0         -0.15\n\nValue-growth spread from long-run risks: 2.04 points\n```\n:::\n:::\n\n\nThe premium ordering follows the measured leverage: the leg whose\ndividends load on long-run news earns compensation for it, the leg\nwhose dividends do not earns a small hedge discount, and the spread is\npositive without any return ever entering the calculation.\n\nDo not read the *level* literally. Seventy-odd annual observations buy\na ranking, not a third decimal: Table VI of the paper reports annual\nslopes of $-0.38$ for growth and $2.16$ for value, where this\nreconstruction prints $-0.27$ and $12.13$ — the ranking survives, the\npoint estimates do not. And an annual slope is not the monthly loading\nthe full solution uses (Table II sets $\\phi_V = 6.2$, $\\phi_G = 2.6$);\nat $\\tilde\\phi = 12.13$ the log-linear elasticity of 208.9 is the\nformula strained well past the region it was linearized for. The\ndemonstration is the ordering and the mechanism, not the decimals.\n\n## When your claim is not a traded portfolio\n\nThe recipe does not require a CRSP ticker — any cash-flow growth series\ncan be projected on the consumption moving average. But two warnings\nmatter more, not less, outside traded portfolios.\n\nFirst, measurement error. The regression above had seven decades of\nexchange-listed dividends and still moved a point estimate from 2.16\nto 12.13 across reconstructions. A firm's\ndistributable earnings over 15 or 20 years measure $\\tilde\\phi$ with\nerror large enough that the honest output is a range: price the claim\nat the low and high ends of a confidence band for the loading, not at\nthe point estimate.\n\nSecond, the anchor. `price_from_loadings` linearizes around a mean log\nprice–dividend ratio of 3.30. That is a linearization point, not a\nfitted level — the function does not know your claim's actual\nvaluation, and `mean_log_pd` in its output is the assumption echoed\nback, not a prediction. If your claim's valuation ratio sits far from\n$e^{3.30} \\approx 27$, the elasticities and the Gordon comparison drift\nwith it. What survives is the sign and ordering logic: loading above\n$1/\\psi$ means the valuation rises on good long-run news and the claim\nowes a premium for it; loading below means the opposite.\n\n## Takeaways\n\n- Any claim is priced from one measured number: the loading of its\n  cash-flow growth on the two-year moving average of lagged consumption\n  growth. Returns never enter, so the premium is a prediction.\n- `price_from_loadings` returns the valuation response to growth news\n  ($A_1$), the compensation that response commands (`premium_lr`), and\n  the Gordon return — the growth-only number a DCF would report, blind\n  to the risk that separates the claims.\n- On the 1930–2003 data the measured leverages are 12.13 (value),\n  $-0.27$ (growth) and 0.72 (market), and the implied premium ordering\n  follows the leverage ordering.\n- Short samples measure the loading with substantial error, and the\n  anchor P/D of 3.30 is a linearization point, not a fitted level.\n  Trust the ordering and the sign; do not trust the third decimal.\n\n## Exercises\n\n1. Price a claim with $\\phi = 0.67$ (the household's $1/\\psi$). Confirm\n   `A1` and `premium_lr` are approximately zero, and explain why the\n   threshold is $1/\\psi$ rather than 0.\n2. Re-run the equation (19) regression with `window=3` in\n   `expected_growth_proxy`. Does the value–growth leverage ranking\n   survive? Compare with exercise 1 of\n   [Chapter 8](08-calibrating-cash-flows.qmd).\n3. Drop 1930–1945 from the sample and re-estimate $\\tilde\\phi$ for both\n   legs, then re-price them. How much does the spread move? What does\n   that tell you about where the identifying variation lives?\n4. Take any dividend-paying portfolio you can build a yearly\n   dividend-growth series for, run the four steps, and write down the\n   loading, the premium, and the Gordon return. Which of the three\n   numbers would a DCF valuation of the same portfolio have shown you?\n\n::: {.firewall}\n**Where each number comes from.** The two-firm table and the leg\npricing are `lrr.price_from_loadings` on the Table II economy; the\nmeasured leverages are the equation (19) regression on\n`data/consumption_annual.csv` and `data/annual_panel.csv` via\n`lrr.expected_growth_proxy`, with `lrr.calibrate_from_data` wrapping\nthe same arithmetic. Every cell runs when the site is built; download\nthe chapter as a notebook (Other Formats, top of the page) to rerun it\non your own series.\n:::\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: C:\\DBD\\kiku-value-premium-replication\\.venv\\share\\jupyter\\kernels\\python3\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.12.12\n---\n",
    "supporting": [
      "11-price-your-own-claim_files\\figure-ipynb"
    ],
    "filters": [],
    "includes": {}
  }
}