{
  "hash": "12efb3d571968baf18adf9eb15935497",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"6. The log-linear solution\"\n---\n\nEvery asset pricing model faces the same practical obstacle. The Euler\nequation prices a claim by an expectation over everything that can happen\nnext period, and next period contains another expectation, and so on\nforever. In this chapter I solve the recursion the first of two ways,\nwith a log-linear approximation that turns the model into three\nnumbers per claim. You can read the economics of the value premium\noff those three numbers before running any simulation.\n\nThe result is a formula for how a claim's valuation responds to news\nabout long-run growth, and a formula for the premium that comes with\nthe response. Both formulas are in closed form, so you can see which\nparameter does what.\n\n## The valuation ratio is linear in the state\n\nThe state of the economy is the pair $(x_t, \\sigma_t^2)$, which is\nexpected consumption growth and its volatility.\n[Chapter 5](05-long-run-risks.qmd) defines both processes.\nThe claim's log price-dividend ratio turns out to be almost exactly a\nlinear function of the state,\n\n$$\nz_t \\equiv \\log(P_t/D_t) = A_0 + A_1\\, x_t + A_2\\, \\sigma_t^2 .\n$$ {#eq-affine}\n\n$A_1$ is the most important of the three coefficients. It measures how\nmuch the price moves when investors learn that long-run growth is one\npoint higher. For a claim whose dividends load on expected growth with\nleverage $\\phi$ (paper eq. 11),\n\n$$\nA_1 = \\frac{\\phi - \\tfrac{1}{\\psi}}{1 - \\kappa_1 \\rho},\n$$ {#eq-a1}\n\nwhere $\\psi$ is the elasticity of intertemporal substitution,\n$\\rho$ the persistence of expected growth, and\n$\\kappa_1 = e^{\\bar z}/(1 + e^{\\bar z})$ a linearization constant that\nis close to one for realistic valuation levels.\n\nThe numerator and the denominator of @eq-a1 each do one job:\n\n- The numerator says prices rise on good growth news only when\n  cash-flow leverage exceeds the investor's willingness to substitute\n  ($\\phi > 1/\\psi$). With $\\psi = 1.5$, any claim with leverage above\n  $0.67$ appreciates on good long-run news.\n- The denominator magnifies the numerator. With $\\rho = 0.98$ monthly and\n  $\\kappa_1 \\approx 0.96$ at annual valuation levels, $1 - \\kappa_1\\rho$\n  is a small number, so a modest difference in cash-flow leverage\n  becomes a large difference in price sensitivity.\n\n::: {.callout-note collapse=\"true\" title=\"Derivation: where @eq-a1 comes from\"}\nStart from the Campbell-Shiller approximation of the log return on the\nclaim, $r_{t+1} = \\kappa_0 + \\kappa_1 z_{t+1} - z_t + \\Delta d_{t+1}$,\nand the log Euler equation $E_t[\\exp(m_{t+1} + r_{t+1})] = 1$ with the\nEpstein-Zin kernel of [Chapter 4](04-epstein-zin-preferences.qmd). Guess the affine form\n@eq-affine, substitute both into the Euler equation, and use the\nlog-normal moment $E[e^X] = e^{E[X] + \\frac{1}{2}\\mathrm{Var}[X]}$.\nThe Euler equation must hold state by state, so the coefficients on\n$x_t$ and on $\\sigma_t^2$ must each vanish. The $x_t$ coefficient reads\n$-\\tfrac{1}{\\psi} + \\phi + A_1(\\kappa_1 \\rho - 1) = 0$, which is\n@eq-a1. Collecting the $\\sigma_t^2$ terms the same way gives $A_2$\n(paper eq. 12), the response of valuations to volatility news. With\n$\\gamma > 1$ and $\\psi > 1$ the coefficient is negative, so higher\nuncertainty lowers prices.\n:::\n\n## The market price of each shock\n\nSubstituting the solved wealth-portfolio ratio back into the pricing\nkernel expresses its surprises in terms of the three shocks of the\neconomy (paper eqs. 13 and 14):\n\n$$\nm_{t+1} - E_t[m_{t+1}]\n  = -\\Lambda_\\eta \\sigma_t \\eta_{t+1}\n    - \\Lambda_\\epsilon \\sigma_t \\epsilon_{t+1}\n    - \\Lambda_w \\sigma_w w_{t+1},\n$$\n\nwith market prices of risk\n\n$$\n\\Lambda_\\eta = \\gamma, \\qquad\n\\Lambda_\\epsilon = \\Big(\\gamma - \\tfrac{1}{\\psi}\\Big)\n  \\frac{\\kappa_{c,1}\\varphi_x}{1 - \\kappa_{c,1}\\rho}, \\qquad\n\\Lambda_w \\;\\text{(volatility news)} .\n$$\n\nShort-run consumption news $\\eta$ carries the price $\\gamma$.\nThe long-run news price $\\Lambda_\\epsilon$ drives the model's results.\nIt contains the same $1/(1 - \\kappa \\rho)$ factor as $A_1$, and it is\nzero under power utility ($\\gamma = 1/\\psi$), so persistence risk is\npriced only because Epstein-Zin preferences care about when\nuncertainty resolves. The premium on any claim is then loadings\ntimes prices (paper eq. 16), and the value-growth spread is, to first\norder, the spread in long-run loadings times $\\Lambda_\\epsilon$\n(paper eq. 18).\n\n## Hands-on: solving the equilibrium\n\n`solve_analytical` computes every object above from the Table II\ncalibration. No returns enter anywhere. The inputs are preferences and\ncash-flow dynamics only.\n\n::: {#d811e341 .cell execution_count=1}\n``` {.python .cell-code}\nimport lrrcs as lrr\n\nparams = lrr.get_table_ii_params()\nsol = lrr.solve_analytical(params)\nlrr.print_long_short_premium(sol)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nApproximate annualized long-run risk premia:\n  growth  :   0.39%\n  value   :   0.80%\n  market  :   0.34%\nValue-growth spread from long-run risks: 0.40%\nA1 (PD elasticity to x): growth=43.1, value=88.9\nPrice of long-run risk Lambda_eps = 5.95\n```\n:::\n:::\n\n\nRead the output against @eq-a1. Growth's leverage is $\\phi_G = 2.6$ and\nvalue's is $\\phi_V = 6.2$, a ratio of 2.4. The price elasticities\ncome out at 43.1 and 88.9, and the annualized long-run risk\ncompensation doubles from growth to value. The small denominator in\n@eq-a1 turns the modest leverage gap into the larger elasticity gap.\n\nCompute the linearization constant once by hand,\nbecause a wrong $\\kappa_1$ corrupts every downstream number without\nany error message. An earlier draft of the site printed 56.3 for the\nmarket's $A_1$, and the arithmetic below shows why the correct value\nis 37.5:\n\n::: {#f448491c .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\n\nz_bar = 3.24                      # mean log P/D of the market claim (annual)\nkappa1 = np.exp(z_bar) / (1 + np.exp(z_bar))\nphi_m, psi, rho = 2.8, 1.5, 0.98\nA1_market = (phi_m - 1 / psi) / (1 - kappa1 * rho)\nprint(f\"kappa1 = {kappa1:.3f}, A1(market) = {A1_market:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nkappa1 = 0.962, A1(market) = 37.5\n```\n:::\n:::\n\n\nFinally, I plot the premium as a function of leverage, which\nsummarizes the mechanism. Each point in the figure solves the model\nfor a claim that differs only in $\\phi$:\n\n::: {#e4535395 .cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\"}\nimport matplotlib\nmatplotlib.use(\"Agg\")\nimport matplotlib.pyplot as plt\n\nphis = np.linspace(0.5, 7.5, 40)\nprem = [lrr.price_from_loadings(float(p))[\"premium_lr\"] * 100 for p in phis]\n\nfig, ax = plt.subplots(figsize=(6.5, 3.4))\nax.plot(phis, prem, color=\"#7a1f1f\", lw=1.6)\nfor name, phi in ((\"growth\", 2.6), (\"market\", 2.8), (\"value\", 6.2)):\n    y = lrr.price_from_loadings(phi)[\"premium_lr\"] * 100\n    ax.scatter([phi], [y], color=\"#1b1714\", zorder=3, s=18)\n    ax.annotate(name, (phi, y), textcoords=\"offset points\",\n                xytext=(6, -2), fontsize=9)\nax.set_xlabel(\"long-run leverage φ\")\nax.set_ylabel(\"long-run premium (% per year)\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nfig.tight_layout()\nplt.show()\n```\n:::\n\n\n::: {.firewall}\n**Where each number comes from.** Every figure in this chapter is\nprinted by the code cells above, which run when the site is built:\n`solve_analytical` and `price_from_loadings` on the Table II\ncalibration (`get_table_ii_params`). Download the chapter as a notebook\n(top of the page) to rerun everything.\n:::\n\n## Takeaways\n\n- A claim's valuation is close to a linear function of the two state\n  variables, and the slope on expected growth is\n  $A_1 = (\\phi - 1/\\psi)/(1 - \\kappa_1\\rho)$.\n- Persistence magnifies leverage. With $\\rho$ near one, small leverage\n  differences become large differences in price sensitivity and a large\n  spread in premia.\n- Long-run risk is priced only under Epstein-Zin preferences, because\n  the price $\\Lambda_\\epsilon$ vanishes under power utility.\n\n## Exercises\n\n1. Recompute $A_1$ for the value claim with $\\rho = 0.95$ instead of\n   $0.98$ (keep everything else at Table II). How much of the elasticity\n   survives? Relate your answer to the robustness grid in\n   [Chapter 10](10-value-premium-resolved.qmd).\n2. Set $\\psi = 0.9$ and recompute the market's $A_1$. What happens to\n   the sign, and what does the sign change mean economically for how\n   prices react to good news about growth?\n3. Use `price_from_loadings` to find the leverage $\\phi$ at which a\n   claim's long-run premium equals zero. Why is it $1/\\psi$ and not 0?\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: C:\\DBD\\kiku-value-premium-replication\\.venv\\share\\jupyter\\kernels\\python3\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.12.12\n---\n",
    "supporting": [
      "06-log-linear-solution_files\\figure-ipynb"
    ],
    "filters": [],
    "includes": {}
  }
}