{
  "hash": "93c18089918e9abb404c06794e61ff83",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"4. Epstein-Zin preferences\"\n---\n\n[Chapter 3](03-pricing-by-euler-equation.qmd) ended with a kernel that\nmoves only with consumption in the current year, and three failures\nthat follow from the single fact. Before changing anything, the design\nflaw needs a precise name. Power utility makes one parameter do two\njobs. The curvature $\\gamma$ sets how much the investor would pay to\navoid a gamble over consumption, which is an attitude about states.\nThe same curvature also sets how strongly she rearranges consumption\nover time when interest rates move, which is an attitude about dates.\nThe two attitudes are different, one about risk and the other about\nsmoothing over time, and there is no economic reason a person's answer\nto the first should be the reciprocal of her answer to the second.\n\nThe coupling is quantitatively fatal. An investor risk-averse enough\nto generate premia, with a large $\\gamma$, is forced to have a tiny\nelasticity of intertemporal substitution of $1/\\gamma$. An investor\nwith a tiny elasticity dislikes a growing consumption path so much\nthat the model prints an absurd risk-free rate, which was the second\nfailure in Chapter 3. Moreover, persistent good news about growth\nwould raise interest rates so much that valuations fall on good news.\nThe interest-rate response becomes a central problem once the endowment\nof [Chapter 5](05-long-run-risks.qmd) contains persistent news.\n\nEpstein and Zin (1989) remove the coupling with a recursive\nformulation in which risk aversion and the elasticity of intertemporal\nsubstitution are two free parameters. The cost of the separation is\nthat marginal utility stops being a function of consumption alone. It\ncomes to depend on the return to total wealth, which is the market's\nforward-looking assessment of the entire future consumption stream.\nThe course relies on the wealth-return dependence throughout. With\npower utility, only consumption growth next year enters the kernel,\nwhile with Epstein-Zin preferences, news about the future is priced\ntoday.\n\n## The recursion\n\nLifetime utility is defined recursively:\n\n$$\nV_t = \\left[(1-\\delta)\\, C_t^{\\frac{1-\\gamma}{\\theta}}\n      + \\delta \\left(E_t\\!\\left[V_{t+1}^{\\,1-\\gamma}\\right]\\right)^{\\frac{1}{\\theta}}\n      \\right]^{\\frac{\\theta}{1-\\gamma}},\n\\qquad\n\\theta = \\frac{1-\\gamma}{1-\\tfrac{1}{\\psi}} .\n$$ {#eq-ez}\n\nToday's utility aggregates current consumption with a *certainty\nequivalent* of tomorrow's utility. The two attitudes now enter in two\ndifferent places. Risk aversion $\\gamma$ sits inside the certainty\nequivalent, $(E_t[V_{t+1}^{1-\\gamma}])^{1/(1-\\gamma)}$, and governs how\nthe investor collapses a distribution over tomorrow's states into one\nnumber. The elasticity of intertemporal substitution $\\psi$ sits in the\nouter aggregator and governs the willingness to trade consumption today\nagainst the certainty equivalent, a choice across dates made after all\nthe risk has already been collapsed. The composite parameter $\\theta$\nmeasures how far apart the two attitudes are. When $\\gamma = 1/\\psi$\nthe recursion reduces to ordinary power utility and $\\theta = 1$. Any\nother configuration is something power utility cannot represent.\n\n## The kernel\n\nSolving the investor's problem under @eq-ez gives the log\nintertemporal marginal rate of substitution (paper eq. 5):\n\n$$\nm_{t+1} = \\theta \\log \\delta\n          - \\frac{\\theta}{\\psi}\\, \\Delta c_{t+1}\n          + (\\theta - 1)\\, r_{c,t+1},\n$$ {#eq-kernel}\n\nwhere $\\Delta c_{t+1}$ is log consumption growth and $r_{c,t+1}$ is the\nlog return on the *consumption claim*, the portfolio that pays\naggregate consumption as its dividend, meaning total wealth.\n\n::: {.callout-note collapse=\"true\" title=\"Derivation: the IMRS from the recursion\"}\nHomogeneity drives the derivation. The aggregator @eq-ez is linearly\nhomogeneous in $(C_t, V_{t+1})$, so along the optimal plan utility is\nproportional to wealth, $V_t = \\lambda_t W_t$, with a scale $\\lambda_t$\nthat depends on the investment opportunity set. The budget constraint\nis $W_{t+1} = (W_t - C_t) R_{c,t+1}$, with $R_{c,t+1}$ the return on\nthe portfolio holding all wealth, which in equilibrium is the claim to\naggregate consumption.\n\nThe marginal rate of substitution between consumption at $t$ and in a\nstate at $t+1$ is\n$M_{t+1} = \\delta\\,\n\\big(\\tfrac{C_{t+1}}{C_t}\\big)^{-\\frac{1}{\\psi}\\theta}\\,\n\\big(\\tfrac{V_{t+1}^{1-\\gamma}}{E_t[V_{t+1}^{1-\\gamma}]}\\big)^{1-\\frac{1}{\\theta}}$.\nThe expression is the power-utility term times an adjustment that\nrewards states where continuation utility is high. Continuation\nutility is not observable, but homogeneity lets it be substituted out.\nCombining $V_t = \\lambda_t W_t$ with the budget constraint and the\nfirst-order condition for consumption expresses the\ncontinuation-utility ratio through consumption growth and the wealth\nreturn. After the substitution,\n\n$$\nM_{t+1} = \\delta^{\\theta}\n\\left(\\frac{C_{t+1}}{C_t}\\right)^{-\\frac{\\theta}{\\psi}}\nR_{c,t+1}^{\\,\\theta-1},\n$$\n\nwhose log is @eq-kernel. Epstein and Zin (1989) give the full argument.\nThe step to remember is that $R_{c,t+1}$ enters as the observable\nstand-in for continuation utility.\n:::\n\nRead @eq-kernel term by term. The middle term is the familiar\nconsumption-growth penalty. The last term is new. Marginal utility now\nloads on the return to total wealth, and $r_{c,t+1}$ is a\nforward-looking price. It jumps when expectations about future\nconsumption move, long before consumption itself does. Power utility\nswitches the channel off exactly. Setting $\\gamma = 1/\\psi$ forces\n$\\theta = 1$, so the exponent $\\theta - 1$ vanishes. The kernel\n@eq-kernel then reduces to $\\log\\delta - \\gamma\\,\\Delta c_{t+1}$, which\nis Chapter 3's kernel, and the reduced kernel ignores any news that has\nnot yet reached realized consumption. With $\\theta \\ne 1$, a revision\nin expected future growth moves $r_{c,t+1}$ and therefore moves\nmarginal utility today. News about the future has become a priced state\nvariable, and the mechanism is all the course needs.\n[Chapter 6](06-log-linear-solution.qmd) computes the price the news\ncommands.\n\n## Timing of resolution: why $\\gamma > 1/\\psi$\n\nThe sign of the wealth-return exposure has a behavioral reading.\nEpstein-Zin preferences are sensitive to when uncertainty resolves.\nWhen $\\gamma > 1/\\psi$, meaning risk aversion is above the reciprocal\nof the substitution elasticity and hence $\\theta < 1$, the investor\nprefers early resolution of uncertainty. She would pay to learn the\npath of future consumption sooner, even though the path itself would\nnot change. Such an investor treats bad news about consumption in the\ndistant future as a loss now, and demands compensation for holding\nclaims that deliver their bad news bundled with bad long-run prospects.\nA power-utility investor ($\\gamma = 1/\\psi$) is exactly indifferent to\ntiming, which is another way of saying long-run news carries a zero\nrisk price for her.\n\nThe preference for early resolution is why the paper pairs $\\gamma = 10$\nwith $\\psi = 1.5$ in the calibration of [Chapter 5](05-long-run-risks.qmd).\nThe gap between $\\gamma$ and $1/\\psi \\approx 0.67$ makes persistent\nconsumption risk expensive. Setting $\\psi > 1$ also keeps the\ninterest-rate channel from overwhelming the cash-flow channel. When\nexpected growth rises, an investor with a high elasticity does not need\na large rate rise to accept the steeper consumption path, so valuations\ncan rise on good long-run news rather than fall.\n\n## Hands-on: $\\theta$ for the Table II preferences\n\nThe package carries the paper's preference block. Read it and compute\n$\\theta$:\n\n::: {#cc45410a .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport lrrcs as lrr\nfrom great_tables import GT\n\nKIKU_GT = dict(table_background_color=\"transparent\", table_font_size=\"0.92rem\",\n               heading_title_font_size=\"1.05rem\", heading_subtitle_font_size=\"0.85rem\",\n               source_notes_font_size=\"0.8rem\", column_labels_font_weight=\"bold\",\n               data_row_padding=\"4px\")\n\nprefs = lrr.get_table_ii_params().prefs\npref_df = pd.DataFrame({\n    \"parameter\": [\"delta\", \"gamma\", \"psi\", \"theta\"],\n    \"value\": [f\"{prefs.delta}\", f\"{prefs.gamma:g}\", f\"{prefs.psi}\",\n              f\"{prefs.theta:.0f}\"],\n    \"meaning\": [\"time preference\", \"risk aversion\",\n                \"elasticity of intertemporal substitution\",\n                \"derived, (1 - gamma) / (1 - 1/psi)\"],\n})\n(\n    GT(pref_df)\n    .tab_header(title=\"The Table II preference parameters\")\n    .cols_label(parameter=\"parameter\", value=\"value\", meaning=\"meaning\")\n    .tab_source_note(\"Read from lrr.get_table_ii_params().prefs at build time.\")\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div id=\"bbjgyyepdi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#bbjgyyepdi table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#bbjgyyepdi thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#bbjgyyepdi p { margin: 0; padding: 0; }\n #bbjgyyepdi .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #bbjgyyepdi .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #bbjgyyepdi .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #bbjgyyepdi .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #bbjgyyepdi .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #bbjgyyepdi .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #bbjgyyepdi .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #bbjgyyepdi .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #bbjgyyepdi .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #bbjgyyepdi .gt_column_spanner_outer:first-child { padding-left: 0; }\n #bbjgyyepdi .gt_column_spanner_outer:last-child { padding-right: 0; }\n #bbjgyyepdi .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #bbjgyyepdi .gt_spanner_row { border-bottom-style: hidden; }\n #bbjgyyepdi .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #bbjgyyepdi .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #bbjgyyepdi .gt_from_md> :first-child { margin-top: 0; }\n #bbjgyyepdi .gt_from_md> :last-child { margin-bottom: 0; }\n #bbjgyyepdi .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #bbjgyyepdi .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #bbjgyyepdi .gt_indent_1 { text-indent: 5px; }\n #bbjgyyepdi .gt_indent_2 { text-indent: calc(5px * 2); }\n #bbjgyyepdi .gt_indent_3 { text-indent: calc(5px * 3); }\n #bbjgyyepdi .gt_indent_4 { text-indent: calc(5px * 4); }\n #bbjgyyepdi .gt_indent_5 { text-indent: calc(5px * 5); }\n #bbjgyyepdi .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #bbjgyyepdi .gt_row_group_first td { border-top-width: 2px; }\n #bbjgyyepdi .gt_row_group_first th { border-top-width: 2px; }\n #bbjgyyepdi .gt_striped { color: #333333; background-color: #F4F4F4; }\n #bbjgyyepdi .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #bbjgyyepdi .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #bbjgyyepdi .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #bbjgyyepdi .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #bbjgyyepdi .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #bbjgyyepdi .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #bbjgyyepdi .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #bbjgyyepdi .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #bbjgyyepdi .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #bbjgyyepdi .gt_left { text-align: left; }\n #bbjgyyepdi .gt_center { text-align: center; }\n #bbjgyyepdi .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #bbjgyyepdi .gt_font_normal { font-weight: normal; }\n #bbjgyyepdi .gt_font_bold { font-weight: bold; }\n #bbjgyyepdi .gt_font_italic { font-style: italic; }\n #bbjgyyepdi .gt_super { font-size: 65%; }\n #bbjgyyepdi .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #bbjgyyepdi .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #bbjgyyepdi .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #bbjgyyepdi .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #bbjgyyepdi .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #bbjgyyepdi .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\">The Table II preference parameters</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"value\">value</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"meaning\">meaning</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">delta</td>\n    <td class=\"gt_row gt_right\">0.999</td>\n    <td class=\"gt_row gt_left\">time preference</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">gamma</td>\n    <td class=\"gt_row gt_right\">10</td>\n    <td class=\"gt_row gt_left\">risk aversion</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">psi</td>\n    <td class=\"gt_row gt_right\">1.5</td>\n    <td class=\"gt_row gt_left\">elasticity of intertemporal substitution</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">theta</td>\n    <td class=\"gt_row gt_right\">-27</td>\n    <td class=\"gt_row gt_left\">derived, (1 - gamma) / (1 - 1/psi)</td>\n  </tr>\n</tbody>\n<tfoot><tr class=\"gt_sourcenotes\"><td class=\"gt_sourcenote\" colspan=\"3\"><span class=\"gt_from_md\">Read from lrr.get_table_ii_params().prefs at build time.</span></td></tr></tfoot>\n</table>\n\n</div>\n```\n:::\n:::\n\n\nThe table gives $\\theta = -27$, which is a long way from the\npower-utility value of 1. The kernel's exposures follow directly from\n@eq-kernel:\n\n::: {#a481da64 .cell execution_count=2}\n``` {.python .cell-code}\ntheta, psi = prefs.theta, prefs.psi\nprint(\"m = theta*log(delta) - (theta/psi)*dc + (theta-1)*r_c\")\n\npower = lrr.PreferencesParams(gamma=10.0, psi=0.1)\nsdf_df = pd.DataFrame({\n    \"preferences\": [\"Table II\", \"power utility (gamma = 1/psi = 10)\"],\n    \"theta\": [f\"{theta:.0f}\", f\"{power.theta:.0f}\"],\n    \"on_dc\": [f\"{-theta / psi:+.0f}\", f\"{-power.theta / power.psi:+.0f}\"],\n    \"on_rc\": [f\"{theta - 1:+.0f}\", f\"{power.theta - 1:+.0f}\"],\n})\n(\n    GT(sdf_df)\n    .tab_header(title=\"Kernel exposures under two preference settings\")\n    .cols_label(preferences=\"\", theta=\"theta\",\n                on_dc=\"coefficient on dc\", on_rc=\"coefficient on r_c\")\n    .tab_source_note(\"Computed from the parameters in the cell above.\")\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nm = theta*log(delta) - (theta/psi)*dc + (theta-1)*r_c\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div id=\"ppznuklbvh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#ppznuklbvh table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#ppznuklbvh thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#ppznuklbvh p { margin: 0; padding: 0; }\n #ppznuklbvh .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #ppznuklbvh .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #ppznuklbvh .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #ppznuklbvh .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #ppznuklbvh .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #ppznuklbvh .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #ppznuklbvh .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #ppznuklbvh .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #ppznuklbvh .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #ppznuklbvh .gt_column_spanner_outer:first-child { padding-left: 0; }\n #ppznuklbvh .gt_column_spanner_outer:last-child { padding-right: 0; }\n #ppznuklbvh .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #ppznuklbvh .gt_spanner_row { border-bottom-style: hidden; }\n #ppznuklbvh .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #ppznuklbvh .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #ppznuklbvh .gt_from_md> :first-child { margin-top: 0; }\n #ppznuklbvh .gt_from_md> :last-child { margin-bottom: 0; }\n #ppznuklbvh .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #ppznuklbvh .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #ppznuklbvh .gt_indent_1 { text-indent: 5px; }\n #ppznuklbvh .gt_indent_2 { text-indent: calc(5px * 2); }\n #ppznuklbvh .gt_indent_3 { text-indent: calc(5px * 3); }\n #ppznuklbvh .gt_indent_4 { text-indent: calc(5px * 4); }\n #ppznuklbvh .gt_indent_5 { text-indent: calc(5px * 5); }\n #ppznuklbvh .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #ppznuklbvh .gt_row_group_first td { border-top-width: 2px; }\n #ppznuklbvh .gt_row_group_first th { border-top-width: 2px; }\n #ppznuklbvh .gt_striped { color: #333333; background-color: #F4F4F4; }\n #ppznuklbvh .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #ppznuklbvh .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #ppznuklbvh .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #ppznuklbvh .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #ppznuklbvh .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #ppznuklbvh .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #ppznuklbvh .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #ppznuklbvh .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #ppznuklbvh .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #ppznuklbvh .gt_left { text-align: left; }\n #ppznuklbvh .gt_center { text-align: center; }\n #ppznuklbvh .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #ppznuklbvh .gt_font_normal { font-weight: normal; }\n #ppznuklbvh .gt_font_bold { font-weight: bold; }\n #ppznuklbvh .gt_font_italic { font-style: italic; }\n #ppznuklbvh .gt_super { font-size: 65%; }\n #ppznuklbvh .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #ppznuklbvh .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #ppznuklbvh .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #ppznuklbvh .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #ppznuklbvh .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #ppznuklbvh .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\">Kernel exposures under two preference settings</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"preferences\"></th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"theta\">theta</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"on_dc\">coefficient on dc</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"on_rc\">coefficient on r_c</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">Table II</td>\n    <td class=\"gt_row gt_right\">-27</td>\n    <td class=\"gt_row gt_right\">+18</td>\n    <td class=\"gt_row gt_right\">-28</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">power utility (gamma = 1/psi = 10)</td>\n    <td class=\"gt_row gt_right\">1</td>\n    <td class=\"gt_row gt_right\">-10</td>\n    <td class=\"gt_row gt_right\">+0</td>\n  </tr>\n</tbody>\n<tfoot><tr class=\"gt_sourcenotes\"><td class=\"gt_sourcenote\" colspan=\"4\"><span class=\"gt_from_md\">Computed from the parameters in the cell above.</span></td></tr></tfoot>\n</table>\n\n</div>\n```\n:::\n:::\n\n\nFirst, the power-utility row is the promised special case. Set\n$\\psi = 1/\\gamma$; $\\theta$ returns to 1; the wealth-return exposure\ndrops to 0; and the consumption coefficient becomes $-\\gamma$. Second,\nin the Table II row the raw coefficient on $\\Delta c$ is positive\n($+18$) while the coefficient on $r_{c}$ is large and negative\n($-28$). Do not read the two in isolation. The wealth return covaries\nstrongly and positively with consumption growth. Once $r_{c,t+1}$ is\nexpressed in terms of the underlying shocks, the net exposure to\nshort-run consumption news is $-\\gamma$, plus a new negative exposure\nto long-run news that power utility lacks.\n[Chapter 6](06-log-linear-solution.qmd) performs the substitution and\nprints the risk price attached to each shock.\n\n## Takeaways\n\n- Power utility ties two distinct attitudes together. Epstein-Zin\n  preferences (@eq-ez) make risk aversion $\\gamma$ and the substitution\n  elasticity $\\psi$ separate parameters, with\n  $\\theta = (1-\\gamma)/(1-1/\\psi)$ measuring their gap.\n- The kernel (@eq-kernel) contains the return on total wealth. Because\n  the wealth return is forward-looking, news about future consumption\n  moves marginal utility today, so long-run news is priced.\n- Power utility is the $\\theta = 1$ special case. The wealth-return\n  term vanishes and only realized consumption growth matters, which is\n  why Chapter 3's kernel misses the risk that value stocks carry.\n- With $\\gamma > 1/\\psi$ the investor prefers early resolution of\n  uncertainty and fears persistent risks. Table II's\n  $\\delta = 0.999$, $\\gamma = 10$, $\\psi = 1.5$ give $\\theta = -27$.\n\n## Exercises\n\n1. Compute $\\theta$ for $\\gamma = 10$ and $\\psi \\in\n   \\{0.5,\\, 0.9,\\, 1.1,\\, 1.5,\\, 2.0\\}$ using\n   `lrr.PreferencesParams(gamma=10.0, psi=...)`. Where does the sign\n   flip, and what happens as $\\psi \\to 1$?\n2. Hold $\\psi = 1.5$ and lower $\\gamma$ toward $1/\\psi$. At what\n   $\\gamma$ does $\\theta$ reach 1, and what does @eq-kernel look like\n   there? Interpret the investor's attitude to the timing of\n   resolution at that point.\n3. Substitute $\\theta = 1$ into @eq-ez and show, line by line, that the\n   recursion reduces to expected power utility\n   $V_t^{1-\\gamma} \\propto E_t \\sum_j \\delta^j C_{t+j}^{1-\\gamma}$ (up\n   to a monotone transformation). Which step uses $\\gamma = 1/\\psi$?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n::: {#00ddb3fa .cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\"}\n# Exercise 1: theta as psi moves, gamma fixed at 10\nfor psi in (0.5, 0.9, 1.1, 1.5, 2.0):\n    print(f\"psi = {psi:.1f}:  theta = \"\n          f\"{lrr.PreferencesParams(gamma=10.0, psi=psi).theta:8.2f}\")\n\n# Exercise 2: theta = 1 at gamma = 1/psi\nprint(f\"gamma = 1/psi = {1/1.5:.3f}:  theta = \"\n      f\"{lrr.PreferencesParams(gamma=1/1.5, psi=1.5).theta:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npsi = 0.5:  theta =     9.00\npsi = 0.9:  theta =    81.00\npsi = 1.1:  theta =   -99.00\npsi = 1.5:  theta =   -27.00\npsi = 2.0:  theta =   -18.00\ngamma = 1/psi = 0.667:  theta = 1.00\n```\n:::\n:::\n\n\nThe sign of theta flips at psi = 1, and its magnitude explodes as psi\napproaches 1 from either side. Theta reaches 1 exactly at gamma = 1/psi,\nwhere the recursivity is silent about the timing of resolution.\n\nExercise 3 is an algebra proof, not a computation. The step that uses\ngamma = 1/psi is the one where the continuation value inside the certainty\nequivalent becomes a power of the linear aggregator, so the recursion\ncollapses to a sum of expected power utilities.\n\n:::\n\n::: {.firewall}\n**Where each number comes from.** The values $\\delta = 0.999$,\n$\\gamma = 10$, $\\psi = 1.5$, and $\\theta = -27$ come from the tables\nabove, read from `lrr.get_table_ii_params().prefs`, and the\npower-utility check uses `lrr.PreferencesParams(gamma=10.0, psi=0.1)`.\nNo number on this page is typed by hand. Download the chapter as a\nnotebook (top of the page) to rerun everything.\n:::\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: C:\\DBD\\kiku-value-premium-replication\\.venv\\share\\jupyter\\kernels\\python3\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.12.12\n---\n",
    "supporting": [
      "04-epstein-zin-preferences_files\\figure-ipynb"
    ],
    "filters": [],
    "includes": {}
  }
}