{
  "hash": "88afc7da8a217ea781bd3f8866c3d323",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"3. Pricing by Euler equation\"\n---\n\nPart I ended with a diagnosis. A discounted-cash-flow valuation has two\nfree numbers, a growth rate and a discount rate, and nothing inside\nthe method constrains either one ([Chapter 1](01-two-free-numbers.qmd)).\nThe data also contain a spread that the standard repair does not price.\nValue portfolios have out-earned growth portfolios by about six points\na year, while their market betas suggest the opposite ranking\n([Chapter 2](02-value-premium-in-the-data.qmd)). The chapter begins the\nrebuild by replacing the two free numbers with one equation and one\neconomic object.\n\nThe equation says that an investor who can buy a little more or a\nlittle less of any asset must, at her chosen consumption plan, be\nindifferent to doing so. The indifference condition prices the asset.\nNo forecast and no exogenous discount rate enter. The price comes from\nthe investor's willingness to trade consumption today for consumption\nin each possible state tomorrow.\n\nThe condition applies to any claim, and the generality is why the\ncourse is called *valuing asset claims* rather than valuing stocks.\nThe same condition, with the same economic object inside it, prices a\nbroad stock portfolio, a Treasury bill, a value portfolio, and the\ndividend stream of a private firm that has never traded. The condition\ndoes not depend on what the claim is called. It depends only on what\nthe claim's payoffs covary with.\n\nThe chapter then tests the simplest version of the economic object,\nthe power-utility kernel that most of macroeconomics uses, on 74 years\nof data, and the kernel fails three times. The three failures are the\nreason [Chapter 4](04-epstein-zin-preferences.qmd) changes the\npreferences and [Chapter 5](05-long-run-risks.qmd) changes the\nendowment.\n\n## One equation for every claim\n\nFor any traded claim $i$ with gross return $R_{i,t+1}$, the first-order\ncondition of an investor's consumption and portfolio problem is\n\n$$\nE_t\\!\\left[M_{t+1}\\, R_{i,t+1}\\right] = 1 .\n$$ {#eq-euler}\n\n$M_{t+1}$ is the **pricing kernel** (also called the stochastic\ndiscount factor, or the intertemporal marginal rate of substitution).\nIt is the rate at which the investor is willing to exchange consumption\nat $t$ for consumption in each state at $t+1$. The kernel is high in\nstates where marginal utility is high, so the investor is desperate,\nand low in states where she is flush. Equation @eq-euler says that once\npayoffs are weighted by the state-by-state exchange rate, every asset\nearns exactly its price. No claim earns extra return for free, relative\nto the investor's own marginal utility.\n\n::: {.callout-note collapse=\"true\" title=\"Derivation: the Euler equation from a consumption choice\"}\nLet the investor maximize $E_t \\sum_j \\delta^j u(C_{t+j})$ and consider\na perturbation: reduce consumption at $t$ by a small amount $\\xi$, buy\n$\\xi/P_t$ units of an asset with price $P_t$ and payoff $X_{t+1}$, and\nconsume the proceeds. At an optimum the perturbation cannot improve\nwelfare in either direction, so the marginal cost equals the marginal\nbenefit: $u'(C_t)\\,P_t = E_t[\\delta\\, u'(C_{t+1})\\, X_{t+1}]$. Divide\nby $u'(C_t)$ and by $P_t$, and define\n$M_{t+1} = \\delta\\, u'(C_{t+1})/u'(C_t)$ and\n$R_{i,t+1} = X_{t+1}/P_t$; the result is @eq-euler. Nothing in the\nargument used what the asset is, only that the investor could hold a\nlittle more or less of it. The same $M$ therefore prices every claim\nshe can trade, and prices a non-traded dividend stream by the value at\nwhich she would be indifferent to holding it.\n:::\n\nIn price form the equation reads $P_t = E_t[M_{t+1} X_{t+1}]$, so\ntoday's price is the payoff in each state, weighted by probability and\nby how much a unit of payoff is worth in that state. A DCF collapses\nthe weighted sum into a single discount rate. The Euler equation keeps\nthe states separate, and the risk adjustment comes from the state\nweights.\n\nApplied to a riskless claim, whose return is known at $t$, @eq-euler\ngives\n\n$$\nR_{f,t} = \\frac{1}{E_t[M_{t+1}]} ,\n$$ {#eq-rf}\n\nso the level of the kernel pins down the risk-free rate. Subtracting\nthe riskless version from the risky one turns @eq-euler into a\nstatement about premia:\n\n$$\nE_t[R_{i,t+1}] - R_{f,t} = -R_{f,t}\\,\\mathrm{Cov}_t\\!\\left(M_{t+1},\\, R_{i,t+1}\\right) .\n$$ {#eq-premium}\n\nEvery risk premium is a covariance with the kernel. A claim commands a\nhigh expected return if and only if it pays badly in the states where\n$M$ is high, which are the states where the investor is already\nhurting. A claim that pays well in those states is insurance, and its\npremium is negative, whatever its volatility. Volatility by itself\nearns nothing, because only the covariance is priced. The CAPM\napproximates @eq-premium with the market return standing in for $-M$,\nand the rest of the course computes the covariance exactly.\n\n## The simplest kernel\n\nTo use @eq-premium quantitatively we need a concrete $M$. The standard\nchoice is time-separable power utility,\n$u(C) = C^{1-\\gamma}/(1-\\gamma)$, for which\n\n$$\nM_{t+1} = \\delta \\left(\\frac{C_{t+1}}{C_t}\\right)^{-\\gamma} .\n$$ {#eq-crra}\n\nMarginal utility is high when consumption growth is low, so under\n@eq-crra an asset is risky exactly to the extent that it pays badly in\nconsumption recessions. With jointly lognormal consumption growth and\nreturns, @eq-premium becomes, in logs and up to a Jensen term, the\napproximation\n\n$$\nE[r_i] - r_f \\approx \\gamma\\, \\mathrm{Cov}(\\Delta c,\\, r_i),\n$$ {#eq-boe}\n\nand the volatility of the kernel bounds every attainable Sharpe ratio.\nHansen and Jagannathan (1991) show that\n$\\left|E[R_i] - R_f\\right| / \\sigma(R_i) \\le \\sigma(M)/E[M] \\approx \\gamma\\,\\sigma(\\Delta c)$.\nAggregate consumption growth is smooth, so unless $\\gamma$ is large the\nkernel barely moves. A kernel that barely moves cannot generate large\npremia. The arithmetic is the equity premium puzzle of Mehra and\nPrescott (1985), and the next section runs it on the course's sample.\n\n## Hands-on: testing the kernel on 74 years of data\n\nThe cells below use the three annual series built in Part I:\nreal consumption growth, the real T-bill, and returns on the growth,\nvalue, and market claims.\n\n::: {#f495bec3 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\n# Data bootstrap: use the repo's committed CSVs, or fetch them when this\n# notebook runs outside the repository.\nfrom pathlib import Path\nimport urllib.request\n\nDATA = Path(\"../../data\")\nif not DATA.exists():\n    DATA = Path(\"data\")\n    DATA.mkdir(exist_ok=True)\n    base = (\"https://raw.githubusercontent.com/tlorans/\"\n            \"kiku-value-premium-replication/main/data/\")\n    for f in (\"consumption_annual.csv\", \"rf_annual.csv\", \"annual_panel.csv\"):\n        if not (DATA / f).exists():\n            urllib.request.urlretrieve(base + f, DATA / f)\n```\n:::\n\n\n::: {#ee93f75a .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\ncons = pd.read_csv(DATA / \"consumption_annual.csv\")\nrf = pd.read_csv(DATA / \"rf_annual.csv\")\npanel = pd.read_csv(DATA / \"annual_panel.csv\")\n\nrets = panel.pivot(index=\"year\", columns=\"claim\", values=\"ret\")\ndf = rets.join(rf.set_index(\"year\")).join(cons.set_index(\"year\"))\nprint(f\"{len(df)} annual observations, {df.index.min()}-{df.index.max()}\")\nprint(f\"consumption growth: mean {df.dc.mean():.2%}, sd {df.dc.std():.2%}\")\nprint(f\"real T-bill:        mean {df.rf.mean():.2%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n74 annual observations, 1930-2003\nconsumption growth: mean 1.75%, sd 2.37%\nreal T-bill:        mean 0.07%\n```\n:::\n:::\n\n\nThe endowment is smooth, with consumption growth moving about two\npoints a year, and the real bill earns roughly nothing. The next cell\nprints the premia the kernel has to explain:\n\n::: {#c982abc3 .cell execution_count=3}\n``` {.python .cell-code}\nfor name in (\"Growth\", \"Value\", \"Market\"):\n    ex = df[name] - df.rf\n    print(f\"{name:8s} mean excess {ex.mean():6.2%}   \"\n          f\"sd {ex.std():6.2%}   Sharpe {ex.mean() / ex.std():.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGrowth   mean excess  7.42%   sd 19.99%   Sharpe 0.37\nValue    mean excess 13.60%   sd 29.65%   Sharpe 0.46\nMarket   mean excess  8.45%   sd 20.07%   Sharpe 0.42\n```\n:::\n:::\n\n\nFeed the excess returns into @eq-boe with a conventional risk aversion\nof $\\gamma = 10$:\n\n::: {#0fb920f3 .cell execution_count=4}\n``` {.python .cell-code}\ngamma = 10.0\nfor name in (\"Growth\", \"Value\", \"Market\"):\n    ex = df[name] - df.rf\n    cov = np.cov(ex, df.dc, ddof=1)[0, 1]\n    print(f\"{name:8s} actual {ex.mean():6.2%}   \"\n          f\"power utility, gamma=10: {gamma * cov:6.2%}\")\n\nex_m = df[\"Market\"] - df.rf\ncov_m = np.cov(ex_m, df.dc, ddof=1)[0, 1]\nprint(f\"\\ngamma needed to match the market premium: \"\n      f\"{ex_m.mean() / cov_m:.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGrowth   actual  7.42%   power utility, gamma=10:  0.43%\nValue    actual 13.60%   power utility, gamma=10: -0.02%\nMarket   actual  8.45%   power utility, gamma=10:  0.54%\n\ngamma needed to match the market premium: 155\n```\n:::\n:::\n\n\nThe failures are described below, from least to most severe.\n\n**The equity premium puzzle.** The market earned 8.45 percent over\nbills, while the power-utility kernel with $\\gamma = 10$ delivers 0.54\npercent. Closing the gap takes $\\gamma \\approx 155$, which describes\nan investor who would decline gambles that no one declines. Mehra and\nPrescott (1985) documented the same failure, and the cell reproduces\nit on the course's sample.\n\n**The risk-free rate puzzle.** Even the least demanding fix fails.\nThe Hansen-Jagannathan bound only asks the kernel to be volatile enough\nto support the market's Sharpe ratio, and then @eq-rf reports what the\nrequired volatility does to the interest rate:\n\n::: {#ae51f0d7 .cell execution_count=5}\n``` {.python .cell-code}\nsr = ex_m.mean() / ex_m.std()\ngamma_hj = sr / df.dc.std()\ndelta_annual = 0.999 ** 12\nrf_implied = (-np.log(delta_annual) + gamma_hj * df.dc.mean()\n              - gamma_hj**2 * df.dc.std()**2 / 2)\nprint(f\"market Sharpe ratio {sr:.2f}  =>  \"\n      f\"gamma >= {sr:.2f}/{df.dc.std():.4f} = {gamma_hj:.0f}\")\nprint(f\"risk-free rate implied by gamma = {gamma_hj:.0f}: \"\n      f\"{rf_implied:.1%}   (data: {df.rf.mean():.2%})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmarket Sharpe ratio 0.42  =>  gamma >= 0.42/0.0237 = 18\nrisk-free rate implied by gamma = 18: 23.4%   (data: 0.07%)\n```\n:::\n:::\n\n\nA $\\gamma$ of 18 matches the Sharpe ratio but predicts a 23 percent\nrisk-free rate, against 0.07 percent in the data. Power utility forces\nan investor that averse to risk to be equally averse to consumption\ngrowth, so she demands an enormous reward to lend into a growing\neconomy.\n\n**The value premium.** The deepest failure is in the cross section,\nand no choice of $\\gamma$ fixes it. In the $\\gamma = 10$ column,\ngrowth is assigned 0.43 percent and value is assigned $-0.02$ percent.\nValue's excess return barely covaries with contemporaneous consumption\ngrowth, and the point estimate is negative. As a result, @eq-boe\nassigns the highest-earning claim in the sample a premium of zero at\nany risk aversion. Scaling $\\gamma$ up scales all\nthree predictions together and can never produce the six-point spread.\nThe one-period consumption covariance is measuring the wrong risk.\n\nThe rest of Part II builds a kernel that measures a different risk.\nThe premium must still be a covariance with the kernel, because\n@eq-premium holds for any preferences. The kernel must therefore\nrespond to something other than consumption in the current year.\n[Chapter 4](04-epstein-zin-preferences.qmd) builds\npreferences under which news about future consumption enters marginal\nutility today, and [Chapter 5](05-long-run-risks.qmd) builds an\nendowment in which there is persistent news to be had.\n\n## Takeaways\n\n- One condition, $E_t[M_{t+1}R_{i,t+1}] = 1$, prices every claim. The\n  same kernel values a stock index, a bill, and a private dividend\n  stream, and only the cash flows change across claims.\n- Premia are covariances (@eq-premium). A claim is risky if it pays\n  badly when marginal utility is high, and volatility alone earns\n  nothing.\n- The power-utility kernel fails three ways on 74 years of data: the\n  market premium needs $\\gamma \\approx 155$; a $\\gamma$ large enough\n  for the Sharpe ratio implies a 23 percent risk-free rate; and value's\n  consumption covariance is zero, so no $\\gamma$ prices the value\n  premium.\n- The fix cannot be a bigger $\\gamma$. The kernel must price a\n  different risk.\n\n## Exercises\n\n1. Compute the value-minus-growth spread's mean, volatility, and Sharpe\n   ratio from `annual_panel.csv`. What kernel volatility\n   $\\sigma(M)/E[M]$ does the Hansen-Jagannathan bound demand for that\n   claim alone, and what $\\gamma$ does that imply?\n2. Rerun the $\\gamma = 10$ cell with $\\gamma = 50$ and $\\gamma = 155$.\n   Verify that the ratio of the predicted value premium to the\n   predicted growth premium never moves. Why not?\n3. Using @eq-rf under lognormality,\n   $r_f = -\\log\\delta + \\gamma E[\\Delta c] - \\tfrac{1}{2}\\gamma^2\\sigma^2(\\Delta c)$,\n   solve for the $\\delta$ that reconciles $\\gamma = 155$ with the\n   observed 0.07 percent real rate. Is it a discount factor a patient\n   investor could have?\n\n::: {.firewall}\n**Where each number comes from.** Every number above is printed by the\ncells on this page from three files built in Part I\n(`data/consumption_annual.csv`, `data/rf_annual.csv`, and\n`data/annual_panel.csv`), using only `numpy` and `pandas`. The\n$\\gamma \\approx 155$ and 23 percent figures are the cells' own output.\nDownload the chapter as a notebook (top of the page) to rerun\neverything.\n:::\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: C:\\DBD\\kiku-value-premium-replication\\.venv\\share\\jupyter\\kernels\\python3\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.12.12\n---\n",
    "supporting": [
      "03-pricing-by-euler-equation_files\\figure-ipynb"
    ],
    "filters": [],
    "includes": {}
  }
}