{
  "hash": "e3757ff4723a2854a06cbba764d4b235",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"10. The value premium, resolved\"\naliases: [/cross-section.html]\n---\n\nNothing has been re-tuned since\n[Chapter 8](08-calibrating-cash-flows.qmd). The household, the\nconsumption process, and the Euler equation are the same ones that\njust priced the market in [Chapter 9](09-the-market-test.qmd). A model\nthat needed a new discount rate for every asset would repeat the DCF's\nproblem. The only thing that distinguishes the value claim from the\ngrowth claim inside the model is the set of cash-flow parameters each\nbrought from [Chapter 8](08-calibrating-cash-flows.qmd), and above all\nvalue's dividend loading on long-run consumption news, $\\phi_V = 6.2$,\nagainst growth's $\\phi_G = 2.6$.\n\nThe chapter asks the model for four results at once:\n\n- the six-point return spread between value and growth;\n- the valuation ranking, in which value trades cheaper than growth;\n- the CAPM anomaly, in which value's market beta fails to explain its\n  premium inside the model the way it fails in the data;\n- a counterfactual, in which setting value's long-run loading equal to\n  growth's removes the premium.\n\nIf the beta anomaly does not appear, the model has explained some\nother economy. If the premium survives the counterfactual, something\nother than the loading was doing the work.\n\n## The facts to be explained\n\n::: {#4010cd12 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\n# Data bootstrap: use the repo's committed CSVs, or fetch them when this\n# notebook runs outside the repository.\nfrom pathlib import Path\nimport urllib.request\n\nDATA = Path(\"../../data\")\nif not DATA.exists():\n    DATA = Path(\"data\")\n    DATA.mkdir(exist_ok=True)\n    base = (\"https://raw.githubusercontent.com/tlorans/\"\n            \"kiku-value-premium-replication/main/data/\")\n    for f in (\"annual_panel.csv\", \"consumption_annual.csv\", \"rf_annual.csv\"):\n        if not (DATA / f).exists():\n            urllib.request.urlretrieve(base + f, DATA / f)\n```\n:::\n\n\n::: {#351994a8 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport lrrcs as lrr\nfrom great_tables import GT\n\nKIKU_GT = dict(table_background_color=\"transparent\",\n               table_font_size=\"0.92rem\",\n               heading_title_font_size=\"1.05rem\",\n               heading_subtitle_font_size=\"0.85rem\",\n               source_notes_font_size=\"0.8rem\",\n               column_labels_font_weight=\"bold\",\n               data_row_padding=\"4px\")\n\npanel = pd.read_csv(DATA / \"annual_panel.csv\")\nmeans = {c: float(panel[panel[\"claim\"] == c][\"ret\"].mean() * 100)\n         for c in (\"Growth\", \"Value\", \"Market\")}\nprint(f\"value-growth spread: {means['Value'] - means['Growth']:.2f} points\")\n\nrm = panel[panel[\"claim\"] == \"Market\"].sort_values(\"year\")[\"ret\"].to_numpy()\nrm_d = rm - rm.mean()\nfor c in (\"Growth\", \"Value\"):\n    r = panel[panel[\"claim\"] == c].sort_values(\"year\")[\"ret\"].to_numpy()\n    print(f\"CAPM beta, {c.lower():6s}: \"\n          f\"{float(rm_d @ (r - r.mean()) / (rm_d @ rm_d)):.2f}\")\n\n(\n    GT(pd.DataFrame({\"claim\": list(means), \"ret\": list(means.values())}))\n    .tab_header(title=\"Mean annual returns in the data\")\n    .cols_label(claim=\"\", ret=\"mean return %\")\n    .fmt_number(columns=\"ret\", decimals=2)\n    .tab_source_note(\"From data/annual_panel.csv, 1930 to 2003.\")\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nvalue-growth spread: 6.18 points\nCAPM beta, growth: 0.95\nCAPM beta, value : 1.28\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div id=\"facmskkyox\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#facmskkyox table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#facmskkyox thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#facmskkyox p { margin: 0; padding: 0; }\n #facmskkyox .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #facmskkyox .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #facmskkyox .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #facmskkyox .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #facmskkyox .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #facmskkyox .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #facmskkyox .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #facmskkyox .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #facmskkyox .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #facmskkyox .gt_column_spanner_outer:first-child { padding-left: 0; }\n #facmskkyox .gt_column_spanner_outer:last-child { padding-right: 0; }\n #facmskkyox .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #facmskkyox .gt_spanner_row { border-bottom-style: hidden; }\n #facmskkyox .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #facmskkyox .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #facmskkyox .gt_from_md> :first-child { margin-top: 0; }\n #facmskkyox .gt_from_md> :last-child { margin-bottom: 0; }\n #facmskkyox .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #facmskkyox .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #facmskkyox .gt_indent_1 { text-indent: 5px; }\n #facmskkyox .gt_indent_2 { text-indent: calc(5px * 2); }\n #facmskkyox .gt_indent_3 { text-indent: calc(5px * 3); }\n #facmskkyox .gt_indent_4 { text-indent: calc(5px * 4); }\n #facmskkyox .gt_indent_5 { text-indent: calc(5px * 5); }\n #facmskkyox .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #facmskkyox .gt_row_group_first td { border-top-width: 2px; }\n #facmskkyox .gt_row_group_first th { border-top-width: 2px; }\n #facmskkyox .gt_striped { color: #333333; background-color: #F4F4F4; }\n #facmskkyox .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #facmskkyox .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #facmskkyox .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #facmskkyox .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #facmskkyox .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #facmskkyox .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #facmskkyox .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #facmskkyox .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #facmskkyox .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #facmskkyox .gt_left { text-align: left; }\n #facmskkyox .gt_center { text-align: center; }\n #facmskkyox .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #facmskkyox .gt_font_normal { font-weight: normal; }\n #facmskkyox .gt_font_bold { font-weight: bold; }\n #facmskkyox .gt_font_italic { font-style: italic; }\n #facmskkyox .gt_super { font-size: 65%; }\n #facmskkyox .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #facmskkyox .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #facmskkyox .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #facmskkyox .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #facmskkyox .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #facmskkyox .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal\">Mean annual returns in the data</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"claim\"></th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ret\">mean return %</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">Growth</td>\n    <td class=\"gt_row gt_right\">7.49</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Value</td>\n    <td class=\"gt_row gt_right\">13.67</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Market</td>\n    <td class=\"gt_row gt_right\">8.52</td>\n  </tr>\n</tbody>\n<tfoot><tr class=\"gt_sourcenotes\"><td class=\"gt_sourcenote\" colspan=\"2\"><span class=\"gt_from_md\">From data/annual_panel.csv, 1930 to 2003.</span></td></tr></tfoot>\n</table>\n\n</div>\n```\n:::\n:::\n\n\nValue out-earns growth by 6.18 percentage points a year on the\nreconstruction used here (the paper's vintage prints 13.88 against\n7.81, a 6.07 spread). The CAPM cannot explain a spread of six points\nwith the estimated betas. The betas are 1.28 against 0.95 here, and\nwith the market earning 8.52 the beta gap prices a spread of roughly\n$(1.28 - 0.95) \\times 8.5 \\approx 2.8$ points, which is less than half\nof the spread in the data. On the paper's vintage both betas sit near\n1.03, where the CAPM predicts no spread at all. Value also trades\ncheaper than growth in almost every year, as the figure below shows.\n\n::: {#3d616c27 .cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\"}\nfrom plotnine import (ggplot, aes, geom_line, labs, scale_color_manual,\n                      coord_cartesian, theme_minimal, theme,\n                      element_blank, element_line, element_text)\n\npd_long = panel[panel[\"claim\"].isin([\"Growth\", \"Value\"])].copy()\npd_long[\"log_pd\"] = np.log(pd_long[\"pd\"])\npd_long[\"claim\"] = pd_long[\"claim\"].str.lower()\n\np = (\n    ggplot(pd_long, aes(\"year\", \"log_pd\", color=\"claim\"))\n    + geom_line(size=0.9)\n    + scale_color_manual(values={\"growth\": \"#1b1714\", \"value\": \"#7a1f1f\"})\n    + coord_cartesian(ylim=(2.2, 4.6))\n    + labs(x=\"year\", y=\"log(P/D)\")\n    + theme_minimal(base_size=11)\n    + theme(figure_size=(6.5, 3.4), text=element_text(color=\"#2d2926\"),\n            panel_grid_minor=element_blank(),\n            panel_grid_major=element_line(color=\"#e2d6c4\", size=0.4),\n            axis_line=element_line(color=\"#1b1714\", size=0.5),\n            legend_title=element_blank(), legend_position=\"top\")\n)\np.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Log price-dividend ratios of the growth and value portfolios, 1930 to 2003. Value trades below growth in essentially every year. Its series has a gap and a distorted print around 1933 to 1934, when its dividends nearly vanished. The value premium and the valuation discount are the same fact.](10-value-premium-resolved_files/figure-html/cell-4-output-1.svg){}\n:::\n:::\n\n\n## The model's Table VII\n\nSolve on the paper's grid and simulate the paper's object, meaning\nhundreds of 74-year samples with statistics estimated sample by sample\nand then averaged ([Chapter 9](09-the-market-test.qmd) explained why\nsample statistics are the right comparison). The code path, seed, and\ngrid are the same as in the market test, and the value and growth rows\nsimply come along.\n\nIt is worth being clear about how we ask. The model prices a set of\nnamed claims, and it does not know that one of them is the value\nportfolio and another the growth portfolio. Asking for the value\npremium is therefore a step we take after the solve. We name the two\nclaims we want to set side by side, and the comparison gives us the\nreturn spread, the valuation spread, and the ratio of the two CAPM\nbetas. We wrap that call in a small helper because the chapter asks\nfor the same pair many times.\n\n::: {#cc685afa .cell execution_count=4}\n``` {.python .cell-code}\nmodel = lrr.LongRunRisksModel()\nsim = model.simulate(n_samples=300, years=74, seed=0, n_x=30, n_s=4)\n\n\ndef value_growth(res):\n    \"\"\"Value against growth, with the market as the beta reference.\"\"\"\n    return res.compare(\"value\", \"growth\", market=\"market\")\n\n\ncmp = value_growth(sim)\nprint(f\"risk-free rate : {sim.risk_free:.2f}%  (SE {sim.risk_free_se:.2f})\")\nprint(f\"value premium  : {cmp.premium:.2f}%\")\nprint(f\"CAPM beta ratio (value/growth): {cmp.beta_ratio:.2f}\")\n\n# The row order below is ours to choose. The model prices the claims as\n# a set, so nothing in it says growth comes before value.\norder = [\"growth\", \"value\", \"market\"]\nbetas = sim.capm_betas(\"market\")\n(\n    GT(pd.DataFrame({\n        \"portfolio\": order,\n        \"er\": [sim.expected_returns[n] for n in order],\n        \"se\": [sim.expected_returns_se[n] for n in order],\n        \"vol\": [sim.volatility[n] for n in order],\n        \"sharpe\": [sim.sharpe_ratios[n] for n in order],\n        \"beta\": [betas[n] for n in order],\n        \"pd_level\": [sim.pd_levels[n] for n in order],\n        \"log_pd\": [sim.mean_log_pd[n] for n in order],\n    }))\n    .tab_header(title=\"Table VII by simulation\")\n    .cols_label(portfolio=\"\", er=\"E[R] %\", se=\"SE\", vol=\"Vol %\",\n                sharpe=\"Sharpe\", beta=\"CAPM beta\", pd_level=\"P/D\",\n                log_pd=\"log P/D\")\n    .fmt_number(columns=[\"er\", \"se\", \"vol\", \"sharpe\", \"beta\", \"log_pd\"],\n                decimals=2)\n    .fmt_number(columns=\"pd_level\", decimals=1)\n    .tab_source_note(\"300 simulated samples of 74 years, seed 0.\")\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrisk-free rate : 1.04%  (SE 0.62)\nvalue premium  : 5.38%\nCAPM beta ratio (value/growth): 0.81\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div id=\"qqtxgzyzsu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#qqtxgzyzsu table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#qqtxgzyzsu thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#qqtxgzyzsu p { margin: 0; padding: 0; }\n #qqtxgzyzsu .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #qqtxgzyzsu .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #qqtxgzyzsu .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #qqtxgzyzsu .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #qqtxgzyzsu .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #qqtxgzyzsu .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #qqtxgzyzsu .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #qqtxgzyzsu .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #qqtxgzyzsu .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #qqtxgzyzsu .gt_column_spanner_outer:first-child { padding-left: 0; }\n #qqtxgzyzsu .gt_column_spanner_outer:last-child { padding-right: 0; }\n #qqtxgzyzsu .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #qqtxgzyzsu .gt_spanner_row { border-bottom-style: hidden; }\n #qqtxgzyzsu .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #qqtxgzyzsu .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #qqtxgzyzsu .gt_from_md> :first-child { margin-top: 0; }\n #qqtxgzyzsu .gt_from_md> :last-child { margin-bottom: 0; }\n #qqtxgzyzsu .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #qqtxgzyzsu .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #qqtxgzyzsu .gt_indent_1 { text-indent: 5px; }\n #qqtxgzyzsu .gt_indent_2 { text-indent: calc(5px * 2); }\n #qqtxgzyzsu .gt_indent_3 { text-indent: calc(5px * 3); }\n #qqtxgzyzsu .gt_indent_4 { text-indent: calc(5px * 4); }\n #qqtxgzyzsu .gt_indent_5 { text-indent: calc(5px * 5); }\n #qqtxgzyzsu .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #qqtxgzyzsu .gt_row_group_first td { border-top-width: 2px; }\n #qqtxgzyzsu .gt_row_group_first th { border-top-width: 2px; }\n #qqtxgzyzsu .gt_striped { color: #333333; background-color: #F4F4F4; }\n #qqtxgzyzsu .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #qqtxgzyzsu .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #qqtxgzyzsu .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #qqtxgzyzsu .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #qqtxgzyzsu .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #qqtxgzyzsu .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #qqtxgzyzsu .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #qqtxgzyzsu .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #qqtxgzyzsu .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #qqtxgzyzsu .gt_left { text-align: left; }\n #qqtxgzyzsu .gt_center { text-align: center; }\n #qqtxgzyzsu .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #qqtxgzyzsu .gt_font_normal { font-weight: normal; }\n #qqtxgzyzsu .gt_font_bold { font-weight: bold; }\n #qqtxgzyzsu .gt_font_italic { font-style: italic; }\n #qqtxgzyzsu .gt_super { font-size: 65%; }\n #qqtxgzyzsu .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #qqtxgzyzsu .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #qqtxgzyzsu .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #qqtxgzyzsu .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #qqtxgzyzsu .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #qqtxgzyzsu .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"8\" class=\"gt_heading gt_title gt_font_normal\">Table VII by simulation</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"portfolio\"></th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"er\">E[R] %</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\">SE</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"vol\">Vol %</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sharpe\">Sharpe</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"beta\">CAPM beta</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pd_level\">P/D</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"log_pd\">log P/D</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">growth</td>\n    <td class=\"gt_row gt_right\">7.94</td>\n    <td class=\"gt_row gt_right\">3.35</td>\n    <td class=\"gt_row gt_right\">21.63</td>\n    <td class=\"gt_row gt_right\">0.32</td>\n    <td class=\"gt_row gt_right\">0.90</td>\n    <td class=\"gt_row gt_right\">25.7</td>\n    <td class=\"gt_row gt_right\">3.19</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">value</td>\n    <td class=\"gt_row gt_right\">13.32</td>\n    <td class=\"gt_row gt_right\">4.96</td>\n    <td class=\"gt_row gt_right\">25.61</td>\n    <td class=\"gt_row gt_right\">0.48</td>\n    <td class=\"gt_row gt_right\">0.72</td>\n    <td class=\"gt_row gt_right\">20.1</td>\n    <td class=\"gt_row gt_right\">2.81</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">market</td>\n    <td class=\"gt_row gt_right\">8.93</td>\n    <td class=\"gt_row gt_right\">3.25</td>\n    <td class=\"gt_row gt_right\">19.68</td>\n    <td class=\"gt_row gt_right\">0.40</td>\n    <td class=\"gt_row gt_right\">1.00</td>\n    <td class=\"gt_row gt_right\">21.4</td>\n    <td class=\"gt_row gt_right\">3.01</td>\n  </tr>\n</tbody>\n<tfoot><tr class=\"gt_sourcenotes\"><td class=\"gt_sourcenote\" colspan=\"8\"><span class=\"gt_from_md\">300 simulated samples of 74 years, seed 0.</span></td></tr></tfoot>\n</table>\n\n</div>\n```\n:::\n:::\n\n\nWalk through what the table shows, fact by fact.\n\n**The premium.** The simulated value premium is 5.38 percent, and the\npaper's Table VII prints 5.3 on 1,000 samples. The data show roughly\nsix (6.18 on the reconstruction, 6.07 on the paper's vintage). Value\nearns 13.32 against the data's 13.67, and growth earns 7.94 against\n7.49. The cross-sample dispersions (4.96 and 3.35) say a 74-year\nsample from the model economy routinely strays a few points from the\nreported means, and the data column is one such sample. No return was\ntargeted anywhere in the calibration, so the spread comes entirely\nfrom $\\phi_V - \\phi_G$ and the pricing framework of Chapters 4 to 7.\n\n**The valuation ranking.** Mean log P/D prints 2.81 for value, 3.01\nfor the market, and 3.19 for growth (the paper prints 3.10, 3.24, and\n3.65 on the same ranking). Value is the cheapest and growth is the most expensive,\nwhich is the data's ordering. The claim that earns more is the claim\nthat costs less, because the long-run loading drives both. A high\n$\\phi$ makes dividends riskier in the state investors fear, so the\nprice is low and the expected return is high. A DCF treats the\nvaluation discount and the return premium as two separate numbers,\nwhile the model derives both from the same loading.\n\n**The CAPM anomaly, reproduced inside the model.** In the beta column,\nvalue's CAPM beta prints 0.72, below growth's 0.90, while value's mean\nreturn is more than five points higher. The beta ratio is 0.81 (the\npaper prints 0.92, and both vintages of the data put the ratio near or\nabove one). The model reproduces the anomaly that\n[Chapter 1](01-two-free-numbers.qmd) used to argue against the CAPM.\nIt can do so because a single market beta is a one-factor projection\nof three separately priced risks, namely short-run consumption shocks,\nlong-run growth news, and volatility news\n([Chapter 6](06-log-linear-solution.qmd)), and the projection mixes\nthem together. Value loads heavily on long-run news, which is\nexpensive per unit of return covariance. Growth's return covaries\nstrongly with the market, because growth is a long-duration claim and\nis sensitive to discount rates, while carrying little of the priced\ncash-flow risk. In the paper's decomposition (its footnote 10), the\n5.3-point spread splits into roughly $-0.6$ from short-run risk,\n$+4.6$ from long-run growth risk, and $+1.3$ from volatility risk.\nAbout 85 percent of the premium comes from the long-run channel, and\nabout a quarter comes from volatility. The three parts sum past 100\npercent because the short-run piece is negative. A beta regression\ncaptures only the sum of the covariances and prices none of the parts.\n\nTwo shorthand terms used across the course name the two ways a price\ncan move, and the chapter puts both in view at once.\nCash-flow news is a revision in expected dividends, the quantity the\nloadings measure. Discount-rate news is a revision in expected\nreturns. The value premium comes from cash-flow news. Value's\ndividends move with long-run consumption news, so holding value is\nbearing cash-flow news about the next decade. Growth's price is\nsensitive to discount-rate news instead, because a long-duration claim\ngains the most when the rate falls.\n\n## The counterfactual: set the loadings equal\n\nIf the explanation is right, the premium depends on one input. Set\nvalue's long-run loading equal to growth's 2.6; leave everything else\nalone, including value's volatility loading $\\varphi_\\sigma$ and its\nshort-run correlation $\\alpha$; then re-solve. The counterfactual is\none line. `model.replace` returns a new model with the named claim\nparameter overridden and every other parameter carried over unchanged,\nand the model it was called on is left alone. First, compute the\nanalytical long-run compensation of\n[Chapter 6](06-log-linear-solution.qmd):\n\n::: {#dd3188e6 .cell execution_count=5}\n``` {.python .cell-code}\nphi_growth = model.params.claims[\"growth\"].phi  # 2.6\nmodel_eq = model.replace(claims={\"value\": {\"phi\": phi_growth}})\nres_eq = model_eq.solve(method=\"analytical\")\n\nspread_eq = value_growth(res_eq).premium\nprint(f\"value-growth spread from long-run risks: {spread_eq:.2f}%\")\n\nclaims = list(res_eq.claims)\n(\n    GT(pd.DataFrame({\n        \"claim\": claims,\n        \"prem\": [res_eq.long_run_premium[n] for n in claims],\n        \"a1\": [res_eq.A1[n] for n in claims],\n    }))\n    .tab_header(title=\"Analytical long-run premia with equal loadings\")\n    .cols_label(claim=\"\", prem=\"long-run premium %\", a1=\"A1\")\n    .fmt_number(columns=\"prem\", decimals=2)\n    .fmt_number(columns=\"a1\", decimals=1)\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nvalue-growth spread from long-run risks: -0.12%\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div id=\"jfrlfczlvr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#jfrlfczlvr table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#jfrlfczlvr thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#jfrlfczlvr p { margin: 0; padding: 0; }\n #jfrlfczlvr .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #jfrlfczlvr .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #jfrlfczlvr .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #jfrlfczlvr .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #jfrlfczlvr .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #jfrlfczlvr .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #jfrlfczlvr .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #jfrlfczlvr .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #jfrlfczlvr .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #jfrlfczlvr .gt_column_spanner_outer:first-child { padding-left: 0; }\n #jfrlfczlvr .gt_column_spanner_outer:last-child { padding-right: 0; }\n #jfrlfczlvr .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #jfrlfczlvr .gt_spanner_row { border-bottom-style: hidden; }\n #jfrlfczlvr .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #jfrlfczlvr .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #jfrlfczlvr .gt_from_md> :first-child { margin-top: 0; }\n #jfrlfczlvr .gt_from_md> :last-child { margin-bottom: 0; }\n #jfrlfczlvr .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #jfrlfczlvr .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #jfrlfczlvr .gt_indent_1 { text-indent: 5px; }\n #jfrlfczlvr .gt_indent_2 { text-indent: calc(5px * 2); }\n #jfrlfczlvr .gt_indent_3 { text-indent: calc(5px * 3); }\n #jfrlfczlvr .gt_indent_4 { text-indent: calc(5px * 4); }\n #jfrlfczlvr .gt_indent_5 { text-indent: calc(5px * 5); }\n #jfrlfczlvr .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #jfrlfczlvr .gt_row_group_first td { border-top-width: 2px; }\n #jfrlfczlvr .gt_row_group_first th { border-top-width: 2px; }\n #jfrlfczlvr .gt_striped { color: #333333; background-color: #F4F4F4; }\n #jfrlfczlvr .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #jfrlfczlvr .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #jfrlfczlvr .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #jfrlfczlvr .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #jfrlfczlvr .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #jfrlfczlvr .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #jfrlfczlvr .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #jfrlfczlvr .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #jfrlfczlvr .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #jfrlfczlvr .gt_left { text-align: left; }\n #jfrlfczlvr .gt_center { text-align: center; }\n #jfrlfczlvr .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #jfrlfczlvr .gt_font_normal { font-weight: normal; }\n #jfrlfczlvr .gt_font_bold { font-weight: bold; }\n #jfrlfczlvr .gt_font_italic { font-style: italic; }\n #jfrlfczlvr .gt_super { font-size: 65%; }\n #jfrlfczlvr .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #jfrlfczlvr .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #jfrlfczlvr .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #jfrlfczlvr .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #jfrlfczlvr .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #jfrlfczlvr .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\">Analytical long-run premia with equal loadings</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"claim\"></th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"prem\">long-run premium %</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a1\">A1</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">growth</td>\n    <td class=\"gt_row gt_right\">0.39</td>\n    <td class=\"gt_row gt_right\">43.1</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">value</td>\n    <td class=\"gt_row gt_right\">0.28</td>\n    <td class=\"gt_row gt_right\">31.1</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">market</td>\n    <td class=\"gt_row gt_right\">0.34</td>\n    <td class=\"gt_row gt_right\">37.5</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\nThe 0.40 percent long-run spread of the baseline collapses, but the\nprint is $-0.12$ percent, not exactly zero. The residual has a\nmechanical explanation. The analytical formula linearizes each claim\naround its own sample-average valuation\n([Chapter 6](06-log-linear-solution.qmd)), and value's anchor (mean log\nP/D of 3.10) differs from growth's (3.65) because the claims still\ndiffer in their other cash-flow parameters, namely $\\mu_d$,\n$\\varphi_\\sigma$, and $\\alpha$. Different anchors give different\nlinearization slopes ($A_1$ of 31.1 against 43.1) even at identical\n$\\phi$, so a small artifact of the approximation survives. The full\nEuler-equation simulation has no linearization anchor, so ask it the\nsame question:\n\n::: {#39986555 .cell execution_count=6}\n``` {.python .cell-code}\nsim_eq = model_eq.simulate(n_samples=300, years=74, seed=0, n_x=30, n_s=4)\nprint(f\"simulated value premium, equal phi : {value_growth(sim_eq).premium:5.2f}%\")\nprint(f\"simulated value premium, Table II  : {value_growth(sim).premium:5.2f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsimulated value premium, equal phi :  0.03%\nsimulated value premium, Table II  :  5.38%\n```\n:::\n:::\n\n\nThe premium falls from 5.38 to 0.03 percent, and the household never\nchanged. The leftover three basis points reflect value's remaining\nparameter differences (its $\\varphi_\\sigma$ and $\\alpha$ terms)\ntogether with 300-sample noise. The value premium in the model is the\nprice of one measured cash-flow characteristic, and removing the\ncharacteristic removes the premium.\n\n## Robustness: varying one parameter at a time\n\nThe cell below varies one parameter at a time and re-solves. It\nrecords the analytical long-run compensation of the market and the\nvalue-growth spread, meaning the parts of each premium that come from\nnews about $x_t$, because the mechanism works through those parts:\n\n::: {#f1e8abab .cell execution_count=7}\n``` {.python .cell-code code-fold=\"true\"}\ngrids = {\n    \"rho\": (\"persistence of x_t\", [0.95, 0.98, 0.99]),\n    \"psi\": (\"EIS\", [1.2, 1.5, 2.0]),\n    \"gamma\": (\"risk aversion\", [5.0, 10.0, 15.0]),\n    \"phi_value\": (\"value loading\", [5.0, 6.2, 7.4]),\n    \"phi_growth\": (\"growth loading\", [2.0, 2.6, 3.2]),\n}\nrows = []\nfor attr, (label, values) in grids.items():\n    for v in values:\n        if attr in (\"rho\", \"psi\", \"gamma\"):\n            variant = model.replace(**{attr: v})\n        else:\n            claim = attr.removeprefix(\"phi_\")\n            variant = model.replace(claims={claim: {\"phi\": v}})\n        res = variant.solve(method=\"analytical\")\n        rows.append({\"parameter\": label, \"value\": v,\n                     \"market\": res.long_run_premium[\"market\"],\n                     \"spread\": value_growth(res).premium})\n\n(\n    GT(pd.DataFrame(rows), rowname_col=\"value\", groupname_col=\"parameter\")\n    .tab_header(title=\"Long-run premia, one parameter at a time\")\n    .cols_label(market=\"market x-premium %\", spread=\"value-growth spread %\")\n    .fmt_number(columns=[\"market\", \"spread\"], decimals=2)\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div id=\"mpjsiudvfj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#mpjsiudvfj table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#mpjsiudvfj thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#mpjsiudvfj p { margin: 0; padding: 0; }\n #mpjsiudvfj .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #mpjsiudvfj .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #mpjsiudvfj .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #mpjsiudvfj .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #mpjsiudvfj .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #mpjsiudvfj .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #mpjsiudvfj .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #mpjsiudvfj .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #mpjsiudvfj .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #mpjsiudvfj .gt_column_spanner_outer:first-child { padding-left: 0; }\n #mpjsiudvfj .gt_column_spanner_outer:last-child { padding-right: 0; }\n #mpjsiudvfj .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #mpjsiudvfj .gt_spanner_row { border-bottom-style: hidden; }\n #mpjsiudvfj .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #mpjsiudvfj .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #mpjsiudvfj .gt_from_md> :first-child { margin-top: 0; }\n #mpjsiudvfj .gt_from_md> :last-child { margin-bottom: 0; }\n #mpjsiudvfj .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #mpjsiudvfj .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #mpjsiudvfj .gt_indent_1 { text-indent: 5px; }\n #mpjsiudvfj .gt_indent_2 { text-indent: calc(5px * 2); }\n #mpjsiudvfj .gt_indent_3 { text-indent: calc(5px * 3); }\n #mpjsiudvfj .gt_indent_4 { text-indent: calc(5px * 4); }\n #mpjsiudvfj .gt_indent_5 { text-indent: calc(5px * 5); }\n #mpjsiudvfj .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #mpjsiudvfj .gt_row_group_first td { border-top-width: 2px; }\n #mpjsiudvfj .gt_row_group_first th { border-top-width: 2px; }\n #mpjsiudvfj .gt_striped { color: #333333; background-color: #F4F4F4; }\n #mpjsiudvfj .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #mpjsiudvfj .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #mpjsiudvfj .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #mpjsiudvfj .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #mpjsiudvfj .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #mpjsiudvfj .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #mpjsiudvfj .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #mpjsiudvfj .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #mpjsiudvfj .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #mpjsiudvfj .gt_left { text-align: left; }\n #mpjsiudvfj .gt_center { text-align: center; }\n #mpjsiudvfj .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #mpjsiudvfj .gt_font_normal { font-weight: normal; }\n #mpjsiudvfj .gt_font_bold { font-weight: bold; }\n #mpjsiudvfj .gt_font_italic { font-style: italic; }\n #mpjsiudvfj .gt_super { font-size: 65%; }\n #mpjsiudvfj .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #mpjsiudvfj .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #mpjsiudvfj .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #mpjsiudvfj .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #mpjsiudvfj .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #mpjsiudvfj .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\">Long-run premia, one parameter at a time</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"\"></th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"market\">market x-premium %</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"spread\">value-growth spread %</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr class=\"gt_group_heading_row\">\n    <th class=\"gt_group_heading\" colspan=\"3\">persistence of x_t</th>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">0.95</th>\n    <td class=\"gt_row gt_right\">0.14</td>\n    <td class=\"gt_row gt_right\">0.19</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">0.98</th>\n    <td class=\"gt_row gt_right\">0.34</td>\n    <td class=\"gt_row gt_right\">0.40</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">0.99</th>\n    <td class=\"gt_row gt_right\">0.51</td>\n    <td class=\"gt_row gt_right\">0.55</td>\n  </tr>\n  <tr class=\"gt_group_heading_row\">\n    <th class=\"gt_group_heading\" colspan=\"3\">EIS</th>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">1.2</th>\n    <td class=\"gt_row gt_right\">0.31</td>\n    <td class=\"gt_row gt_right\">0.41</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">1.5</th>\n    <td class=\"gt_row gt_right\">0.34</td>\n    <td class=\"gt_row gt_right\">0.40</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">2.0</th>\n    <td class=\"gt_row gt_right\">0.37</td>\n    <td class=\"gt_row gt_right\">0.40</td>\n  </tr>\n  <tr class=\"gt_group_heading_row\">\n    <th class=\"gt_group_heading\" colspan=\"3\">risk aversion</th>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">5.0</th>\n    <td class=\"gt_row gt_right\">0.16</td>\n    <td class=\"gt_row gt_right\">0.19</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">10.0</th>\n    <td class=\"gt_row gt_right\">0.34</td>\n    <td class=\"gt_row gt_right\">0.40</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">15.0</th>\n    <td class=\"gt_row gt_right\">0.52</td>\n    <td class=\"gt_row gt_right\">0.62</td>\n  </tr>\n  <tr class=\"gt_group_heading_row\">\n    <th class=\"gt_group_heading\" colspan=\"3\">value loading</th>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">5.0</th>\n    <td class=\"gt_row gt_right\">0.34</td>\n    <td class=\"gt_row gt_right\">0.23</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">6.2</th>\n    <td class=\"gt_row gt_right\">0.34</td>\n    <td class=\"gt_row gt_right\">0.40</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">7.4</th>\n    <td class=\"gt_row gt_right\">0.34</td>\n    <td class=\"gt_row gt_right\">0.58</td>\n  </tr>\n  <tr class=\"gt_group_heading_row\">\n    <th class=\"gt_group_heading\" colspan=\"3\">growth loading</th>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">2.0</th>\n    <td class=\"gt_row gt_right\">0.34</td>\n    <td class=\"gt_row gt_right\">0.52</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">2.6</th>\n    <td class=\"gt_row gt_right\">0.34</td>\n    <td class=\"gt_row gt_right\">0.40</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">3.2</th>\n    <td class=\"gt_row gt_right\">0.34</td>\n    <td class=\"gt_row gt_right\">0.28</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\nThe spread is positive at every grid point. Its size scales with the\npersistence of $x_t$ (0.19 to 0.55 across $\\rho$ from 0.95 to 0.99),\nwith risk aversion (0.19 to 0.62), and with the gap between the\nloadings, and it barely moves with the EIS. The pattern matches the\ntheory. Persistence and risk aversion govern the price of long-run\nnews, and the loading gap governs the quantity. The EIS mostly\nreallocates between the premium and the level of rates. The ordering\ndoes not flip anywhere in the ranges tested.\n\n## How much of the magnitude is the method?\n\n::: {.callout-warning title=\"The grid size affects the printed numbers\"}\nThe paper's Table VII, and the cells above, solve on a 30-point grid\nfor $x_t$. The cell below re-solves on finer grids, with the same\ncalibration and the same seed:\n\n::: {#185e9177 .cell execution_count=8}\n``` {.python .cell-code code-fold=\"true\"}\ngrid_rows = []\nfor n_x in (30, 60, 100):\n    t = model.simulate(n_samples=300, years=74, seed=0, n_x=n_x, n_s=4)\n    c = value_growth(t)\n    grid_rows.append({\"n_x\": n_x, \"vp\": c.premium,\n                      \"rf\": t.risk_free, \"ratio\": c.beta_ratio})\n\n(\n    GT(pd.DataFrame(grid_rows))\n    .tab_header(title=\"The same simulation on finer grids\")\n    .cols_label(n_x=\"x-grid size\", vp=\"value premium %\",\n                rf=\"risk-free rate %\", ratio=\"beta ratio\")\n    .fmt_number(columns=[\"vp\", \"rf\", \"ratio\"], decimals=2)\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div id=\"buyfwvhmat\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#buyfwvhmat table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#buyfwvhmat thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#buyfwvhmat p { margin: 0; padding: 0; }\n #buyfwvhmat .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #buyfwvhmat .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #buyfwvhmat .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #buyfwvhmat .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #buyfwvhmat .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #buyfwvhmat .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #buyfwvhmat .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #buyfwvhmat .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #buyfwvhmat .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #buyfwvhmat .gt_column_spanner_outer:first-child { padding-left: 0; }\n #buyfwvhmat .gt_column_spanner_outer:last-child { padding-right: 0; }\n #buyfwvhmat .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #buyfwvhmat .gt_spanner_row { border-bottom-style: hidden; }\n #buyfwvhmat .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #buyfwvhmat .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #buyfwvhmat .gt_from_md> :first-child { margin-top: 0; }\n #buyfwvhmat .gt_from_md> :last-child { margin-bottom: 0; }\n #buyfwvhmat .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #buyfwvhmat .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #buyfwvhmat .gt_indent_1 { text-indent: 5px; }\n #buyfwvhmat .gt_indent_2 { text-indent: calc(5px * 2); }\n #buyfwvhmat .gt_indent_3 { text-indent: calc(5px * 3); }\n #buyfwvhmat .gt_indent_4 { text-indent: calc(5px * 4); }\n #buyfwvhmat .gt_indent_5 { text-indent: calc(5px * 5); }\n #buyfwvhmat .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #buyfwvhmat .gt_row_group_first td { border-top-width: 2px; }\n #buyfwvhmat .gt_row_group_first th { border-top-width: 2px; }\n #buyfwvhmat .gt_striped { color: #333333; background-color: #F4F4F4; }\n #buyfwvhmat .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #buyfwvhmat .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #buyfwvhmat .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #buyfwvhmat .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #buyfwvhmat .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #buyfwvhmat .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #buyfwvhmat .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #buyfwvhmat .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #buyfwvhmat .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #buyfwvhmat .gt_left { text-align: left; }\n #buyfwvhmat .gt_center { text-align: center; }\n #buyfwvhmat .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #buyfwvhmat .gt_font_normal { font-weight: normal; }\n #buyfwvhmat .gt_font_bold { font-weight: bold; }\n #buyfwvhmat .gt_font_italic { font-style: italic; }\n #buyfwvhmat .gt_super { font-size: 65%; }\n #buyfwvhmat .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #buyfwvhmat .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #buyfwvhmat .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #buyfwvhmat .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #buyfwvhmat .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #buyfwvhmat .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\">The same simulation on finer grids</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_x\">x-grid size</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"vp\">value premium %</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rf\">risk-free rate %</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ratio\">beta ratio</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_right\">30</td>\n    <td class=\"gt_row gt_right\">5.38</td>\n    <td class=\"gt_row gt_right\">1.04</td>\n    <td class=\"gt_row gt_right\">0.81</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">60</td>\n    <td class=\"gt_row gt_right\">4.03</td>\n    <td class=\"gt_row gt_right\">1.82</td>\n    <td class=\"gt_row gt_right\">0.91</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">100</td>\n    <td class=\"gt_row gt_right\">3.64</td>\n    <td class=\"gt_row gt_right\">1.84</td>\n    <td class=\"gt_row gt_right\">0.88</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\nRefining the grid moves the numbers. The premium prints 5.38 at 30\npoints, 4.03 at 60, and 3.64 at 100. The safe rate rises to 1.82 and\n1.84, closer to the paper's 1.58 print than the 30-point run, and the\nbeta ratio moves to 0.91 at 60 points, next to the paper's own 0.92. A\ncoarse grid overstates the dispersion of long-run growth states, and\nwith it the premium, so part of the size of the 5.3 reflects the\n30-point discretization the paper and the page share. The refinement\nleaves the qualitative results in place. The spread stays large and\npositive, and value stays cheaper. Value's beta stays below growth's\nwhile its return stays far higher. The mechanism is robust to the\ngrid, and the exact level is not. Read the numbers on the page as what\nthe 30-point grid prints, not as the model's last decimal.\n:::\n\n## What has been shown\n\nSummarize Parts I through IV. The complaint in\n[Chapter 1](01-two-free-numbers.qmd) was that a DCF has two free\nnumbers, so it fits any premium. The CAPM, in turn, could not fit the\nvalue premium in the data. The replacement was one household,\ncalibrated to consumption, pricing every claim through one Euler\nequation. Each claim brought only measured cash-flow parameters, and\nreturns entered nothing. The same solve then produced:\n\n- a market premium near eight percent at the data's valuation level\n  ([Chapter 9](09-the-market-test.qmd));\n- a value premium of 5.38 percent against roughly six in the data,\n  with the valuation ranking value < market < growth;\n- a CAPM beta for value below growth's, so the model generates the\n  anomaly itself, because beta is the wrong summary of three priced\n  risks;\n- a premium that falls to 0.03 percent the moment value's one\n  distinguishing loading is equalized.\n\nUnder the model's accounting, the value premium is not a puzzle. It is\nthe price of holding cash flows that do badly exactly when news about\nlong-run growth is bad. The risk is measured in dividends, and the\ncompensation is paid in returns.\n\n## Takeaways\n\n- With nothing re-tuned, the simulated Table VII prints a value premium\n  of 5.38 percent (paper: 5.3; data: about 6) and the data's valuation\n  ranking, with value the cheapest and growth the most expensive.\n- The model reproduces the CAPM anomaly. Value's beta prints 0.72\n  against growth's 0.90 (ratio 0.81; paper 0.92) while value earns five\n  points more. A one-factor projection mixes three separately priced\n  risks, and long-run growth news carries about 85 percent of the\n  spread in the paper's decomposition.\n- Equalize the long-run loadings and the simulated premium collapses\n  from 5.38 to 0.03 percent. The analytical spread's $-0.12$ residual\n  is an artifact of the linearization anchors, not a priced risk.\n- The mechanism survives every point of the robustness grid, but the\n  magnitude depends on the method. Finer grids print a smaller premium\n  (3.64 at $n_x = 100$) and the paper's beta ratio. Trust the ordering\n  and the channel, and treat the exact level as uncertain.\n\n::: {.callout-note collapse=\"true\" title=\"Recall\"}\n\nAnswer from memory before opening.\n\n1. With nothing re-tuned, what premium does the model print, against\n   what data fact?\n2. State the CAPM anomaly the model reproduces.\n3. What happens to the simulated premium when the two long-run loadings\n   are equalized?\n\n**Answers.**\n\n1. 5.38 percent, against about six points in the data (the paper prints\n   5.3).\n2. Value's beta is below growth's (0.72 against 0.90) while value earns\n   five points more.\n3. It collapses, from 5.38 to about zero.\n\n:::\n\n## Exercises\n\n1. Rerun the equal-$\\phi$ counterfactual, but instead of lowering\n   value's loading, raise growth's to 6.2. What does the simulated\n   premium print, and why is the market row now mispriced relative to\n   Chapter 9?\n2. Using the robustness grid, find the combination in the tested ranges\n   that produces the largest long-run spread. Which two parameters\n   interact, and what does the interaction say about where the model is\n   most vulnerable to calibration error?\n3. Set `n_s=6` in the convergence cell (volatility grid) and re-solve at\n   `n_x=60`. Does refining the volatility dimension move the premium as\n   much as refining the $x$ dimension did? What does the result tell\n   you about which state variable is harder to discretize accurately?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n::: {#5e7d2232 .cell execution_count=9}\n``` {.python .cell-code code-fold=\"true\"}\n# Exercise 1: raise growth's loading instead\nt_hi = model.replace(claims={\"growth\": {\"phi\": 6.2}}).simulate(\n    n_samples=300, years=74, seed=0, n_x=30, n_s=4)\nprint(f\"premium with both phi = 6.2: {value_growth(t_hi).premium:.2f}\")\nprint(f\"market E[R]: {t_hi.expected_returns['market']:.2f} \"\n      f\"(Table VII chapter: {sim.expected_returns['market']:.2f})\")\n\n# Exercise 2: the largest spread in the one-at-a-time grid\nprint(pd.DataFrame(rows).sort_values(\"spread\", ascending=False).head(3))\n\n# Exercise 3: refining the volatility dimension at n_x = 60\nt6 = model.simulate(n_samples=300, years=74, seed=0, n_x=60, n_s=6)\nprint(f\"vp, n_x=60 n_s=4: {grid_rows[1]['vp']:.2f}\")\nprint(f\"vp, n_x=60 n_s=6: {value_growth(t6).premium:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npremium with both phi = 6.2: 0.10\nmarket E[R]: 8.93 (Table VII chapter: 8.93)\n             parameter  value    market    spread\n8        risk aversion  15.00  0.518214  0.618366\n11       value loading   7.40  0.337442  0.575295\n2   persistence of x_t   0.99  0.507099  0.546913\nvp, n_x=60 n_s=4: 4.03\nvp, n_x=60 n_s=6: 3.94\n```\n:::\n:::\n\n\nEqualizing from above kills the value premium just as equalizing from\nbelow did (0.10 percent), and the market row is untouched at 8.93\nbecause the market's own cash-flow process never moved. The cross-section\nbreaks while the aggregate stays put. The biggest spread in the tested\nranges sits at the highest risk aversion (0.62 at gamma = 15), with the\nhigh value loading and high persistence just behind, and all three scale\nthe price or the quantity of long-run news.\nRefining the volatility grid at n_x = 60 barely moves the premium next to\nrefining the x grid, so x is the state that is hard to discretize.\n\n:::\n\n::: {.firewall}\n**Where each number comes from.** Data numbers are printed by the first\ncell from `data/annual_panel.csv`. Every model number is printed by\n`model.simulate(n_samples=300, seed=0)` or by\n`model.solve(method=\"analytical\")` on `lrr.LongRunRisksModel()`, which\nis the Table II calibration, including the equal-$\\phi$\ncounterfactual, the robustness grid, and the grid refinement cell. The\n5.3, the 0.92, the decomposition in footnote 10, and the 3.10/3.24/3.65\nvaluations are the paper's prints. Download the chapter as a notebook\n(top of the page) to rerun everything.\n:::\n\n::: {.callout-note title=\"Where to go next\"}\nThe canonical treatment of this chapter's topic is Kiku (2006), the cross-section section, with Bansal and Yaron (2004) for the model class\n([references](../reference/references.qmd)). Stuck, or spot an\nerror? Open an issue at the\n[repository](https://github.com/tlorans/kiku-value-premium-replication/issues), or ask your agent to walk through it with\nyou.\n:::\n\n",
    "supporting": [
      "10-value-premium-resolved_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}