{
  "hash": "8044bba39ae0531e25466386b1ca157c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"10. The value premium, resolved\"\naliases: [/cross-section.html]\n---\n\nNothing has been re-tuned since\n[Chapter 8](08-calibrating-cash-flows.qmd). The household, the\nconsumption process, and the Euler equation are the same ones that\njust priced the market in [Chapter 9](09-the-market-test.qmd). A model\nthat needed a new discount rate for every asset would repeat the DCF's\nproblem. The only thing that distinguishes the value claim from the\ngrowth claim inside the model is the set of cash-flow parameters each\nbrought from [Chapter 8](08-calibrating-cash-flows.qmd), and above all\nvalue's dividend loading on long-run consumption news, $\\phi_V = 6.2$,\nagainst growth's $\\phi_G = 2.6$.\n\nThe chapter asks the model for four results at once:\n\n- the six-point return spread between value and growth;\n- the valuation ranking, in which value trades cheaper than growth;\n- the CAPM anomaly, in which value's market beta fails to explain its\n  premium inside the model the way it fails in the data;\n- a counterfactual, in which setting value's long-run loading equal to\n  growth's removes the premium.\n\nIf the beta anomaly does not appear, the model has explained some\nother economy. If the premium survives the counterfactual, something\nother than the loading was doing the work.\n\n## The facts to be explained\n\n::: {#bd35c0e2 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\n# Data bootstrap: use the repo's committed CSVs, or fetch them when this\n# notebook runs outside the repository.\nfrom pathlib import Path\nimport urllib.request\n\nDATA = Path(\"../../data\")\nif not DATA.exists():\n    DATA = Path(\"data\")\n    DATA.mkdir(exist_ok=True)\n    base = (\"https://raw.githubusercontent.com/tlorans/\"\n            \"kiku-value-premium-replication/main/data/\")\n    for f in (\"annual_panel.csv\", \"consumption_annual.csv\", \"rf_annual.csv\"):\n        if not (DATA / f).exists():\n            urllib.request.urlretrieve(base + f, DATA / f)\n```\n:::\n\n\n::: {#fd25b560 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport lrrcs as lrr\n\npanel = pd.read_csv(DATA / \"annual_panel.csv\")\nmeans = {c: float(panel[panel[\"claim\"] == c][\"ret\"].mean() * 100)\n         for c in (\"Growth\", \"Value\", \"Market\")}\nprint({c: round(v, 2) for c, v in means.items()},\n      \" spread:\", round(means[\"Value\"] - means[\"Growth\"], 2))\n\nrm = panel[panel[\"claim\"] == \"Market\"].sort_values(\"year\")[\"ret\"].to_numpy()\nrm_d = rm - rm.mean()\nfor c in (\"Growth\", \"Value\"):\n    r = panel[panel[\"claim\"] == c].sort_values(\"year\")[\"ret\"].to_numpy()\n    print(f\"CAPM beta, {c.lower():6s}: \"\n          f\"{float(rm_d @ (r - r.mean()) / (rm_d @ rm_d)):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n{'Growth': 7.49, 'Value': 13.67, 'Market': 8.52}  spread: 6.18\nCAPM beta, growth: 0.95\nCAPM beta, value : 1.28\n```\n:::\n:::\n\n\nValue out-earns growth by 6.18 percentage points a year on the\nreconstruction used here (the paper's vintage prints 13.88 against\n7.81, a 6.07 spread). The CAPM cannot explain a spread of six points\nwith the estimated betas. The betas are 1.28 against 0.95 here, and\nwith the market earning 8.52 the beta gap prices a spread of roughly\n$(1.28 - 0.95) \\times 8.5 \\approx 2.8$ points, which is less than half\nof the spread in the data. On the paper's vintage both betas sit near\n1.03, where the CAPM predicts no spread at all. Value also trades\ncheaper than growth in almost every year, as the figure below shows.\n\n::: {#a1c62539 .cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\"}\nimport matplotlib\nmatplotlib.use(\"Agg\")\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots(figsize=(6.5, 3.4))\nfor claim, color in ((\"Growth\", \"#1b1714\"), (\"Value\", \"#7a1f1f\")):\n    sub = panel[panel[\"claim\"] == claim].sort_values(\"year\")\n    ax.plot(sub[\"year\"], np.log(sub[\"pd\"]), color=color, lw=1.3,\n            label=claim.lower())\nax.set_xlabel(\"year\")\nax.set_ylabel(\"log(P/D)\")\nax.set_ylim(2.2, 4.6)\nax.legend(frameon=False, fontsize=9)\nax.spines[[\"top\", \"right\"]].set_visible(False)\nfig.tight_layout()\nplt.show()\n```\n:::\n\n\n## The model's Table VII\n\nSolve on the paper's grid and simulate the paper's object, meaning\nhundreds of 74-year samples with statistics estimated sample by sample\nand then averaged ([Chapter 9](09-the-market-test.qmd) explained why\nsample statistics are the right comparison). The code path, seed, and\ngrid are the same as in the market test, and the value and growth rows\nsimply come along:\n\n::: {#154d659f .cell execution_count=4}\n``` {.python .cell-code}\nparams = lrr.get_table_ii_params()\nsolver = lrr.ModelSolver(params, n_x=30, n_s=4).solve()\ntab = lrr.simulate_table_vii(solver, n_samples=300, years=74, seed=0)\nlrr.print_table_vii(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n====================================================================\nTable VII by simulation (300 samples x 74 years, annual data)\n====================================================================\nRisk-free rate :   1.04 %  (SE 0.62)\nValue premium  :   5.38 %\nCAPM beta ratio (value/growth): 0.81\n\nPortfolio    E[R] %   (SE)   Vol %  Sharpe   beta     P/D  log P/D\n------------------------------------------------------------------\ngrowth         7.94   3.35   21.63    0.32   0.90    25.7     3.19\nvalue         13.32   4.96   25.61    0.48   0.72    20.1     2.81\nmarket         8.93   3.25   19.68    0.40   1.00    21.4     3.01\n```\n:::\n:::\n\n\nWalk through what the block prints, fact by fact.\n\n**The premium.** The simulated value premium is 5.38 percent, and the\npaper's Table VII prints 5.3 on 1,000 samples. The data show roughly\nsix (6.18 on the reconstruction, 6.07 on the paper's vintage). Value\nearns 13.32 against the data's 13.67, and growth earns 7.94 against\n7.49. The cross-sample dispersions (4.96 and 3.35) say a 74-year\nsample from the model economy routinely strays a few points from the\nreported means, and the data column is one such sample. No return was\ntargeted anywhere in the calibration, so the spread comes entirely\nfrom $\\phi_V - \\phi_G$ and the pricing framework of Chapters 4 to 7.\n\n**The valuation ranking.** Mean log P/D prints 2.81 for value, 3.01\nfor the market, and 3.19 for growth (the paper prints 3.10, 3.24, and\n3.65 on the same ranking). Value is cheapest and growth is dearest,\nwhich is the data's ordering. The claim that earns more is the claim\nthat costs less, because the long-run loading drives both. A high\n$\\phi$ makes dividends riskier in the state investors fear, so the\nprice is low and the expected return is high. A DCF treats the\nvaluation discount and the return premium as two separate numbers,\nwhile the model derives both from the same loading.\n\n**The CAPM anomaly, reproduced inside the model.** In the beta column,\nvalue's CAPM beta prints 0.72, below growth's 0.90, while value's mean\nreturn is more than five points higher. The beta ratio is 0.81 (the\npaper prints 0.92, and both vintages of the data put the ratio near or\nabove one). The model reproduces the very anomaly that\n[Chapter 1](01-two-free-numbers.qmd) used to argue against the CAPM.\nIt can do so because a single market beta is a one-factor projection\nof three separately priced risks, namely short-run consumption shocks,\nlong-run growth news, and volatility news\n([Chapter 6](06-log-linear-solution.qmd)), and the projection mixes\nthem together. Value loads heavily on long-run news, which is\nexpensive per unit of return covariance. Growth's return covaries\nstrongly with the market, because growth is a long-duration claim and\nis sensitive to discount rates, while carrying little of the priced\ncash-flow risk. In the paper's decomposition (its footnote 10), the\n5.3-point spread splits into roughly $-0.6$ from short-run risk,\n$+4.6$ from long-run growth risk, and $+1.3$ from volatility risk.\nAbout 85 percent of the premium comes from the long-run channel, and\nabout a quarter comes from volatility. The three parts sum past 100\npercent because the short-run piece is negative. A beta regression\ncaptures only the sum of the covariances and prices none of the parts.\n\n## The counterfactual: set the loadings equal\n\nIf the explanation is right, the premium depends on one input. Set\nvalue's long-run loading equal to growth's 2.6; leave everything else\nalone, including value's volatility loading $\\varphi_\\sigma$ and its\nshort-run correlation $\\alpha$; then re-solve. First, compute the\nanalytical long-run compensation of\n[Chapter 6](06-log-linear-solution.qmd):\n\n::: {#7452ca2f .cell execution_count=5}\n``` {.python .cell-code}\nimport copy\n\nparams_eq = copy.deepcopy(params)\nparams_eq.dividends[\"value\"].phi = params.dividends[\"growth\"].phi  # 2.6\nlrr.print_long_short_premium(lrr.solve_analytical(params_eq))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nApproximate annualized long-run risk premia:\n  growth  :   0.39%\n  value   :   0.28%\n  market  :   0.34%\nValue-growth spread from long-run risks: -0.12%\nA1 (PD elasticity to x): growth=43.1, value=31.1\nPrice of long-run risk Lambda_eps = 5.95\n```\n:::\n:::\n\n\nThe 0.40 percent long-run spread of the baseline collapses, but the\nprint is $-0.12$ percent, not exactly zero. The residual has a\nmechanical explanation. The analytical formula linearizes each claim\naround its own sample-average valuation\n([Chapter 6](06-log-linear-solution.qmd)), and value's anchor (mean log\nP/D of 3.10) differs from growth's (3.65) because the claims still\ndiffer in their other cash-flow parameters, namely $\\mu_d$,\n$\\varphi_\\sigma$, and $\\alpha$. Different anchors give different\nlinearization slopes ($A_1$ of 31.1 against 43.1) even at identical\n$\\phi$, so a small artifact of the approximation survives. The full\nEuler-equation simulation has no linearization anchor, so ask it the\nsame question:\n\n::: {#dda1496e .cell execution_count=6}\n``` {.python .cell-code}\nsolver_eq = lrr.ModelSolver(params_eq, n_x=30, n_s=4).solve()\ntab_eq = lrr.simulate_table_vii(solver_eq, n_samples=300, years=74, seed=0)\nprint(f\"simulated value premium, equal phi : {tab_eq['value_premium']:5.2f}%\")\nprint(f\"simulated value premium, Table II  : {tab['value_premium']:5.2f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsimulated value premium, equal phi :  0.03%\nsimulated value premium, Table II  :  5.38%\n```\n:::\n:::\n\n\nThe premium falls from 5.38 to 0.03 percent, and the household never\nchanged. The leftover three basis points reflect value's remaining\nparameter differences (its $\\varphi_\\sigma$ and $\\alpha$ terms)\ntogether with 300-sample noise. The value premium in the model is the\nprice of one measured cash-flow characteristic, and removing the\ncharacteristic removes the premium.\n\n## Robustness: varying one parameter at a time\n\nThe cell below varies one parameter at a time and re-solves. It\nrecords the analytical long-run compensation of the market and the\nvalue-growth spread, meaning the parts of each premium that come from\nnews about $x_t$, because the mechanism works through those parts:\n\n::: {#dc84d0a2 .cell execution_count=7}\n``` {.python .cell-code code-fold=\"true\"}\ndef lr_spread(p):\n    sol = lrr.solve_analytical(p)\n    return (sol.premium_lr[\"market\"] * 100,\n            (sol.premium_lr[\"value\"] - sol.premium_lr[\"growth\"]) * 100)\n\ngrids = {\n    \"rho\": (\"persistence of x_t\", [0.95, 0.98, 0.99]),\n    \"psi\": (\"EIS\", [1.2, 1.5, 2.0]),\n    \"gamma\": (\"risk aversion\", [5.0, 10.0, 15.0]),\n    \"phi_value\": (\"value loading\", [5.0, 6.2, 7.4]),\n    \"phi_growth\": (\"growth loading\", [2.0, 2.6, 3.2]),\n}\nfor attr, (label, values) in grids.items():\n    print(label)\n    for v in values:\n        p = copy.deepcopy(params)\n        if attr == \"rho\":\n            p.cons.rho = v\n        elif attr == \"psi\":\n            p.prefs.psi = v\n        elif attr == \"gamma\":\n            p.prefs.gamma = v\n        else:\n            p.dividends[attr.removeprefix(\"phi_\")].phi = v\n        market, spread = lr_spread(p)\n        print(f\"  {label} = {v:<5} market x-premium {market:5.2f}%   \"\n              f\"value-growth spread {spread:5.2f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npersistence of x_t\n  persistence of x_t = 0.95  market x-premium  0.14%   value-growth spread  0.19%\n  persistence of x_t = 0.98  market x-premium  0.34%   value-growth spread  0.40%\n  persistence of x_t = 0.99  market x-premium  0.51%   value-growth spread  0.55%\nEIS\n  EIS = 1.2   market x-premium  0.31%   value-growth spread  0.41%\n  EIS = 1.5   market x-premium  0.34%   value-growth spread  0.40%\n  EIS = 2.0   market x-premium  0.37%   value-growth spread  0.40%\nrisk aversion\n  risk aversion = 5.0   market x-premium  0.16%   value-growth spread  0.19%\n  risk aversion = 10.0  market x-premium  0.34%   value-growth spread  0.40%\n  risk aversion = 15.0  market x-premium  0.52%   value-growth spread  0.62%\nvalue loading\n  value loading = 5.0   market x-premium  0.34%   value-growth spread  0.23%\n  value loading = 6.2   market x-premium  0.34%   value-growth spread  0.40%\n  value loading = 7.4   market x-premium  0.34%   value-growth spread  0.58%\ngrowth loading\n  growth loading = 2.0   market x-premium  0.34%   value-growth spread  0.52%\n  growth loading = 2.6   market x-premium  0.34%   value-growth spread  0.40%\n  growth loading = 3.2   market x-premium  0.34%   value-growth spread  0.28%\n```\n:::\n:::\n\n\nThe spread is positive at every grid point. Its size scales with the\npersistence of $x_t$ (0.19 to 0.55 across $\\rho$ from 0.95 to 0.99),\nwith risk aversion (0.19 to 0.62), and with the gap between the\nloadings, and it barely moves with the EIS. The pattern matches the\ntheory. Persistence and risk aversion govern the price of long-run\nnews, and the loading gap governs the quantity. The EIS mostly\nreallocates between the premium and the level of rates. The ordering\ndoes not flip anywhere in the ranges tested.\n\n## How much of the magnitude is the method?\n\n::: {.callout-warning title=\"The grid size affects the printed numbers\"}\nThe paper's Table VII, and the cells above, solve on a 30-point grid\nfor $x_t$. The cell below re-solves on finer grids, with the same\ncalibration and the same seed:\n\n::: {#4def125a .cell execution_count=8}\n``` {.python .cell-code code-fold=\"true\"}\nfor n_x in (30, 60, 100):\n    s = lrr.ModelSolver(params, n_x=n_x, n_s=4).solve()\n    t = lrr.simulate_table_vii(s, n_samples=300, years=74, seed=0)\n    print(f\"n_x = {n_x:>3}: value premium {t['value_premium']:.2f}%, \"\n          f\"rf {t['mean_rf']:.2f}%, beta ratio {t['beta_ratio']:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nn_x =  30: value premium 5.38%, rf 1.04%, beta ratio 0.81\nn_x =  60: value premium 4.03%, rf 1.82%, beta ratio 0.91\nn_x = 100: value premium 3.64%, rf 1.84%, beta ratio 0.88\n```\n:::\n:::\n\n\nRefining the grid moves the numbers. The premium prints 5.38 at 30\npoints, 4.03 at 60, and 3.64 at 100. The safe rate rises to 1.82 and\n1.84, closer to the paper's 1.58 print than the 30-point run, and the\nbeta ratio moves to 0.91 at 60 points, next to the paper's own 0.92. A\ncoarse grid overstates the dispersion of long-run growth states, and\nwith it the premium, so part of the size of the 5.3 reflects the\n30-point discretization the paper and the page share. The refinement\nleaves the qualitative results in place. The spread stays large and\npositive, and value stays cheaper. Value's beta stays below growth's\nwhile its return stays far higher. The mechanism is robust to the\ngrid, and the exact level is not. Read the numbers on the page as what\nthe 30-point grid prints, not as the model's last decimal.\n:::\n\n## What has been shown\n\nSummarize Parts I through IV. The complaint in\n[Chapter 1](01-two-free-numbers.qmd) was that a DCF has two free\nnumbers, so it fits any premium. The CAPM, in turn, could not fit the\nvalue premium in the data. The replacement was one household,\ncalibrated to consumption, pricing every claim through one Euler\nequation. Each claim brought only measured cash-flow parameters, and\nreturns entered nothing. The same solve then produced:\n\n- a market premium near eight percent at the data's valuation level\n  ([Chapter 9](09-the-market-test.qmd));\n- a value premium of 5.38 percent against roughly six in the data,\n  with the valuation ranking value < market < growth;\n- a CAPM beta for value below growth's, so the model generates the\n  anomaly itself, because beta is the wrong summary of three priced\n  risks;\n- a premium that falls to 0.03 percent the moment value's one\n  distinguishing loading is equalized.\n\nUnder the model's accounting, the value premium is not a puzzle. It is\nthe price of holding cash flows that do badly exactly when news about\nlong-run growth is bad. The risk is measured in dividends, and the\ncompensation is paid in returns.\n\n## Takeaways\n\n- With nothing re-tuned, the simulated Table VII prints a value premium\n  of 5.38 percent (paper: 5.3; data: about 6) and the data's valuation\n  ranking, value cheapest and growth dearest.\n- The model reproduces the CAPM anomaly. Value's beta prints 0.72\n  against growth's 0.90 (ratio 0.81; paper 0.92) while value earns five\n  points more. A one-factor projection mixes three separately priced\n  risks, and long-run growth news carries about 85 percent of the\n  spread in the paper's decomposition.\n- Equalize the long-run loadings and the simulated premium collapses\n  from 5.38 to 0.03 percent. The analytical spread's $-0.12$ residual\n  is an artifact of the linearization anchors, not a priced risk.\n- The mechanism survives every point of the robustness grid, but the\n  magnitude depends on the method. Finer grids print a smaller premium\n  (3.64 at $n_x = 100$) and the paper's beta ratio. Trust the ordering\n  and the channel, and treat the exact level as uncertain.\n\n## Exercises\n\n1. Rerun the equal-$\\phi$ counterfactual, but instead of lowering\n   value's loading, raise growth's to 6.2. What does the simulated\n   premium print, and why is the market row now mispriced relative to\n   Chapter 9?\n2. Using the robustness grid, find the combination in the tested ranges\n   that produces the largest long-run spread. Which two parameters\n   interact, and what does the interaction say about where the model is\n   most vulnerable to calibration error?\n3. Set `n_s=6` in the convergence cell (volatility grid) and re-solve at\n   `n_x=60`. Does refining the volatility dimension move the premium as\n   much as refining the $x$ dimension did? What does the result tell\n   you about which state variable is harder to discretize accurately?\n\n::: {.firewall}\n**Where each number comes from.** Data numbers are printed by the first\ncell from `data/annual_panel.csv`. Every model number is printed by\n`ModelSolver` + `simulate_table_vii` (300 samples, seed 0) or\n`solve_analytical` on `get_table_ii_params`, including the equal-$\\phi$\ncounterfactual, the robustness grid, and the grid refinement cell. The\n5.3, the 0.92, the decomposition in footnote 10, and the 3.10/3.24/3.65\nvaluations are the paper's prints. Download the chapter as a notebook\n(top of the page) to rerun everything.\n:::\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: C:\\DBD\\kiku-value-premium-replication\\.venv\\share\\jupyter\\kernels\\python3\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.12.12\n---\n",
    "supporting": [
      "10-value-premium-resolved_files\\figure-ipynb"
    ],
    "filters": [],
    "includes": {}
  }
}