{
  "hash": "cac7b08459b74291a83dda5ed542f2e6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"8. Calibrating cash flows from data\"\naliases: [/measuring-leverage.html]\n---\n\nEverything so far priced the cash-flow processes of Table II as given.\nThis chapter is where those numbers come from — and, more importantly,\nwhere they do *not* come from. The characteristic that separates value\nfrom growth in this model is not a return beta, not an average return,\nnot a valuation ratio. It is how hard a claim's *dividends* load on the\npersistent component of consumption growth. That loading is measured by\na regression whose right-hand side contains only consumption. There is\nno return anywhere on the page.\n\nThis discipline is the whole point of the exercise.\n[Chapter 1](01-two-free-numbers.qmd) showed that a DCF can rationalize\nany premium because its discount rate is a free number fitted to the\nreturns it claims to explain. Here the household was calibrated to\nconsumption moments alone ([Chapter 5](05-long-run-risks.qmd)), and\neach claim brings only its cash-flow numbers. When the model later\nproduces a value premium, that premium will be an output, because\nnothing in this chapter ever saw one.\n\nThe plan: build the paper's proxy for expected consumption growth, run\nthe paper's equation (19) on the dividends of the growth, value, and\nmarket claims, and see the risk sit exactly where the model needs it —\nin value's cash flows. Then I explain how these annual slopes relate to\nthe monthly loadings the solver actually uses.\n\n## The economics: one regression, no returns\n\nExpected consumption growth $x_t$ is not observable. But it is\npersistent, and consumption growth is expected growth plus noise:\n$\\Delta c_{t+1} = \\mu + x_t + \\sigma_t \\eta_{t+1}$. Averaging the last\nfew years of realized growth averages the noise away and leaves an\nestimate of where $x_t$ has recently been. The paper uses a two-year\nmoving average of *lagged* consumption growth — lagged, so the current\nyear's dividend innovation never sits on both sides of the regression.\n\nEquation (19) of the paper regresses each claim's dividend growth on\nthat proxy:\n\n$$\n\\Delta d_t \\;=\\; d_0 \\;+\\; \\tilde\\phi \\, \\tfrac{1}{2}\\!\\sum_{k=1}^{2} \\Delta c_{t-k} \\;+\\; \\varepsilon_t .\n$$ {#eq-nineteen}\n\nThe slope $\\tilde\\phi$ is the annual, estimable counterpart of the\nmonthly leverage parameter $\\phi$ from\n[Chapter 5](05-long-run-risks.qmd): it answers *when the slow component\nof consumption growth is one point higher, how much faster do this\nclaim's dividends grow?* If the long-run risks story of the value\npremium is right, value's $\\tilde\\phi$ must come out well above\ngrowth's — measured from cash flows alone, before any return is looked\nat.\n\n::: {.callout-note collapse=\"true\" title=\"Derivation: why the moving average identifies the loading\"}\nTake the dividend process of [Chapter 5](05-long-run-risks.qmd),\n$\\Delta d_{t+1} = \\mu_d + \\phi x_t + \\varphi_\\sigma \\sigma_t u_{t+1}$,\nand the consumption process\n$\\Delta c_{t+1} = \\mu + x_t + \\sigma_t \\eta_{t+1}$. A window-$w$ average\nof lagged consumption growth is\n$\\frac{1}{w}\\sum_k \\Delta c_{t-k} = \\mu + \\frac{1}{w}\\sum_k x_{t-k-1} + \\text{noise}$.\nBecause $x_t$ is highly persistent, the average of its recent lags is\nclose to $x_t$ itself, so the regressor is (noisy) $x_t$ plus a\nconstant, and the population slope of $\\Delta d$ on it is $\\phi$ times\nan attenuation factor that depends on the signal-to-noise ratio of the\nproxy and on time aggregation. The attenuation is common across claims\nrun against the *same* regressor, which is why the regression\nidentifies the *ordering and relative size* of the loadings cleanly,\nwhile the level of each annual slope is not the monthly $\\phi$.\n:::\n\nTwo clocks, one mapping. The regression above runs on annual data,\nbecause that is the frequency at which seven decades of portfolio\ndividends exist. The solver runs on monthly data. The annual slopes are\ntherefore *not* the numbers Table II feeds the solver. They do two\njobs: they establish the ranking the monthly loadings must respect, and\nthey are the data panel of the paper's Table VI. The monthly Table II\nloadings ($\\phi_G = 2.6$, $\\phi_V = 6.2$, $\\phi_m = 2.8$) are then\nchosen so that when the *model* is simulated and equation (19) is run\non the simulated annual data, the model's slopes match the data's —\nthat is Table VI's model panel. Cash flows are matched to cash flows,\non both clocks; returns enter neither.\n\n## Hands-on: measuring the loadings\n\nThe reconstruction of the 1930–2003 series (consumption growth,\nportfolio dividend growth from the book-to-market sort) was built in\n[Chapter 2](02-value-premium-in-the-data.qmd); here I only load the\ncommitted CSVs.\n\n::: {#f4349640 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\n# Data bootstrap: use the repo's committed CSVs, or fetch them when this\n# notebook runs outside the repository.\nfrom pathlib import Path\nimport urllib.request\n\nDATA = Path(\"../../data\")\nif not DATA.exists():\n    DATA = Path(\"data\")\n    DATA.mkdir(exist_ok=True)\n    base = (\"https://raw.githubusercontent.com/tlorans/\"\n            \"kiku-value-premium-replication/main/data/\")\n    for f in (\"annual_panel.csv\", \"consumption_annual.csv\", \"rf_annual.csv\"):\n        if not (DATA / f).exists():\n            urllib.request.urlretrieve(base + f, DATA / f)\n```\n:::\n\n\n::: {#d8d03e0c .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport lrrcs as lrr\n\ndc = pd.read_csv(DATA / \"consumption_annual.csv\").sort_values(\"year\")\npanel = pd.read_csv(DATA / \"annual_panel.csv\")\ny = dc[\"dc\"].to_numpy()\n```\n:::\n\n\n`lrr.expected_growth_proxy` builds the two-year moving average of\nlagged growth. The first two years have no lags to average, so they are\nmissing by construction:\n\n::: {#c6422fb9 .cell execution_count=3}\n``` {.python .cell-code}\nma = lrr.expected_growth_proxy(y, window=2)\npd.DataFrame({\"year\": dc[\"year\"], \"dc\": y, \"ma\": ma}).round(3).head(6)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>dc</th>\n      <th>ma</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1930</td>\n      <td>-0.053</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1931</td>\n      <td>-0.024</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1932</td>\n      <td>-0.088</td>\n      <td>-0.038</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1933</td>\n      <td>-0.021</td>\n      <td>-0.056</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1934</td>\n      <td>0.062</td>\n      <td>-0.055</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>1935</td>\n      <td>0.042</td>\n      <td>0.020</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#18fbb1ad .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\nimport matplotlib\nmatplotlib.use(\"Agg\")\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots(figsize=(6.5, 3.2))\nax.plot(dc[\"year\"], y, color=\"#1b1714\", lw=1.1, label=\"annual Δc\")\nax.plot(dc[\"year\"], ma, color=\"#7a1f1f\", lw=1.8, label=\"two-year MA of lags\")\nax.axhline(0, color=\"#888888\", lw=0.6)\nax.set_xlabel(\"year\")\nax.set_ylabel(\"consumption growth\")\nax.legend(frameon=False, fontsize=9)\nax.spines[[\"top\", \"right\"]].set_visible(False)\nfig.tight_layout()\nplt.show()\n```\n:::\n\n\nNow @eq-nineteen, once per claim. The value portfolio's dividend series\nhas two missing depression years, so the regression masks non-finite\nobservations; the cell prints the count so nothing is silently dropped.\n\n::: {#b3e50b38 .cell execution_count=5}\n``` {.python .cell-code}\ndef dgrowth(claim):\n    rows = panel[panel[\"claim\"] == claim].merge(dc, on=\"year\").sort_values(\"year\")\n    return rows[\"dgrowth\"].to_numpy()\n\ndef phi_tilde(dd):\n    ok = np.isfinite(ma) & np.isfinite(dd)\n    xx = ma[ok] - ma[ok].mean()\n    ee = dd[ok] - dd[ok].mean()\n    return float(xx @ ee / (xx @ xx))\n\nprint({c: round(phi_tilde(dgrowth(c)), 3) for c in (\"Growth\", \"Value\", \"Market\")})\nprint(\"missing value-portfolio years:\", int(np.sum(~np.isfinite(dgrowth(\"Value\")))))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n{'Growth': -0.267, 'Value': 12.129, 'Market': 0.722}\nmissing value-portfolio years: 2\n```\n:::\n:::\n\n\nThere is the risk, in the cash flows, where the model said it would be.\nValue's dividend growth rises hard with the slow component of\nconsumption; growth's barely responds — on this reconstruction it even\nleans slightly the other way — and the market sits in between.\n\n::: {#d8aef398 .cell execution_count=6}\n``` {.python .cell-code code-fold=\"true\"}\nfig, ax = plt.subplots(figsize=(6.5, 3.6))\nfor claim, color in ((\"Growth\", \"#1b1714\"), (\"Value\", \"#7a1f1f\")):\n    dd = dgrowth(claim)\n    ok = np.isfinite(ma) & np.isfinite(dd)\n    ax.scatter(ma[ok], dd[ok], s=16, color=color, label=claim.lower(), alpha=0.8)\n    slope = phi_tilde(dd)\n    grid_x = np.linspace(ma[ok].min(), ma[ok].max(), 2)\n    ax.plot(grid_x, dd[ok].mean() + slope * (grid_x - ma[ok].mean()),\n            color=color, lw=1.4)\nax.set_xlabel(\"two-year MA of lagged Δc\")\nax.set_ylabel(\"dividend growth Δd\")\nax.legend(frameon=False, fontsize=9)\nax.spines[[\"top\", \"right\"]].set_visible(False)\nfig.tight_layout()\nplt.show()\n```\n:::\n\n\nHow do these numbers compare with the paper? My Table VI reports\n$-0.38$ for growth, $2.16$ for value, and $0.66$ for the market; the\nreconstruction prints $-0.267$, $12.129$, and $0.722$. The market slope\nlands close, the growth slope is small and negative in both, and value\nis far above growth in both — but the value *point estimate* is wildly\ndifferent. That is what seventy-odd annual observations buy: a claim's\nslope moves a lot with the data vintage and with the two masked\ndepression years, which fall exactly where consumption swings were\nlargest. The deliverable of this regression is the ordering — value\nloads hard on long-run consumption news, growth does not — and the\nordering is what survives. Do not read a third decimal, or even a first\none, into the value slope.\n\nThe package wraps the same arithmetic.\n`lrr.estimate_long_run_leverage` is the one-claim slope, and\n`lrr.calibrate_from_data` turns consumption and dividend-growth series\ninto a full set of cash-flow parameters. Look at the signatures: there\nis no argument that accepts a return. The function will not take one.\nThat is the structural discipline of the calibration, enforced by the\nAPI itself.\n\n::: {#3acef880 .cell execution_count=7}\n``` {.python .cell-code}\nprint(round(lrr.estimate_long_run_leverage(y, dgrowth(\"Market\"), window=2), 3))\nlrr.print_calibration_summary(\n    lrr.calibrate_from_data(y, market=dgrowth(\"Market\"),\n                            frequency=\"annual\", window=2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0.722\nPortfolio          μ (m)     φ (long-run)   φ_σ      α\n-------------------------------------------------------\nmarket              0.00076     0.722       5.33    0.57\n```\n:::\n:::\n\n\nSame 0.722 as the manual regression, plus the volatility loading\n$\\varphi_\\sigma$ and the short-run correlation $\\alpha$ estimated from\nthe residuals of the same regression — still no returns.\n\nFinally, the mapping to the solver's clock. Table II's monthly loadings\nare the numbers everything downstream prices:\n\n::: {#510817b7 .cell execution_count=8}\n``` {.python .cell-code}\nparams = lrr.get_table_ii_params()\nfor name, d in params.dividends.items():\n    print(f\"{name:8s} monthly phi = {d.phi}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngrowth   monthly phi = 2.6\nvalue    monthly phi = 6.2\nmarket   monthly phi = 2.8\n```\n:::\n:::\n\n\nThe monthly $\\phi$ are larger than the annual slopes because time\naggregation and the noisy proxy attenuate the annual regression (see\nthe derivation callout above). What disciplines them is Table VI's\nmodel panel: simulate the economy at these monthly loadings, aggregate\nto years, rerun @eq-nineteen, and the simulated slopes have to look\nlike the data's. The ordering — $\\phi_V = 6.2$ far above\n$\\phi_G = 2.6$, market at $2.8$ — is the annual regression's ordering,\ncarried to the monthly clock.\n\n## Takeaways\n\n- The characteristic is cash-flow leverage: the slope of dividend\n  growth on a two-year moving average of lagged consumption growth\n  (paper eq. 19). Returns appear nowhere in the calibration, and\n  `calibrate_from_data` has no argument that could accept one.\n- On the reconstruction the slopes print $-0.267$ (growth), $12.129$\n  (value), $0.722$ (market); my Table VI reports $-0.38$, $2.16$,\n  $0.66$. The point estimates are noisy — the ordering, value far above\n  growth with the market in between, is the robust deliverable.\n- The annual slopes are not the solver's inputs. Table II's monthly\n  loadings ($2.6$, $6.2$, $2.8$) are chosen so the model's simulated\n  eq.-19 slopes match the data's; the annual regression fixes the\n  ordering and provides the check.\n\n## Exercises\n\n1. Rerun the three regressions with\n   `lrr.expected_growth_proxy(y, window=3)`. Does the ordering of the\n   slopes survive a different window?\n2. Drop the years 1930–1945 from the sample and re-estimate. Does value\n   still carry the larger $\\tilde\\phi$? What happens to the growth\n   slope's sign?\n3. Call `lrr.calibrate_from_data(y, market=dgrowth(\"Market\"))` and then\n   try to pass the market's *returns* to it in any argument. Confirm\n   from the error that there is no place for them.\n\n::: {.firewall}\n**Where each number comes from.** Every number above is printed by the\ncells on this page: the slopes by the eq.-19 OLS and\n`estimate_long_run_leverage` / `calibrate_from_data` on\n`data/consumption_annual.csv` and `data/annual_panel.csv`, the monthly\nloadings by `get_table_ii_params`; Table VI's $-0.38$ / $2.16$ / $0.66$\nare the paper's prints. Download the chapter as a notebook (top of the\npage) to rerun everything.\n:::\n\n",
    "supporting": [
      "08-calibrating-cash-flows_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}