{
  "hash": "0167a6f77fb6a0e36f28239be7868cce",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"8. Calibrating cash flows from data\"\naliases: [/measuring-leverage.html]\n---\n\nEverything so far priced the cash-flow processes of Table II as given.\nIn this chapter we explain where those numbers come from, and where\nthey do not come from. The characteristic that separates value from\ngrowth in this model is how strongly a claim's dividends load on the\npersistent component of consumption growth. A regression whose\nright-hand side contains only consumption measures the loading, so\nthere is no return anywhere on the page.\n\nKeeping returns out is the point of the exercise.\n[Chapter 1](01-two-free-numbers.qmd) showed that a DCF can rationalize\nany premium because its discount rate is a free number fitted to the\nreturns it claims to explain. Here the household was calibrated to\nconsumption moments alone ([Chapter 5](05-long-run-risks.qmd)), and\neach claim brings only its cash-flow numbers. When the model later\nproduces a value premium, the premium will be an output, because no\nreturn entered the calibration.\n\nFirst, we build the paper's proxy for expected consumption growth.\nSecond, we run the paper's equation (19) on the dividends of the\ngrowth, value, and market claims, and confirm that the risk sits where\nthe model needs it, in value's cash flows. Third, we explain how the\nannual slopes relate to the monthly loadings the solver uses.\n\n## The economics\n\nExpected consumption growth $x_t$ is not observable. But it is\npersistent, and consumption growth is expected growth plus noise:\n$\\Delta c_{t+1} = \\mu + x_t + \\sigma_t \\eta_{t+1}$. Averaging the last\nfew years of realized growth averages the noise away and leaves an\nestimate of where $x_t$ has recently been. The paper uses a two-year\nmoving average of lagged consumption growth. The lag ensures the\ncurrent year's dividend innovation never sits on both sides of the\nregression.\n\nEquation (19) of the paper regresses each claim's dividend growth on\nthat proxy:\n\n$$\n\\Delta d_t \\;=\\; d_0 \\;+\\; \\tilde\\phi \\, \\tfrac{1}{2}\\!\\sum_{k=1}^{2} \\Delta c_{t-k} \\;+\\; \\varepsilon_t .\n$$ {#eq-nineteen}\n\nThe slope $\\tilde\\phi$ is the annual, estimable counterpart of the\nmonthly leverage parameter $\\phi$ from\n[Chapter 5](05-long-run-risks.qmd). It measures how much faster the\nclaim's dividends grow when the slow component of consumption growth\nis one point higher. If the long-run risks story of the value\npremium is right, value's $\\tilde\\phi$ must come out well above\ngrowth's, measured from cash flows alone and before any return is\nlooked at.\n\n::: {.callout-note collapse=\"true\" title=\"Derivation: why the moving average identifies the loading\"}\nTake the dividend process of [Chapter 5](05-long-run-risks.qmd),\n$\\Delta d_{t+1} = \\mu_d + \\phi x_t + \\varphi_\\sigma \\sigma_t u_{t+1}$,\nand the consumption process\n$\\Delta c_{t+1} = \\mu + x_t + \\sigma_t \\eta_{t+1}$. A window-$w$ average\nof lagged consumption growth is\n$\\frac{1}{w}\\sum_k \\Delta c_{t-k} = \\mu + \\frac{1}{w}\\sum_k x_{t-k-1} + \\text{noise}$.\nBecause $x_t$ is highly persistent, the average of its recent lags is\nclose to $x_t$ itself, so the regressor is (noisy) $x_t$ plus a\nconstant, and the population slope of $\\Delta d$ on it is $\\phi$ times\nan attenuation factor that depends on the signal-to-noise ratio of the\nproxy and on time aggregation. The attenuation is common across claims\nrun against the same regressor, which is why the regression\nidentifies the ordering and relative size of the loadings cleanly,\nwhile the level of each annual slope is not the monthly $\\phi$.\n:::\n\nThe regression and the solver run at different frequencies. The\nregression runs on annual data, because portfolio dividends exist at\nthe annual frequency for seven decades. The solver runs on monthly\ndata. The annual slopes are therefore not the numbers Table II feeds\nthe solver. They do two jobs: they establish the ranking the monthly\nloadings must respect, and they are the data panel of the paper's\nTable VI. The monthly Table II loadings ($\\phi_G = 2.6$,\n$\\phi_V = 6.2$, $\\phi_m = 2.8$) are then chosen so that when the model\nis simulated and equation (19) is run on the simulated annual data,\nthe model's slopes match the data's slopes. The match is Table VI's\nmodel panel. Cash flows are matched to cash flows at both frequencies,\nand returns enter neither panel.\n\n## Hands-on: measuring the loadings\n\nThe reconstruction of the 1930 to 2003 series (consumption growth,\nand portfolio dividend growth from the book-to-market sort) was built\nin [Chapter 2](02-value-premium-in-the-data.qmd), so here we only load\nthe committed CSVs.\n\n::: {#534b5f30 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\n# Data bootstrap: use the repo's committed CSVs, or fetch them when this\n# notebook runs outside the repository.\nfrom pathlib import Path\nimport urllib.request\n\nDATA = Path(\"../../data\")\nif not DATA.exists():\n    DATA = Path(\"data\")\n    DATA.mkdir(exist_ok=True)\n    base = (\"https://raw.githubusercontent.com/tlorans/\"\n            \"kiku-value-premium-replication/main/data/\")\n    for f in (\"annual_panel.csv\", \"consumption_annual.csv\", \"rf_annual.csv\"):\n        if not (DATA / f).exists():\n            urllib.request.urlretrieve(base + f, DATA / f)\n```\n:::\n\n\n::: {#513cce60 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport lrrcs as lrr\n\ndc = pd.read_csv(DATA / \"consumption_annual.csv\").sort_values(\"year\")\npanel = pd.read_csv(DATA / \"annual_panel.csv\")\ny = dc[\"dc\"].to_numpy()\n```\n:::\n\n\n`lrr.expected_growth_proxy` builds the two-year moving average of\nlagged growth. The first two years have no lags to average, so they are\nmissing by construction:\n\n::: {#4771ca3d .cell execution_count=3}\n``` {.python .cell-code}\nfrom great_tables import GT\n\nKIKU_GT = dict(table_background_color=\"transparent\", table_font_size=\"0.92rem\",\n               heading_title_font_size=\"1.05rem\", heading_subtitle_font_size=\"0.85rem\",\n               source_notes_font_size=\"0.8rem\", column_labels_font_weight=\"bold\",\n               data_row_padding=\"4px\")\n\nma = lrr.expected_growth_proxy(y, window=2)\nhead = pd.DataFrame({\"year\": dc[\"year\"], \"dc\": y, \"ma\": ma}).head(6)\n(\n    GT(head)\n    .tab_header(title=\"The proxy in the first six sample years\")\n    .cols_label(year=\"Year\", dc=\"Annual growth\", ma=\"Two-year MA of lags\")\n    .fmt_number(columns=[\"dc\", \"ma\"], decimals=3)\n    .sub_missing(columns=\"ma\", missing_text=\"\")\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div id=\"wvatxlejys\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#wvatxlejys table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#wvatxlejys thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#wvatxlejys p { margin: 0; padding: 0; }\n #wvatxlejys .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #wvatxlejys .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #wvatxlejys .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #wvatxlejys .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #wvatxlejys .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #wvatxlejys .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #wvatxlejys .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #wvatxlejys .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #wvatxlejys .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #wvatxlejys .gt_column_spanner_outer:first-child { padding-left: 0; }\n #wvatxlejys .gt_column_spanner_outer:last-child { padding-right: 0; }\n #wvatxlejys .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #wvatxlejys .gt_spanner_row { border-bottom-style: hidden; }\n #wvatxlejys .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #wvatxlejys .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #wvatxlejys .gt_from_md> :first-child { margin-top: 0; }\n #wvatxlejys .gt_from_md> :last-child { margin-bottom: 0; }\n #wvatxlejys .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #wvatxlejys .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #wvatxlejys .gt_indent_1 { text-indent: 5px; }\n #wvatxlejys .gt_indent_2 { text-indent: calc(5px * 2); }\n #wvatxlejys .gt_indent_3 { text-indent: calc(5px * 3); }\n #wvatxlejys .gt_indent_4 { text-indent: calc(5px * 4); }\n #wvatxlejys .gt_indent_5 { text-indent: calc(5px * 5); }\n #wvatxlejys .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #wvatxlejys .gt_row_group_first td { border-top-width: 2px; }\n #wvatxlejys .gt_row_group_first th { border-top-width: 2px; }\n #wvatxlejys .gt_striped { color: #333333; background-color: #F4F4F4; }\n #wvatxlejys .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #wvatxlejys .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #wvatxlejys .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #wvatxlejys .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #wvatxlejys .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #wvatxlejys .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #wvatxlejys .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #wvatxlejys .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #wvatxlejys .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #wvatxlejys .gt_left { text-align: left; }\n #wvatxlejys .gt_center { text-align: center; }\n #wvatxlejys .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #wvatxlejys .gt_font_normal { font-weight: normal; }\n #wvatxlejys .gt_font_bold { font-weight: bold; }\n #wvatxlejys .gt_font_italic { font-style: italic; }\n #wvatxlejys .gt_super { font-size: 65%; }\n #wvatxlejys .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #wvatxlejys .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #wvatxlejys .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #wvatxlejys .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #wvatxlejys .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #wvatxlejys .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\">The proxy in the first six sample years</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"year\">Year</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dc\">Annual growth</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ma\">Two-year MA of lags</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_right\">1930</td>\n    <td class=\"gt_row gt_right\">−0.053</td>\n    <td class=\"gt_row gt_right\"></td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">1931</td>\n    <td class=\"gt_row gt_right\">−0.024</td>\n    <td class=\"gt_row gt_right\"></td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">1932</td>\n    <td class=\"gt_row gt_right\">−0.088</td>\n    <td class=\"gt_row gt_right\">−0.038</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">1933</td>\n    <td class=\"gt_row gt_right\">−0.021</td>\n    <td class=\"gt_row gt_right\">−0.056</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">1934</td>\n    <td class=\"gt_row gt_right\">0.062</td>\n    <td class=\"gt_row gt_right\">−0.055</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_right\">1935</td>\n    <td class=\"gt_row gt_right\">0.042</td>\n    <td class=\"gt_row gt_right\">0.020</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\n::: {#3d8eb1fb .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\nfrom plotnine import (ggplot, aes, geom_line, geom_point, geom_hline, labs,\n                      scale_color_manual, scale_size_manual, theme_minimal,\n                      theme, element_blank, element_line, element_text)\n\nseries = pd.DataFrame({\"year\": dc[\"year\"].to_numpy(),\n                       \"annual Δc\": y,\n                       \"two-year MA of lags\": ma})\nseries = series.melt(id_vars=\"year\", var_name=\"series\", value_name=\"growth\").dropna()\np = (\n    ggplot(series, aes(\"year\", \"growth\", color=\"series\", size=\"series\"))\n    + geom_hline(yintercept=0, color=\"#888888\", size=0.4)\n    + geom_line()\n    + scale_color_manual(values={\"annual Δc\": \"#1b1714\",\n                                 \"two-year MA of lags\": \"#7a1f1f\"})\n    + scale_size_manual(values={\"annual Δc\": 0.8, \"two-year MA of lags\": 1.1})\n    + labs(x=\"year\", y=\"consumption growth\")\n    + theme_minimal(base_size=11)\n    + theme(figure_size=(6.5, 3.2), text=element_text(color=\"#2d2926\"),\n            panel_grid_minor=element_blank(),\n            panel_grid_major=element_line(color=\"#e2d6c4\", size=0.4),\n            axis_line=element_line(color=\"#1b1714\", size=0.5),\n            legend_title=element_blank(), legend_position=\"top\")\n)\np.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Annual consumption growth (black) and the two-year moving average of its lags (red). The red line is the annual picture of the state variable x_t: slow swings the raw series hides.](08-calibrating-cash-flows_files/figure-ipynb/cell-5-output-1.png){width=312 height=153}\n:::\n:::\n\n\nNow we run @eq-nineteen once per claim. The value portfolio's dividend\nseries has two missing depression years, so the regression masks\nnon-finite observations, and the cell prints the count so nothing is\nsilently dropped.\n\n::: {#17fe349f .cell execution_count=5}\n``` {.python .cell-code}\ndef dgrowth(claim):\n    rows = panel[panel[\"claim\"] == claim].merge(dc, on=\"year\").sort_values(\"year\")\n    return rows[\"dgrowth\"].to_numpy()\n\ndef phi_tilde(dd):\n    ok = np.isfinite(ma) & np.isfinite(dd)\n    xx = ma[ok] - ma[ok].mean()\n    ee = dd[ok] - dd[ok].mean()\n    return float(xx @ ee / (xx @ xx))\n\nprint(\"missing value-portfolio years:\", int(np.sum(~np.isfinite(dgrowth(\"Value\")))))\nslopes = pd.DataFrame({\n    \"claim\": [\"Growth\", \"Value\", \"Market\"],\n    \"slope\": [phi_tilde(dgrowth(c)) for c in (\"Growth\", \"Value\", \"Market\")],\n})\n(\n    GT(slopes)\n    .tab_header(title=\"Annual leverage slopes from equation (19)\")\n    .cols_label(claim=\"\", slope=\"Slope on the MA proxy\")\n    .fmt_number(columns=\"slope\", decimals=3)\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmissing value-portfolio years: 2\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div id=\"nscrohnibe\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#nscrohnibe table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#nscrohnibe thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#nscrohnibe p { margin: 0; padding: 0; }\n #nscrohnibe .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #nscrohnibe .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #nscrohnibe .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #nscrohnibe .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #nscrohnibe .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #nscrohnibe .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #nscrohnibe .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #nscrohnibe .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #nscrohnibe .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #nscrohnibe .gt_column_spanner_outer:first-child { padding-left: 0; }\n #nscrohnibe .gt_column_spanner_outer:last-child { padding-right: 0; }\n #nscrohnibe .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #nscrohnibe .gt_spanner_row { border-bottom-style: hidden; }\n #nscrohnibe .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #nscrohnibe .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #nscrohnibe .gt_from_md> :first-child { margin-top: 0; }\n #nscrohnibe .gt_from_md> :last-child { margin-bottom: 0; }\n #nscrohnibe .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #nscrohnibe .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #nscrohnibe .gt_indent_1 { text-indent: 5px; }\n #nscrohnibe .gt_indent_2 { text-indent: calc(5px * 2); }\n #nscrohnibe .gt_indent_3 { text-indent: calc(5px * 3); }\n #nscrohnibe .gt_indent_4 { text-indent: calc(5px * 4); }\n #nscrohnibe .gt_indent_5 { text-indent: calc(5px * 5); }\n #nscrohnibe .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #nscrohnibe .gt_row_group_first td { border-top-width: 2px; }\n #nscrohnibe .gt_row_group_first th { border-top-width: 2px; }\n #nscrohnibe .gt_striped { color: #333333; background-color: #F4F4F4; }\n #nscrohnibe .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #nscrohnibe .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #nscrohnibe .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #nscrohnibe .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #nscrohnibe .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #nscrohnibe .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #nscrohnibe .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #nscrohnibe .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #nscrohnibe .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #nscrohnibe .gt_left { text-align: left; }\n #nscrohnibe .gt_center { text-align: center; }\n #nscrohnibe .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #nscrohnibe .gt_font_normal { font-weight: normal; }\n #nscrohnibe .gt_font_bold { font-weight: bold; }\n #nscrohnibe .gt_font_italic { font-style: italic; }\n #nscrohnibe .gt_super { font-size: 65%; }\n #nscrohnibe .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #nscrohnibe .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #nscrohnibe .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #nscrohnibe .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #nscrohnibe .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #nscrohnibe .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal\">Annual leverage slopes from equation (19)</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"claim\"></th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"slope\">Slope on the MA proxy</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">Growth</td>\n    <td class=\"gt_row gt_right\">−0.267</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Value</td>\n    <td class=\"gt_row gt_right\">12.129</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Market</td>\n    <td class=\"gt_row gt_right\">0.722</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\nThe risk sits in the cash flows, where the model needs it.\nValue's dividend growth rises steeply with the slow component of\nconsumption. Growth's dividend growth barely responds, and on the\nreconstruction here the slope is even slightly negative. The market\nsits in between.\n\n::: {#9d3c6909 .cell execution_count=6}\n``` {.python .cell-code code-fold=\"true\"}\npts, fits = [], []\nfor claim in (\"Growth\", \"Value\"):\n    dd = dgrowth(claim)\n    ok = np.isfinite(ma) & np.isfinite(dd)\n    pts.append(pd.DataFrame({\"claim\": claim.lower(), \"ma\": ma[ok], \"dd\": dd[ok]}))\n    grid_x = np.linspace(ma[ok].min(), ma[ok].max(), 2)\n    fits.append(pd.DataFrame({\n        \"claim\": claim.lower(), \"ma\": grid_x,\n        \"dd\": dd[ok].mean() + phi_tilde(dd) * (grid_x - ma[ok].mean()),\n    }))\npts, fits = pd.concat(pts), pd.concat(fits)\np = (\n    ggplot(pts, aes(\"ma\", \"dd\", color=\"claim\"))\n    + geom_point(size=1.8, alpha=0.8)\n    + geom_line(data=fits, size=0.7)\n    + scale_color_manual(values={\"growth\": \"#1b1714\", \"value\": \"#7a1f1f\"})\n    + labs(x=\"two-year MA of lagged Δc\", y=\"dividend growth Δd\")\n    + theme_minimal(base_size=11)\n    + theme(figure_size=(6.5, 3.6), text=element_text(color=\"#2d2926\"),\n            panel_grid_minor=element_blank(),\n            panel_grid_major=element_line(color=\"#e2d6c4\", size=0.4),\n            axis_line=element_line(color=\"#1b1714\", size=0.5),\n            legend_title=element_blank(), legend_position=\"top\")\n)\np.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Dividend growth against the two-year MA of lagged consumption growth, with the OLS fit for each claim. Value's slope is far steeper than growth's. No return enters this picture.](08-calibrating-cash-flows_files/figure-ipynb/cell-7-output-1.png){width=312 height=172}\n:::\n:::\n\n\nCompare the estimates with the paper. The paper's Table VI reports\n$-0.38$ for growth, $2.16$ for value, and $0.66$ for the market, and\nthe reconstruction estimates $-0.267$, $12.129$, and $0.722$. The market\nslope lands close, and the growth slope is small and negative in both.\nThe value point estimate is far larger in the reconstruction than in\nthe paper. Seventy-odd annual observations explain the gap. A claim's\nslope moves a lot with the data vintage and with the two masked\ndepression years, which fall exactly where consumption swings were\nlargest. The reliable output of the regression is the ordering, in\nwhich value loads heavily on long-run consumption news and growth does\nnot. Do not read precision into the value slope. Even its first digit\nis not reliable.\n\nThe package wraps the same arithmetic.\n`lrr.estimate_long_run_leverage` is the one-claim slope, and\n`lrr.calibrate_from_data` turns consumption and dividend-growth series\ninto a full set of cash-flow parameters. Look at the signatures. There\nis no argument that accepts a return, so the functions cannot take\none. The API itself keeps returns out of the calibration.\n\n::: {#2863e181 .cell execution_count=7}\n``` {.python .cell-code}\nprint(round(lrr.estimate_long_run_leverage(y, dgrowth(\"Market\"), window=2), 3))\ndiv = lrr.calibrate_from_data(y, market=dgrowth(\"Market\"),\n                              frequency=\"annual\", window=2)\ncal = pd.DataFrame({\n    \"portfolio\": list(div),\n    \"mu\": [d.mu for d in div.values()],\n    \"phi\": [d.phi for d in div.values()],\n    \"phi_sigma\": [d.phi_sigma for d in div.values()],\n    \"alpha\": [d.alpha for d in div.values()],\n})\n(\n    GT(cal)\n    .tab_header(title=\"Calibrated cash-flow parameters from the data\")\n    .cols_label(portfolio=\"Portfolio\", mu=\"μ (monthly)\", phi=\"φ (long-run)\",\n                phi_sigma=\"φ_σ\", alpha=\"α\")\n    .fmt_number(columns=\"mu\", decimals=5)\n    .fmt_number(columns=\"phi\", decimals=3)\n    .fmt_number(columns=[\"phi_sigma\", \"alpha\"], decimals=2)\n    .tab_source_note(\"Computed by calibrate_from_data on the consumption and \"\n                     \"market dividend series. No return enters.\")\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0.722\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div id=\"zkzlvmegbk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#zkzlvmegbk table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#zkzlvmegbk thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#zkzlvmegbk p { margin: 0; padding: 0; }\n #zkzlvmegbk .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #zkzlvmegbk .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #zkzlvmegbk .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #zkzlvmegbk .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #zkzlvmegbk .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #zkzlvmegbk .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #zkzlvmegbk .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #zkzlvmegbk .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #zkzlvmegbk .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #zkzlvmegbk .gt_column_spanner_outer:first-child { padding-left: 0; }\n #zkzlvmegbk .gt_column_spanner_outer:last-child { padding-right: 0; }\n #zkzlvmegbk .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #zkzlvmegbk .gt_spanner_row { border-bottom-style: hidden; }\n #zkzlvmegbk .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #zkzlvmegbk .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #zkzlvmegbk .gt_from_md> :first-child { margin-top: 0; }\n #zkzlvmegbk .gt_from_md> :last-child { margin-bottom: 0; }\n #zkzlvmegbk .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #zkzlvmegbk .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #zkzlvmegbk .gt_indent_1 { text-indent: 5px; }\n #zkzlvmegbk .gt_indent_2 { text-indent: calc(5px * 2); }\n #zkzlvmegbk .gt_indent_3 { text-indent: calc(5px * 3); }\n #zkzlvmegbk .gt_indent_4 { text-indent: calc(5px * 4); }\n #zkzlvmegbk .gt_indent_5 { text-indent: calc(5px * 5); }\n #zkzlvmegbk .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #zkzlvmegbk .gt_row_group_first td { border-top-width: 2px; }\n #zkzlvmegbk .gt_row_group_first th { border-top-width: 2px; }\n #zkzlvmegbk .gt_striped { color: #333333; background-color: #F4F4F4; }\n #zkzlvmegbk .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #zkzlvmegbk .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #zkzlvmegbk .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #zkzlvmegbk .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #zkzlvmegbk .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #zkzlvmegbk .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #zkzlvmegbk .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #zkzlvmegbk .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #zkzlvmegbk .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #zkzlvmegbk .gt_left { text-align: left; }\n #zkzlvmegbk .gt_center { text-align: center; }\n #zkzlvmegbk .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #zkzlvmegbk .gt_font_normal { font-weight: normal; }\n #zkzlvmegbk .gt_font_bold { font-weight: bold; }\n #zkzlvmegbk .gt_font_italic { font-style: italic; }\n #zkzlvmegbk .gt_super { font-size: 65%; }\n #zkzlvmegbk .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #zkzlvmegbk .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #zkzlvmegbk .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #zkzlvmegbk .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #zkzlvmegbk .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #zkzlvmegbk .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal\">Calibrated cash-flow parameters from the data</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"portfolio\">Portfolio</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mu\">μ (monthly)</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"phi\">φ (long-run)</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"phi_sigma\">φ_σ</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alpha\">α</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">market</td>\n    <td class=\"gt_row gt_right\">0.00076</td>\n    <td class=\"gt_row gt_right\">0.722</td>\n    <td class=\"gt_row gt_right\">5.33</td>\n    <td class=\"gt_row gt_right\">0.57</td>\n  </tr>\n</tbody>\n<tfoot><tr class=\"gt_sourcenotes\"><td class=\"gt_sourcenote\" colspan=\"5\"><span class=\"gt_from_md\">Computed by calibrate_from_data on the consumption and market dividend series. No return enters.</span></td></tr></tfoot>\n</table>\n\n</div>\n```\n:::\n:::\n\n\nThe table shows the same 0.722 as the manual regression, plus the\nvolatility loading $\\varphi_\\sigma$ and the short-run correlation\n$\\alpha$, both estimated from the residuals of the same regression. No\nreturns enter here either.\n\nFinally, we map the annual estimates to the solver's monthly frequency.\nTable II's monthly loadings are the inputs to everything downstream:\n\n::: {#2806410a .cell execution_count=8}\n``` {.python .cell-code}\nparams = lrr.get_table_ii_params()\nmphi = pd.DataFrame({\n    \"claim\": list(params.dividends),\n    \"phi\": [d.phi for d in params.dividends.values()],\n})\n(\n    GT(mphi)\n    .tab_header(title=\"Monthly leverage loadings in Table II\")\n    .cols_label(claim=\"\", phi=\"Monthly φ\")\n    .fmt_number(columns=\"phi\", decimals=1)\n    .tab_options(**KIKU_GT)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div id=\"kyfgzuiunz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#kyfgzuiunz table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#kyfgzuiunz thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#kyfgzuiunz p { margin: 0; padding: 0; }\n #kyfgzuiunz .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 0.92rem; font-weight: normal; font-style: normal; background-color: transparent; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #kyfgzuiunz .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #kyfgzuiunz .gt_title { color: #333333; font-size: 1.05rem; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: transparent; border-bottom-width: 0; }\n #kyfgzuiunz .gt_subtitle { color: #333333; font-size: 0.85rem; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: transparent; border-top-width: 0; }\n #kyfgzuiunz .gt_heading { background-color: transparent; text-align: center; border-bottom-color: transparent; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #kyfgzuiunz .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #kyfgzuiunz .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #kyfgzuiunz .gt_col_heading { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #kyfgzuiunz .gt_column_spanner_outer { color: #333333; background-color: transparent; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #kyfgzuiunz .gt_column_spanner_outer:first-child { padding-left: 0; }\n #kyfgzuiunz .gt_column_spanner_outer:last-child { padding-right: 0; }\n #kyfgzuiunz .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #kyfgzuiunz .gt_spanner_row { border-bottom-style: hidden; }\n #kyfgzuiunz .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #kyfgzuiunz .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #kyfgzuiunz .gt_from_md> :first-child { margin-top: 0; }\n #kyfgzuiunz .gt_from_md> :last-child { margin-bottom: 0; }\n #kyfgzuiunz .gt_row { padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #kyfgzuiunz .gt_stub { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #kyfgzuiunz .gt_indent_1 { text-indent: 5px; }\n #kyfgzuiunz .gt_indent_2 { text-indent: calc(5px * 2); }\n #kyfgzuiunz .gt_indent_3 { text-indent: calc(5px * 3); }\n #kyfgzuiunz .gt_indent_4 { text-indent: calc(5px * 4); }\n #kyfgzuiunz .gt_indent_5 { text-indent: calc(5px * 5); }\n #kyfgzuiunz .gt_stub_row_group { color: #333333; background-color: transparent; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #kyfgzuiunz .gt_row_group_first td { border-top-width: 2px; }\n #kyfgzuiunz .gt_row_group_first th { border-top-width: 2px; }\n #kyfgzuiunz .gt_striped { color: #333333; background-color: #F4F4F4; }\n #kyfgzuiunz .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #kyfgzuiunz .gt_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #kyfgzuiunz .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #kyfgzuiunz .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #kyfgzuiunz .gt_grand_summary_row { color: #333333; background-color: transparent; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #kyfgzuiunz .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #kyfgzuiunz .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #kyfgzuiunz .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #kyfgzuiunz .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #kyfgzuiunz .gt_left { text-align: left; }\n #kyfgzuiunz .gt_center { text-align: center; }\n #kyfgzuiunz .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #kyfgzuiunz .gt_font_normal { font-weight: normal; }\n #kyfgzuiunz .gt_font_bold { font-weight: bold; }\n #kyfgzuiunz .gt_font_italic { font-style: italic; }\n #kyfgzuiunz .gt_super { font-size: 65%; }\n #kyfgzuiunz .gt_footnotes { color: font-color(transparent); background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #kyfgzuiunz .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #kyfgzuiunz .gt_sourcenotes { color: #333333; background-color: transparent; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #kyfgzuiunz .gt_sourcenote { font-size: 0.8rem; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #kyfgzuiunz .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #kyfgzuiunz .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal\">Monthly leverage loadings in Table II</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"claim\"></th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"phi\">Monthly φ</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">growth</td>\n    <td class=\"gt_row gt_right\">2.6</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">value</td>\n    <td class=\"gt_row gt_right\">6.2</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">market</td>\n    <td class=\"gt_row gt_right\">2.8</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\nThe monthly $\\phi$ are larger than the annual slopes because time\naggregation and the noisy proxy attenuate the annual regression (see\nthe derivation callout above). Table VI's model panel pins the monthly\nvalues down. First, simulate the economy at the monthly loadings.\nSecond, aggregate the simulated data to years. Third, rerun\n@eq-nineteen and require the simulated slopes to look like the data's\nslopes. The ordering, with $\\phi_V = 6.2$ far above $\\phi_G = 2.6$ and\nthe market at $2.8$, is the annual regression's ordering carried to\nthe monthly frequency.\n\n## Takeaways\n\n- The characteristic is cash-flow leverage: the slope of dividend\n  growth on a two-year moving average of lagged consumption growth\n  (paper eq. 19). Returns appear nowhere in the calibration, and\n  `calibrate_from_data` has no argument that could accept one.\n- On the reconstruction the slopes come out at $-0.267$ (growth), $12.129$\n  (value), and $0.722$ (market), and the paper's Table VI reports $-0.38$,\n  $2.16$, and $0.66$. The point estimates are noisy. The ordering,\n  with value far above growth and the market in between, is the\n  reliable result.\n- The annual slopes are not the solver's inputs. Table II's monthly\n  loadings ($2.6$, $6.2$, $2.8$) are chosen so the model's simulated\n  equation (19) slopes match the data's slopes. The annual regression\n  fixes the ordering and provides the check.\n\n::: {.callout-note collapse=\"true\" title=\"Recall\"}\n\nAnswer from memory before opening.\n\n1. What is the model's characteristic, and from what is it measured?\n2. Which quantity is the reliable result of the equation (19)\n   regression: the slope levels or the ordering?\n3. Which loadings actually feed the solver, and what role do the annual\n   slopes play?\n\n**Answers.**\n\n1. Cash-flow leverage: the slope of dividend growth on a two-year\n   moving average of lagged consumption growth. Dividends alone; no\n   return enters.\n2. The ordering, value far above growth with the market between. The\n   point estimates are noisy.\n3. Table II's monthly loadings (2.6, 6.2, 2.8); the annual regression\n   fixes the ordering and provides the check.\n\n:::\n\n## Exercises\n\n1. Rerun the three regressions with\n   `lrr.expected_growth_proxy(y, window=3)`. Does the ordering of the\n   slopes survive a different window?\n2. Drop the years 1930 to 1945 from the sample and re-estimate. Does\n   value still carry the larger $\\tilde\\phi$? What happens to the\n   growth slope's sign?\n3. Call `lrr.calibrate_from_data(y, market=dgrowth(\"Market\"))` and then\n   try to pass the market's returns to it in any argument. Confirm\n   from the error that there is no place for them.\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n::: {#00e58883 .cell execution_count=9}\n``` {.python .cell-code code-fold=\"true\"}\ndef slope(dd, proxy):\n    ok = np.isfinite(proxy) & np.isfinite(dd)\n    xx = proxy[ok] - proxy[ok].mean()\n    ee = dd[ok] - dd[ok].mean()\n    return float(xx @ ee / (xx @ xx))\n\n# Exercise 1: a different window\nma3 = lrr.expected_growth_proxy(y, window=3)\nfor claim in (\"Growth\", \"Value\", \"Market\"):\n    print(f\"{claim:8s}  window 2: {slope(dgrowth(claim), ma):7.3f}\"\n          f\"   window 3: {slope(dgrowth(claim), ma3):7.3f}\")\n\n# Exercise 2: dropping 1930-1945\nkeep = dc[\"year\"].to_numpy() >= 1946\nma_post = lrr.expected_growth_proxy(y[keep], window=2)\ndg_post = {c: dgrowth(c)[keep] for c in (\"Growth\", \"Value\", \"Market\")}\nfor claim in (\"Growth\", \"Value\", \"Market\"):\n    print(f\"{claim:8s}  post-war slope: {slope(dg_post[claim], ma_post):7.3f}\")\n\n# Exercise 3: no place for a return\ntry:\n    lrr.calibrate_from_data(y, returns=dgrowth(\"Market\"))\nexcept TypeError as err:\n    print(f\"TypeError: {err}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGrowth    window 2:  -0.267   window 3:  -0.702\nValue     window 2:  12.129   window 3:  -5.503\nMarket    window 2:   0.722   window 3:  -0.414\nGrowth    post-war slope:  -2.459\nValue     post-war slope:   0.598\nMarket    post-war slope:  -0.901\nTypeError: calibrate_from_data() got an unexpected keyword argument 'returns'\n```\n:::\n:::\n\n\nThe window change does not preserve the slopes. At window 3 the value\nslope turns negative (-5.50), so the level of the annual leverage\nestimate is fragile to the proxy window. The post-war sample keeps the\nvalue-above-growth ordering but collapses the value slope from 12.13 to\n0.60, and the growth slope stays negative throughout. Levels are fragile\nhere, which is why the chapter leans on the paper's Table VI numbers for\nmagnitudes. And\nthere is no returns argument to pass, because the signature rejects the\nkeyword outright.\n\n:::\n\n::: {.firewall}\n**Where each number comes from.** Every number above is printed by the\ncells on this page: the slopes by the eq.-19 OLS and\n`estimate_long_run_leverage` / `calibrate_from_data` on\n`data/consumption_annual.csv` and `data/annual_panel.csv`, the monthly\nloadings by `get_table_ii_params`; Table VI's $-0.38$ / $2.16$ / $0.66$\nare the paper's prints. Download the chapter as a notebook (top of the\npage) to rerun everything.\n:::\n\n::: {.callout-note title=\"Where to go next\"}\nThe canonical treatment of this chapter's topic is Kiku (2006), the cash-flow estimation section\n([references](../reference/references.qmd)). Stuck, or spot an\nerror? Open an issue at the\n[repository](https://github.com/tlorans/kiku-value-premium-replication/issues), or ask your agent to walk through it with\nyou.\n:::\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: C:\\DBD\\kiku-value-premium-replication\\.venv\\share\\jupyter\\kernels\\python3\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.12.12\n---\n",
    "supporting": [
      "08-calibrating-cash-flows_files\\figure-ipynb"
    ],
    "filters": [],
    "includes": {}
  }
}